### ISSUE TITLE
[Obsolete Links] "C++ API reference" and "O3DE UI line edit component" chapters refers to Lumberyard documentation

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#100]
Link to page: https://o3deorg.netlify.app/docs/tools-ui/component-library/

Every "C++ API reference" subchapter in the "UI component library" chapter, includes hyperlinks to "Lumberyard Tools UI C++ API Reference". The following pages are affected:

- O3DE UI breadcrumb navigation component
- O3DE UI browse edit component
- O3DE UI button styles
- O3DE UI card component
- O3DE UI checkbox component
- O3DE UI combobox component
- O3DE UI filtered search widget
- O3DE UI line edit component
- O3DE UI menu component
- O3DE UI progress indicators
- O3DE UI radio button style
- O3DE UI scrollbar styles
- O3DE UI sliders
- O3DE UI spinbox component
- O3DE UI styled dock widget
- O3DE UI tab component
- O3DE UI table view component
- O3DE UI toggle switch component
- O3DE UI tree view component

**Comment by FiniteStateGit** [comment]
The links now point to: https://o3deorg.netlify.app/docs/api/frameworks/azqtcomponents/namespace_az_qt_components.html .
@LB-RobertBaczkowski Can this be closed?

**Comment by LB-RobertBaczkowski** [comment]
The links work correctly, closing the issue.
