### ISSUE TITLE
[DOCS] Setup from Github only contains instructions for the Windows platform

### ISSUE THREAD

**Issue by N8n5h** [o3de/o3de.org#1002]
## Describe the issue briefly

Current instructions for setting up the engine from Github are only in terms of Windows, maybe the article could be expanded or separated into multiple for each platform?

## Which page(s) / section(s) are affected?

https://o3de.org/docs/welcome-guide/setup/setup-from-github

## Does this work have an engineering dependency? What is it?

sig/platform

**Comment by willihay** [comment]
The Get Started topics were updated with setup instructions for Linux in this PR: 
https://github.com/o3de/o3de.org/pull/1085

Instructions for other/future supported platforms can follow a similar pattern.
