### ISSUE TITLE
[Missing information] "C++ API reference" subchapter is not included  in "O3DE UI reflected property editor" chapter

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#101]
Link to page : https://o3deorg.netlify.app/docs/tools-ui/component-library/uidev-reflected-property-editor-component/

The "O3DE UI reflected property editor" chapter is the only one in the "UI component library" which does not include a section on C++ API reference.

**Comment by FiniteStateGit** [comment]
Fixed with PR https://github.com/o3de/o3de.org/pull/850 .

**Comment by LB-RobertBaczkowski** [comment]
The page has not been updated yet, will close as soon as it happens.
