### ISSUE TITLE
[DOCS][BUG] LyTestTools Getting Starting Guide is Missing the Example Script

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de.org#1024]
The LyTestTools getting starting guide says there's a file called "test_system_example.py", but it doesn't exist.  Not in the development branch at least.

https://o3de.org/docs/user-guide/testing/lytesttools/getting-started/
The getting starting guide says there's a file called "test_system_example.py", but i dont see it..

## Impacted page(s)
https://o3de.org/docs/user-guide/testing/lytesttools/getting-started/

**Comment by evanchia-ly-sdets** [comment]
Current documentation and example tests should be utilized. This tutorial page should point towards existing docs/tests (i.e. sanity_tests.py)
