### ISSUE TITLE
[DOCS] Add documentation of ViewportRequestBus.

### ISSUE THREAD

**Issue by FiniteStateGit** [o3de/o3de.org#1028]
## Describe the issue briefly

Add page to document ViewportRequestBus.

## Which page(s) / section(s) are affected?

https://o3de.org/docs/user-guide/editor/viewport/

## Does this work have an engineering dependency? What is it?

None known.

**Comment by hultonha** [comment]
@micronAMZN This looks like something pretty quick I can pick-up. It looks like this should go in the engine developer guide (https://development--o3deorg.netlify.app/docs/engine-dev/frameworks/). Is there a preferred home for this?

The other question is should we add a page for this or should we instead rely on the API refs that will be generated as this may also be sufficient (tagging @chanmosq for visibility). It looks like the API does already have comments but is missing an API header for the bus itself, I could add that as a separate PR even more quickly.

```c++
namespace AzFramework
{
    // <missing right now>
    class ViewportRequests : public AZ::EBusTraits
    {
    public:
        static const AZ::EBusHandlerPolicy HandlerPolicy = AZ::EBusHandlerPolicy::Single;
        static const AZ::EBusAddressPolicy AddressPolicy = AZ::EBusAddressPolicy::ById;
        using BusIdType = ViewportId;

        static void Reflect(AZ::ReflectContext* context);

        //! Gets the current camera's world to view matrix.
        virtual const AZ::Matrix4x4& GetCameraViewMatrix() const = 0;
        //! Gets the current camera's world to view matrix as a Matrix3x4.
        virtual AZ::Matrix3x4 GetCameraViewMatrixAsMatrix3x4() const = 0;
        //! Sets the current camera's world to view matrix.
        virtual void SetCameraViewMatrix(const AZ::Matrix4x4& matrix) = 0;
        //! Gets the current camera's projection (view to clip) matrix.
        virtual const AZ::Matrix4x4& GetCameraProjectionMatrix() const = 0;
        //! Sets the current camera's projection (view to clip) matrix.
        virtual void SetCameraProjectionMatrix(const AZ::Matrix4x4& matrix) = 0;
        //! Convenience method, gets the AZ::Transform corresponding to this camera's world to view matrix.
        virtual AZ::Transform GetCameraTransform() const = 0;
        //! Convenience method, sets the camera's world to view matrix from this AZ::Transform.
        virtual void SetCameraTransform(const AZ::Transform& transform) = 0;

    protected:
        ~ViewportRequests() = default;
    };

    using ViewportRequestBus = AZ::EBus<ViewportRequests>;
}
```

**Comment by hultonha** [comment]
I've linked the relevant PR in the `Development` parameter on the right of the ticket. Discussed with @chanmosq offline and we agreed with the API doc generation this should be sufficient for now. If further documentation for this would be useful in the engine developer guide (see https://development--o3deorg.netlify.app/docs/engine-dev/) then please feel free to reopen this ticket for create a new one.

**Comment by chanmosq** [comment]
Thank you @hultonha!
