### ISSUE TITLE
[BUG][WEBSITE] Splash image is cropped oddly.

### ISSUE THREAD

**Issue by micronAMZN** [o3de/o3de.org#1046]
## Describe the bug

The Deadhaus Sonata splash image on the front page is cropped in such a way that the game title watermark reads "Dead Son" if the browser window on a desktop machine is sized to any width less than the width of the splash image, which is almost always going to be the case.

## Reproduction steps

Open O3DE.org on a desktop in any browser and scale the browser window width.

## Expected behavior

I expect to see the full title of the game, or at the very least, not to see the words "Dead Son".

* **OS**: Any Desktop
* **Browser**: Firefox, Edge, Chrome

**Comment by FiniteStateGit** [comment]
Closing this as resolved by #1214, landing page redesigned for 21.11 release.
