### ISSUE TITLE
[Obsolete Information]: O3DE Framework API reference: AzQtComponents redirects to documentation referencing Lumberyard version 1.25

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#108]
Link: https://o3deorg.netlify.app/docs/api/frameworks/

The link AzQtComponents (https://o3deorg.netlify.app/docs/api/frameworks/azqtcomponents/) redirects to documentation mentioning Amazon Lumberyard version 1.25.

**Comment by FiniteStateGit** [comment]
This is now linking correctly to the Open 3D Engine AzQtComponents API Reference, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
