### ISSUE TITLE
[ISSUE][DOCS] Multiple Simulate destruction with NVIDIA Blast documentation page issues

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de.org#1080]
## Describe the issue

There are multiple issues with the "Simulate destruction with NVIDIA Blast" documentation page. They will be listed below along with Expected experience wherever appropriate:

1. Page screenshots show out of date Blast Family and Blast Family Mesh Data components:
Page:
![ui-blast-add-blast-asset](https://user-images.githubusercontent.com/86952082/138260284-c2300741-f39b-4f52-8c31-14c89c5c1e9c.png)
![ui-blast-add-blast-mesh-data](https://user-images.githubusercontent.com/86952082/138260347-fef93e09-f68b-4454-8bd8-e3d8b2bc0302.png)
![ui-blast-family-mesh-data-add-mesh](https://user-images.githubusercontent.com/86952082/138260673-a8a972b1-32d5-4c84-9294-9d142188e162.png)
Engine:
![Blast1](https://user-images.githubusercontent.com/86952082/138260311-f7b28b6b-7132-4f6d-9bf4-25a265c4fbdb.PNG)
![Blast2](https://user-images.githubusercontent.com/86952082/138260361-60ab0eaa-4e7b-4b66-9831-4815643ec754.PNG)

2. Deprecated PhysX Terrain is mentioned in multiple sections:
* Note: `...on a PhysX collision surface such as PhysX Terrain.`
* Create an entity for NVIDIA Blast: `1. Ensure that the terrain has a PhysX Terrain level component. In Level inspector, choose Add Component and select PhysX Terrain from the component list.` 
* Test NVIDIA Blast destruction simulation: `Because the blast asset has been exported from Houdini with Static root disabled, and a PhysX Terrain level component...`
**Expected**: Deprecated components are not mentioned in the documentation.

3. Due to issues 1. and 2. the instruction could be considered deprecated.
**Expected**: Documentation instructions are up to date with how they work in engine.

## Impacted page(s)

https://o3de.org/docs/user-guide/interactivity/physics/nvidia-blast/simulate/

**Comment by micronAMZN** [comment]
Closing because the pages are set to draft, and Blast is now non-canonical.

**Comment by LB-ArturZieba** [comment]
Confirming the issue has been closed based on the above comment.
