### ISSUE TITLE
[Website Fixes] CSS and HTML Fixes for July 3rd

### ISSUE THREAD

**Issue by svitlani** [o3de/o3de.org#1099]
[Migrated from JIRA LYN-6043]

Search not working
(Interaction = User clicks the search icon and the search field + magnifying glass appears. User can then use the search field and button) (this task has been completed by Sindhu)
Fix the Mobile Menu in the Nav Bar
Make mobile menu usable to match the design (this task has been completed by Danilo)
 

Stop constant refresh of pages when navigating the pages
On the docs pages, when a user clicks from one left hand nav to go to from one page to another, it keeps refreshing the page. 
We would like to only update the content section of the page, and leave the top nav and the left hand side nav. If you need clarification, please let me know.

**Comment by yuyihsu** [comment]
this issue has been resolved.
