### ISSUE TITLE
[Formatting]: O3DE Release notes: The page layout is breaking on resizing its width

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#110]
Link: https://o3deorg.netlify.app/docs/release-notes/

The page breaks the left menu's layout when their window is resized below around 60% of their original width on 1920x1080 resolution and completely vanish when their window is resized below around 30% of its original width on 1920x1080 resolution. This may be a substantial issue on mobile devices such as tablets or phones.

**Comment by FiniteStateGit** [comment]
Table of contents navigation collapses and moves to the hamburger menu on resize.  Tested mobile with same results.  @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
