### ISSUE TITLE
[Learn Page] CSS Fixes

### ISSUE THREAD

**Issue by svitlani** [o3de/o3de.org#1102]
[Migrated from JIRA LYN-6116]

Fix CSS for the Learn Page (D).
Fix the current CSS for the Learn Page to match the design spec.

It is important to note that the Learn Page (D) must be a different subdomain, which is why it's navigation bar differs from the main O3DE Page. We must have O3DE Learn as the prominent logo.

**Comment by yuyihsu** [comment]
this has been resolved.
