### ISSUE TITLE
[Landing Page] Update Product Features and Our Partners

### ISSUE THREAD

**Issue by svitlani** [o3de/o3de.org#1104]
[Migrated from JIRA  LYN-6197]

Acceptance Criteria:
Product Features
Update background to be #111111.
Height needs to be updated.
Images:
Update to overflow behaviour.
Update sizes.
Text:
Needs to be aligned correctly.
Update font size and line heights.
Our Partners
Switch position after Product Features.
Implement Carousel functionality with auto scroll
Implement Pagination below Carousel to let user manually scroll through Partner list.
Update Heading and Subheading to match spec.
Update background to be #EEEEEE.

**Comment by yuyihsu** [comment]
this has been resolved.
