### ISSUE TITLE
[ISSUE][DOCS] Broken formatting in the Configure and Build doc

### ISSUE THREAD

**Issue by N8n5h** [o3de/o3de.org#1116]
## Describe the issue

Error formatting in the documentation at the start of the first paragraph: "Building ``` **Open 3D Engine (O3DE)**```..."

![image](https://user-images.githubusercontent.com/42382648/139313108-39fa718d-4c95-486a-82e5-4ed88628440e.png)

## Impacted page(s)

https://o3de.org/docs/user-guide/build/configure-and-build/

**Comment by sptramer** [comment]
Will be closed by #1085.

**Comment by FiniteStateGit** [comment]
Closing, resolved by #1085.
