### ISSUE TITLE
[Landing page] Replace the hero image with new assets 

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de.org#1133]
## Describe the feature you'd like available on the website

Replace the hero image for the next release

## Proposed implementation

Depend on the assets we can get, we have two possible ways to implement the new image
1. Have a set of static images rotating on the banner area
2. Show a video with clips from various game scenes to show the variety of contents people can create using O3DE.

## Available alternatives

Replace the current hero image with another one from Apocalypse.

**Comment by AMZN-daimini** [comment]
Closing as this was implemented for the 2111.1 release
