### ISSUE TITLE
[Download page] Add tabs design to support Win & Linux download

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de.org#1134]
## Describe the feature you'd like available on the website

In order to support the download of Windows and Linux builds, we propose to add the tabs design for both Windows and Linux Download. When switching between the tabs, users should see the related information, including the download methods, min system requirements, and Getting Started docs for each of the platforms.

**Comment by AMZN-daimini** [comment]
This was delivered successfully, closing.
