### ISSUE TITLE
[Download page] Update the content for Linux download

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de.org#1135]
## Describe the feature you'd like available on the website

The linux download page should include the following info:
1. fork from github info and call to action button
2. min system requirements
3. getting started content for linux installer and setup

## Proposed implementation

Design reference: https://www.figma.com/file/Yz1BfrSk0mRhLk5Bjpng3Q/Website-Design-for-GA?node-id=1023%3A5796

**Comment by FiniteStateGit** [comment]
Closing this as resolved with the 2111 release.
