### ISSUE TITLE
[DOCS] Registering a project to an engine

### ISSUE THREAD

**Issue by chanmosq** [o3de/o3de.org#1142]
## Describe the issue briefly

We need documentation on registering a project to an engine. This belongs in the [Project Configuration](https://o3de.org/docs/user-guide/project-config/) section. This is not covered in [Creating Projects using CLI](https://o3de.org/docs/welcome-guide/create/creating-projects-using-cli/) because projects are automatically registered when you create them. But suppose you set up a different engine, or you are working with a distributed project, then you will need to set it up manually. 

The command to do that is in the [**CLI Reference** page](https://o3de.org/docs/user-guide/project-config/cli-reference/#register), but this is a reference page. Registering a project to an engine is a common task that should be highlighted in **Project Configuration**.

## Which page(s) / section(s) are affected?

https://o3de.org/docs/user-guide/project-config/

## Does this work have an engineering dependency? What is it?

No.

**Comment by sptramer** [comment]
Already in reference - should highlight in project configuration page (projects have legitimate reasons to switch engines, such as testing a newer release.)

**Comment by lmbr-pip** [comment]
@sptramer Believe this has been fixed, see https://www.o3de.org/docs/user-guide/project-config/cli-reference/#register (although registering project to engine appears broken - https://github.com/o3de/o3de/issues/9509)

**Comment by micronAMZN** [comment]
Closing as complete.
