### ISSUE TITLE
[ISSUE][DOCS] Update user-guide landing page to link to log-file.md

### ISSUE THREAD

**Issue by FiniteStateGit** [o3de/o3de.org#1143]
## Describe the issue

log-file.md is not listed with the other Appendix directory pages on the user-guide landing page:
https://o3de.org/docs/user-guide/#reference-documentation

## Impacted page(s)

https://o3de.org/docs/user-guide/appendix/log-files/
https://o3de.org/docs/user-guide/

## Expected experience

There is a Log file link in the Reference Documentation section of the user-guide.

**Comment by sptramer** [comment]
Recommend taking this opportunity to create a index page for as many log files as we can find.
