### ISSUE TITLE
[Obsolete Information]: Create content patches with O3DE/Add a gem and modify the level

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#116]
Link to page:
https://o3deorg.netlify.app/docs/learning-guide/tutorials/packaging/tutorial-content-patches/

"For this tutorial you’ll modify the level2 level created in the previous tutorial. You’ll also be adding a new asset-only gem to the Starter Game project, to demonstrate how to update auxiliary content in addition to pushing direct changes to a bundle".

1." Launch the Project Configurator, make sure that the Starter Game is selected, and select Enable Gems".

There is no Project Configurator tool in current build:
main-spectra-windows-all-12.

**Comment by FiniteStateGit** [comment]
Page no longer exists, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
