### ISSUE TITLE
[ISSUE][DOCS] Update tutorial: Get Started with Material Types and Shaders

### ISSUE THREAD

**Issue by chanmosq** [o3de/o3de.org#1164]
## Describe the issue

This page is out-of-date because there were updates to the `.materialtype` file.

Here is an image of the error: 
![Image of error](https://user-images.githubusercontent.com/75444793/141349926-52b9c23e-1ea0-40f3-9f0b-84fc12506c4a.png)

## Impacted page(s)

Website: https://o3de.org/docs/atom-guide/look-dev/get-started-materialtypes-and-shaders/#4-author-material-type-data-materialtype

o3de.org repo: `/docs/atom-guide/look-dev/get-started-materialtypes-and-shaders.md#4-author-material-type-data-materialtype`

## Expected experience

Review the source files in the engine source directory: `Gems\Atom\RPI\Code\Source\RPI.Edit\Material\MaterialTypeSourceData.cpp`

Also review examples of `.materialtype` files. For example: `Gems\Atom\Feature\Common\Assets\Materials\Types\StandardPBR.materialtype`

**Comment by micronAMZN** [comment]
Fixed: New page here: https://www.o3de.org/docs/learning-guide/tutorials/rendering/get-started-materialtypes-and-shaders/
