### ISSUE TITLE
[SITE][FEATURE] add the community content section on the landing page

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de.org#1188]
## Describe the feature you'd like available on the website

Add a community contribution section on the landing page to showcase the contents that the community created using O3DE.

## Proposed implementation

Design reference: https://www.figma.com/file/TRBWk7CMYfJlor0uo5s1cs/Website-Design-for-GA?node-id=1097%3A4888

In the initial release, we will include two contents first- one from Apocalypse, one from xxx. 

(Interaction TBD)

## Available alternatives

It's a stretch goal is we can include content from Cesium or other community members.

**Comment by bhanuja-s** [comment]
I can't seem to edit this issue, but the (short-term) interaction has been specified in the Design file [here](https://www.figma.com/file/TRBWk7CMYfJlor0uo5s1cs/Website-Design-for-GA?node-id=1142%3A4997).

**Comment by amzn-leenguy** [comment]
This has been handled by @AMZN-daimini recently. So I assume we should assign it to him until it is signed off.

**Comment by amzn-leenguy** [comment]
You can see a prototype of it here https://deploy-preview-1231--o3deorg.netlify.app/

**Comment by AMZN-daimini** [comment]
Proper staging link is: https://deploy-preview-1214--o3deorg.netlify.app/
(1231 is the staging for Doug's branch which doesn't have latest)

**Comment by AMZN-daimini** [comment]
Marketing determined we preferred to hold that section of the website until we have more content we can display there. Closing this issue, we can create a new one when we have a plan.
