### ISSUE TITLE
[SITE][FEATURE] Add a dedicated search results page.

### ISSUE THREAD

**Issue by FiniteStateGit** [o3de/o3de.org#1194]
## Describe the feature you'd like available on the website

Add a dedicated search results page that is navigated to after a search request.

## Available alternatives

Currently, search results replace the current page's content.  You are unable to navigate back to search results.

**Comment by amzn-leenguy** [comment]
Thanks for reporting this bug @FiniteStateGit . We noticed it during our UXR sessions for WF8 as well. This seems like it would be a hugo cms search improvement too.

**Comment by FiniteStateGit** [comment]
This has been resolved, a dedicated search page was added; users are able to navigate back to a search.
