### ISSUE TITLE
[SITE][FEATURE] Signposting (navigational aid) aka Highlight Tip

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de.org#1196]
## Describe the feature you'd like available on the website

1. As a navigational aid (aka call out highlight tip), signposts provide information to users which allow them to make their own decisions. This should not add a layer of complexity, but instead simplify it for the users.
    1. Include internal links at the beginning of an article, to suggest alternative articles that they might be looking for
    2. Include links at the end, to encourage users to continue learning

## Proposed implementation

I would like to see like a call out highlight in a green box or something to highlight if a user is looking for a different or related page, click here to take them there.

It also can be used as a TIP (!) function, to call out a tip during an article / page at the top of throughout the content.

## Available alternatives

As a short term solution, this could be done as just plain text inside a row that is coloured. But that would be an extremely scrappy and poor experience. But it would at least help misguided users get to where they need to go.

## Supplements

Microsoft has a good example here:
https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/main-command-line

TIP EXAMPLE

![Screen Shot 2021-11-18 at 2 36 05 PM](https://user-images.githubusercontent.com/82846749/142507806-e008905b-b59a-4f0c-9b1e-0d347e7a3b96.png)

RELATED ARTICLES AT END OF PAGE EXAMPLE

![Screen Shot 2021-11-18 at 2 35 43 PM](https://user-images.githubusercontent.com/82846749/142507810-2c8f7122-6309-40e1-a08d-3dc530f636b8.png)

**Comment by chanmosq** [comment]
Based on UX Research:
  1. Here are some suggestions. can be done via signposting or sentence related links (short term):
        1. Add signposting to WF8 tutorial landing page (Custom Tools) on *User Guide* landing page
        2. Add signposting to WF8 tutorial landing page (Custom Tools) on the *Developing a Gem* landing page
        3. Add signposting to WF8 tutorial landing page (Custom Tools) on the *Tools UI* landing page

**Comment by chanmosq** [comment]
This issue is to create the shortcode that makes the "highlight" callout box. 

It's related to this issue about applying the shortcode to certain pages: https://github.com/o3de/o3de.org/issues/1198

**Comment by chanmosq** [comment]
We have signposts or "callout boxes" as shown here: http://o3de.org/docs/contributing/to-docs/style-guide/shortcodes/. 

I think the TIP signpost requested by this issue is covered by the existing **Note** callout box. 

**Problems with adding callout boxes to the top of a page**
When you use the search bar, the search results show a list of pages and the first few lines of the page. The problem with having callout boxes at the top of the page is that the text of the callout box are the lines that appear in the search results, which is not informative to users' search results. 

The 2nd solution proposed (related topics at the end of the page) is a better solution.

**Comment by amzn-leenguy** [comment]
> We have signposts or "callout boxes" as shown here: http://o3de.org/docs/contributing/to-docs/style-guide/shortcodes/.
> 
> I think the TIP signpost requested by this issue is covered by the existing **Note** callout box.
> 
> **Problems with adding callout boxes to the top of a page** When you use the search bar, the search results show a list of pages and the first few lines of the page. The problem with having callout boxes at the top of the page is that the text of the callout box are the lines that appear in the search results, which is not informative to users' search results.
> 
> The 2nd solution proposed (related topics at the end of the page) is a better solution.

Thanks for the update @chanmosq . I think for now, until we can get some support on upgrading the functionality of Hugo to ignore shortcodes from the search results / meta descriptions of the page, then we need to just do a work around here.

So moving forward, let's just make sure that shortcodes are not in the intro description area so we don't conflict with the search results text. And we also have related links "pattern" just recently added, so thats something else that can also help our user guidance.

Thanks
