### ISSUE TITLE
[DOCS] Rename “Custom Tools” to something more familiar with our readers

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de.org#1199]
## Describe the issue briefly

Rename “Custom Tools” to something more familiar with our readers. During our UXR sessions with external customers that have experience extending the editor, they got confused what Custom Tools meant. 

    1. Suggestions given were:
        1.  “Extend the Editor” over Creating a tool
        2. “Editor”, “Gems”, “Plugins”, over “Custom Tools” or “Custom Shape Tool”

## Which page(s) / section(s) are affected?

https://deploy-preview-1119--o3deorg.netlify.app/docs/learning-guide/tutorials/

https://deploy-preview-1119--o3deorg.netlify.app/docs/learning-guide/tutorials/custom-tools/

## Does this work have an engineering dependency? What is it?

No it does not

**Comment by amzn-leenguy** [comment]
@chanmosq

**Comment by chanmosq** [comment]
This update is made in this commit: https://github.com/o3de/o3de.org/pull/1119/commits/d918c387c813f1ae29fc299a69f253b3c5a4c716. 

It will be resolved with the linked PR.
