### ISSUE TITLE
[Formatting]: O3DE User guide: Multiple pages layouts are breaking on resizing their width

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#120]
Links:
https://o3deorg.netlify.app/docs/user-guide/
https://o3deorg.netlify.app/docs/user-guide/project-config/
https://o3deorg.netlify.app/docs/user-guide/project-config/tool/
https://o3deorg.netlify.app/docs/user-guide/build/
https://o3deorg.netlify.app/docs/user-guide/editor/
https://o3deorg.netlify.app/docs/user-guide/editor/viewport/
https://o3deorg.netlify.app/docs/user-guide/gems/
https://o3deorg.netlify.app/docs/user-guide/gems/reference/
https://o3deorg.netlify.app/docs/user-guide/gems/reference/chatplay/
https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/
https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/
https://o3deorg.netlify.app/docs/user-guide/gems/development/
https://o3deorg.netlify.app/docs/user-guide/gems/development/creating/
https://o3deorg.netlify.app/docs/user-guide/components/
https://o3deorg.netlify.app/docs/user-guide/components/reference/
https://o3deorg.netlify.app/docs/user-guide/components/reference/atom/
https://o3deorg.netlify.app/docs/user-guide/components/development/
https://o3deorg.netlify.app/docs/user-guide/engine/
https://o3deorg.netlify.app/docs/user-guide/engine/intro/
https://o3deorg.netlify.app/docs/user-guide/engine/memory/
https://o3deorg.netlify.app/docs/user-guide/engine/system-libraries/
https://o3deorg.netlify.app/docs/user-guide/engine/debugging/
https://o3deorg.netlify.app/docs/user-guide/engine/serialization/
https://o3deorg.netlify.app/docs/user-guide/assets/
https://o3deorg.netlify.app/docs/user-guide/assets/pipeline/
https://o3deorg.netlify.app/docs/user-guide/assets/fbx-settings/
https://o3deorg.netlify.app/docs/user-guide/assets/fbx-settings/import/
https://o3deorg.netlify.app/docs/user-guide/assets/builder/
https://o3deorg.netlify.app/docs/user-guide/interactivity/
https://o3deorg.netlify.app/docs/user-guide/interactivity/entities/
https://o3deorg.netlify.app/docs/user-guide/interactivity/navigation-and-pathfinding/
https://o3deorg.netlify.app/docs/user-guide/interactivity/physics/
https://o3deorg.netlify.app/docs/user-guide/interactivity/physics/nvidia-physx/
https://o3deorg.netlify.app/docs/user-guide/interactivity/physics/nvidia-physx/configuring/
https://o3deorg.netlify.app/docs/user-guide/interactivity/physics/nvidia-blast/
https://o3deorg.netlify.app/docs/user-guide/interactivity/physics/nvidia-cloth/
https://o3deorg.netlify.app/docs/user-guide/interactivity/prefabs/
https://o3deorg.netlify.app/docs/user-guide/interactivity/audio/
https://o3deorg.netlify.app/docs/user-guide/interactivity/audio/translation-layer/
https://o3deorg.netlify.app/docs/user-guide/interactivity/user-interface/
https://o3deorg.netlify.app/docs/user-guide/interactivity/user-interface/editor/
https://o3deorg.netlify.app/docs/user-guide/interactivity/user-interface/editor/components/
https://o3deorg.netlify.app/docs/user-guide/interactivity/user-interface/animating/
https://o3deorg.netlify.app/docs/user-guide/interactivity/user-interface/animating/tweener-system/
https://o3deorg.netlify.app/docs/user-guide/interactivity/user-interface/animating/animation-editor/
https://o3deorg.netlify.app/docs/user-guide/interactivity/user-interface/fonts/
https://o3deorg.netlify.app/docs/user-guide/scripting/
https://o3deorg.netlify.app/docs/user-guide/scripting/lua/
https://o3deorg.netlify.app/docs/user-guide/scripting/script-canvas/
https://o3deorg.netlify.app/docs/user-guide/scripting/script-canvas/development/
https://o3deorg.netlify.app/docs/user-guide/scripting/script-events/
https://o3deorg.netlify.app/docs/user-guide/visualization/
https://o3deorg.netlify.app/docs/user-guide/visualization/animation/
https://o3deorg.netlify.app/docs/user-guide/visualization/animation/animation-editor/
https://o3deorg.netlify.app/docs/user-guide/visualization/animation/character-editor/
https://o3deorg.netlify.app/docs/user-guide/visualization/cameras/
https://o3deorg.netlify.app/docs/user-guide/visualization/environments/
https://o3deorg.netlify.app/docs/user-guide/visualization/rendering/
https://o3deorg.netlify.app/docs/user-guide/visualization/rendering/shaders/
https://o3deorg.netlify.app/docs/user-guide/visualization/cinematics/
https://o3deorg.netlify.app/docs/user-guide/visualization/cinematics/track-view/
https://o3deorg.netlify.app/docs/user-guide/networking/
https://o3deorg.netlify.app/docs/user-guide/cloud/
https://o3deorg.netlify.app/docs/user-guide/cloud/aws/
https://o3deorg.netlify.app/docs/user-guide/cloud/aws/core/
https://o3deorg.netlify.app/docs/user-guide/testing/
https://o3deorg.netlify.app/docs/user-guide/testing/profiler/
https://o3deorg.netlify.app/docs/user-guide/localization/
https://o3deorg.netlify.app/docs/user-guide/platforms/android/
https://o3deorg.netlify.app/docs/user-guide/platforms/ios/
https://o3deorg.netlify.app/docs/user-guide/platforms/linux/
https://o3deorg.netlify.app/docs/user-guide/platforms/macos/
https://o3deorg.netlify.app/docs/user-guide/packaging/
https://o3deorg.netlify.app/docs/user-guide/packaging/asset-bundler/
https://o3deorg.netlify.app/docs/user-guide/packaging/asset-bundler/verifying-bundles/
https://o3deorg.netlify.app/docs/user-guide/appendix/
https://o3deorg.netlify.app/docs/user-guide/appendix/cvars/

Listed pages break the left menu's layout when their window is resized below around 60% of their original width on 1920x1080 resolution and completely vanish when their window is resized below around 30% of its original width on 1920x1080 resolution. This may be a substantial issue on mobile devices such as tablets or phones.

**Comment by FiniteStateGit** [comment]
Table of contents navigation collapses and moves to the hamburger menu on resize.  Tested mobile with same results.  @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described. Some links no longer redirect to existing pages, which is not a part of the issue.
