### ISSUE TITLE
[BUG][WEBSITE] Update Meta titles for the pages to be the heading. 

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de.org#1202]
## Describe the bug

Update Meta titles for the pages to be the heading. Currently they all say Open 3D Engine. No Context for page.

## Reproduction steps

1. Open a page on O3DE.org/docs. 
2. Go a few levels deep on any content.
3. Notice all the tabs read Open 3D Engine only

## Expected behavior

That the tab would be titled: O3DE - <Title of the page> 

## Screenshots

![Screen Shot 2021-11-18 at 3 00 28 PM](https://user-images.githubusercontent.com/82846749/142510349-d8fb543c-a0fa-4e9f-972d-79ce711c86a8.png)

**Comment by chanmosq** [comment]
This is a hugo technical fix.

To clarify, its the name of the tabs of the browser.

**Comment by FiniteStateGit** [comment]
![tab_titles](https://user-images.githubusercontent.com/31811688/155211081-98e24bcc-40f3-4580-9cfd-8993b657e01d.png)

The design has been updated to `page.title - site.title`.  I would recommend we use the more succinct `page.linkTitle - site.title` or `page.linkTitle - O3DE`.

**Comment by amzn-leenguy** [comment]
> ![tab_titles](https://user-images.githubusercontent.com/31811688/155211081-98e24bcc-40f3-4580-9cfd-8993b657e01d.png)
> 
> The design has been updated to `page.title - site.title`. I would recommend we use the more succinct `page.linkTitle - site.title` or `page.linkTitle - O3DE`.

Great work @FiniteStateGit . Your contributions are great and consistent :)

**Comment by micronAMZN** [comment]
Close as compete?

**Comment by chanmosq** [comment]
This has been resolved
