### ISSUE TITLE
[BUG][WEBSITE] Clicking on the Right hand side Anchors doesn't scroll down correctly for good experience

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de.org#1204]
## Describe the bug

Clicking on the right hand side (RHS) anchor links should also scroll down page, but also add padding so the title isn’t stuck under the nav bar.

We need to add some offsetting padding so it scrolls down and doesn't have the floating nav at the top of the page cover the text. 

## Reproduction steps

1. Open a page like this: https://deploy-preview-1119--o3deorg.netlify.app/docs/learning-guide/tutorials/custom-tools/shape-example-cpp/
2. Click an anchor link on the right hand side e.g. qt behaviour 

## Expected behavior

It scrolls down enough that the heading is not covered by the nav.

This seems to happen more to the smaller titles, not the larger titles. 

## Other information

NA

**Comment by FiniteStateGit** [comment]
This was resolved with #1176.
