### ISSUE TITLE
[ISSUE][DOCS] Replace the second Section Title with “Overview”

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de.org#1209]
## Describe the issue

In the left hand side nav (LHS nav or aka Table of Contents), we should replace the second Section Title with “Overview”, this would be the /landing page/for all the documentation pages.

E.g: https://o3de.org/docs/learning-guide/

This way the double section title will less confuse our users.

A very strong and solid example of this is: https://stripe.com/docs/payments

## Impacted page(s)

All pages that have a generic landing page that repeats the same items that are on the Table of Contents on the left.

E.g: 
https://o3de.org/docs/learning-guide/
https://o3de.org/docs/learning-guide/tutorials/
https://o3de.org/docs/tools-ui/

## Expected experience

Once we rename it to Overview, users that click on it will expect it more as an overview of pages

**Comment by chanmosq** [comment]
This requires technical knowledge of Hugo and website infrastructure.

**Comment by chanmosq** [comment]
To clarify, the expected behaviour is (for example, the Build section)
- In the left hand nav, the section title should stay as "Build".
- But the page below should be changed to "Overview".
- And in the page, the title should remain as "Build".

**Comment by chanmosq** [comment]
We would like this applied across all the docs.

**Comment by micronAMZN** [comment]
Site IA has changed making this a non-issue.
