### ISSUE TITLE
[Formatting]: O3DE User guide: On multiple pages left navigation menu is being compacted into vanishing when resizing the page's width

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#121]
Links:
https://o3deorg.netlify.app/docs/user-guide/gems/reference/gamelift/
https://o3deorg.netlify.app/docs/user-guide/components/reference/shape/
https://o3deorg.netlify.app/docs/user-guide/engine/codegen/
https://o3deorg.netlify.app/docs/user-guide/engine/ebus/
https://o3deorg.netlify.app/docs/user-guide/interactivity/input/

When the page is being resized below around 80% of its original width, the left navigation menu formatting starts to break and it gets compacted to single letter lines, until it vanishes from the page.

**Comment by FiniteStateGit** [comment]
Table of contents navigation collapses and moves to the hamburger menu on resize.  Tested mobile with same results.  @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described. Some links no longer redirect to existing pages, which is not a part of the issue.
