### ISSUE TITLE
[SITE][FEATURE]  Restyle the Section Title in the Table of Contents (LHS Nav)

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de.org#1211]
## Describe the feature you'd like available on the website

Restyle the Section Title so it looks less like a page to load. Since it doesn’t open a page. It just opens a category in the LHS Nav. Although the arrow at the moment helps guides our users that its not a page, if we just restyle the aesthetics of the section title in this section it will differentiate it from the actual clickable pages that loads content.

## Proposed implementation

We could just move the arrow on the left hand side like the reference below.

## Available alternatives

Or we could add a different font colour to the section titles?

## Supplements

MICROSOFT DOCS EXAMPLE

![Screen Shot 2021-11-18 at 3 36 34 PM](https://user-images.githubusercontent.com/82846749/142513711-6b2bdfd3-754f-4767-bb66-a1486a47ee4a.png)

**Comment by chanmosq** [comment]
Another note, consider putting the `>` on the left hand side to make it feel more like a file structure. Often, the `>` on the right hand side is associated with accordion style UI elements.

**Comment by chanmosq** [comment]
Closing because the behavior and appearance of the left navigation will change due to PR https://github.com/o3de/o3de.org/pull/1859. 

With these changes, the section title now directs to the _index.md page for that section.
