### ISSUE TITLE
[ISSUE][DOCS] Matching the Table of Content section topics to the Topics on the page

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de.org#1212]
## Describe the issue

In the screenshot example below, we should make sure that the topics on the left hand side in the Tables of Contents matches the topic names in the content itself as well. It also should be ordered exactly the same as well, so there's no user confusion.

## Impacted page(s)

https://o3de.org/docs/user-guide/gems/

![Screen-Shot-2021-11-18-at-3 39 46-PM](https://user-images.githubusercontent.com/82846749/142514210-86f88f5a-c56a-4aa6-a50f-ddd8ce5fb2a9.jpg)

## Expected experience

That topics match the contents of the page.

**Comment by chanmosq** [comment]
This issue has been resolved in another PR, where "Developing Gems" was moved to the Programming section.
