### ISSUE TITLE
[Formatting]: O3DE User guide: Chapters within the navigation menu on the left should be collapsible

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#122]
Link: https://o3deorg.netlify.app/docs/user-guide/

Distinct chapters (e.g. Editor, Gems, Components) should be a collapsible menu, as due to a large amount of content within the O3DE User guide it's not easily navigable. This is not a problem at the moment with the other sections, but could become one in the future as more content is being added into them.

**Comment by FiniteStateGit** [comment]
Menu is now collapsible and collapsed by default, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
The menus are now collapsible, closing the issue.
