### ISSUE TITLE
[BUG][WEBSITE] Switching between section tabs scrolls to the very top of the page

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de.org#1235]
## Describe the bug

Switching between the tabs in a menu which can be found for example in the following pages: 
- [cli-reference](https://o3de.org/docs/user-guide/project-config/cli-reference/), 
- [build](https://o3de.org/docs/user-guide/build/), 
- [configure and build](https://o3de.org/docs/user-guide/build/configure-and-build/), 
- [building linux](https://o3de.org/docs/welcome-guide/setup/setup-from-github/building-linux/), 
- [building windows](https://o3de.org/docs/welcome-guide/setup/setup-from-github/building-windows/)

scrolls to the very top of the page. This requires the User to scroll back down to the section they were reading before which is a bad experience.

Please refer to the attached video for more details.

## Reproduction steps

    Steps to reproduce the behavior, as a numbered list:

    1. Open [building windows guide](https://o3de.org/docs/welcome-guide/setup/setup-from-github/building-windows/).
    2. Scroll down to the _Register the engine_ section.
    3. Switch to the _Pre-built SDK engine_ tab.

## Expected behavior

The page does not scroll to the very top of it.

## Screenshots

https://user-images.githubusercontent.com/86953108/142998939-694d1754-4078-4ffd-9943-edf80b68de37.mp4

## Other information

* **OS**: Windows, Linux
* **Browser**: Chrome, Opera, Edge

**Comment by AMZN-daimini** [comment]
As pointed out by @FiniteStateGit , this https://github.com/o3de/o3de.org/pull/1184 fixes the issue. It needs one more approval to go in.

**Comment by chanmosq** [comment]
Closing. Resolved by https://github.com/o3de/o3de.org/pull/1184.

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as fixed.
