### ISSUE TITLE
[BUG][WEBSITE] Community Spotlight Lightbox continues to play the video after the model is closed down

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de.org#1245]
## Describe the bug

When a user clicks on the CTA button for the community spotlight section for Apoc Studios (Preview link https://deploy-preview-1231--o3deorg.netlify.app/) it opens. 

If a user plays the video and then clicks on the X or also clicks outside of the lightbox to close the light box, it continues to play and you can hear the sound. 

## Reproduction steps

1. Goto https://deploy-preview-1231--o3deorg.netlify.app/
2. Scroll down to the community spotlight section
3. Click on the thumbnail for apoc's game: deadhaus sonota
3. light box opens
4. play video
5. close light box model with X or clicking outside of the lightbox area

## Expected behavior

1. video stops playing and the noise stops after I close the window.

## Screenshots

NA

**Comment by FiniteStateGit** [comment]
This was resolved with 2111 website redesign.
