### ISSUE TITLE
[DOCS] Tools UI Developer's Guide Page Update to add BlueJay Design System content

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de.org#1266]
## Describe the issue briefly

An update to the Tools UI Developer's Guide page to add some new content explaining the purpose and resources that come along with the BlueJay Design System. Such content like description of what the BlueJay Design System is, link to the roadmap and a link to the style guide and logo assets for the community to download. 

## Which page(s) / section(s) are affected?

https://o3de.org/docs/tools-ui/

## Does this work have an engineering dependency? What is it?

Yes. I would like an engineer to add the functionality of adding PDF embedding to view PDF's directly on the webpage. This is optional and not a requirement. 

And a person from Docs to help add new text and some images.

**Comment by amzn-leenguy** [comment]
We have an early concept of the page here pending some review: https://www.figma.com/file/fKoPKTu8MpNo4a9xKqg2OT/BJDS-Docs-Landing-Page?node-id=0%3A1

**Comment by chanmosq** [comment]
Closing. Resolved by linked PR.

**Comment by amzn-leenguy** [comment]
Sure thing. thanks @chanmosq !
