### ISSUE TITLE
[DOCS] Add a column for product asset file types to the Asset Types table

### ISSUE THREAD

**Issue by willihay** [o3de/o3de.org#1270]
## Describe the issue briefly

The Asset Types page lists only **source asset file types**. It would be cool and useful if the corresponding **product asset file types** that are generated by the asset pipeline were listed in another column of the table on this page.

## Which page(s) / section(s) are affected?

https://o3de.org/docs/user-guide/assets/pipeline/asset-types/

## Does this work have an engineering dependency? What is it?

n/a

**Comment by micronAMZN** [comment]
https://github.com/o3de/o3de.org/pull/1288
