### ISSUE TITLE
[ISSUE][DOCS] The Create a Custom Tool Gem in Python to Extend Open 3D Engine Editor tutorial does not contain import information

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de.org#1275]
## Describe the issue

The [Create a Custom Tool Gem in Python to Extend Open 3D Engine Editor](https://o3de.org/docs/learning-guide/tutorials/extend-the-editor/shape-example-py/) tutorial is missing the information on modules required to import.

## Impacted page(s)

[Create a Custom Tool Gem in Python to Extend Open 3D Engine Editor](https://o3de.org/docs/learning-guide/tutorials/extend-the-editor/shape-example-py/)

## Expected experience

The tutorial contains a section with all the modules which are required to be imported. It also contains the code responsible for importing them. I.e. 
The following modules must be imported for the tool to work correctly:
```
import azlmbr.bus as bus
import azlmbr.components as components
import azlmbr.editor as editor
import azlmbr.entity as entity
import azlmbr.math as math

from PySide2.QtCore import Qt
from PySide2.QtGui import QDoubleValidator
from PySide2.QtWidgets import QCheckBox, QComboBox, QDialog, QFormLayout, QGridLayout, QGroupBox, QLabel,  QPushButton, QVBoxLayout, QWidget
```

**Comment by chanmosq** [comment]
@LB-TomaszSerwanski Thanks for nothing this issue. I've created a PR to address it. Feel free to review it and comment or approve.

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as Fixed.
