### ISSUE TITLE
[ISSUE][DOCS] The Create a Custom Tool Gem in Python to Extend Open 3D Engine Editor tutorial mentions C++ instead of Python

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de.org#1276]
## Describe the issue

The [Create a Custom Tool Gem in Python to Extend Open 3D Engine Editor](https://o3de.org/docs/learning-guide/tutorials/extend-the-editor/shape-example-py/) contains the following sentence:
`By the end of this tutorial, you’ll be able to extend the Editor by creating your own custom tools written in C++.`

![image](https://user-images.githubusercontent.com/86953108/144845599-f1c83a53-2b68-465f-8449-1b67d95c90bf.png)

## Impacted page(s)

[Create a Custom Tool Gem in Python to Extend Open 3D Engine Editor](https://o3de.org/docs/learning-guide/tutorials/extend-the-editor/shape-example-py/)

## Expected experience
The sentence is: 
`By the end of this tutorial, you’ll be able to extend the Editor by creating your own custom tools written in Python.`

**Comment by chanmosq** [comment]
@LB-TomaszSerwanski Thanks for nothing this issue. I've created a PR to address it: "Custom tool gem". Feel free to review it and comment or approve.

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as Fixed.
