### ISSUE TITLE
[ISSUE][DOCS] The Create a Custom Tool Gem in C++ to Extend Open 3D Engine Editor tutorial does not contain include information

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de.org#1277]
## Describe the issue

The [Create a Custom Tool Gem in C++ to Extend Open 3D Engine Editor](https://o3de.org/docs/learning-guide/tutorials/extend-the-editor/shape-example-cpp/) tutorial is missing the information on libraries required to include in the file.

## Impacted page(s)

[Create a Custom Tool Gem in C++ to Extend Open 3D Engine Editor](https://o3de.org/docs/learning-guide/tutorials/extend-the-editor/shape-example-cpp/)

## Expected experience

The tutorial contains a section with all the libraries which are required to be included. It also contains the code responsible for including them. I.e.
The following modules must be imported for the tool to work correctly:
```
#include <AzCore/Component/TransformBus.h>
#include <AzCore/Utils/Utils.h>
#include <AzToolsFramework/API/EntityCompositionRequestBus.h>
#include <AzToolsFramework/Component/EditorComponentAPIBus.h>
#include <AzToolsFramework/Entity/EditorEntityAPIBus.h>
#include <QComboBox>
#include <QDoubleValidator>
#include <QFormLayout>
#include <QGridLayout>
#include <QGroupBox>
#include <QLabel>
#include <QLineEdit>
#include <QPushButton>
#include <QVBoxLayout>
#include <ShapeExampleWidget.h>
```

**Comment by chanmosq** [comment]
@LB-TomaszSerwanski Thanks for nothing this issue. I've created a PR to address it: "Custom tool gem". Feel free to review it and comment or approve.

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as Fixed.
