### ISSUE TITLE
[Dead Links]: O3DE User guide /Testing and optimization /Profiler /Profiler Tutorial 

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#128]
Link to page:
 https://o3deorg.netlify.app/docs/user-guide/testing/profiler/tutorial/

 Using Profiler for Networking:
 Link to page:
 https://o3deorg.netlify.app/docs/user-guide/deadlink

 Using the Profiler for CPU Usage:
 Link to page:
 https://o3deorg.netlify.app/docs/user-guide/tools/profiler/cpu.md

 The following link leads to a 404 page.

**Comment by FiniteStateGit** [comment]
Page no longer exists, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
