### ISSUE TITLE
[ISSUE][DOCS] Misspelling on Using Multiple Skin Attachments for an Actor page

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de.org#1280]
## Describe the issue

"The" is misspelled as "TheA" in the beginning of the second sentence on the "Using Multiple Skin Attachments for an Actor" page.

## Impacted page(s)

https://o3de.org/docs/user-guide/components/reference/animation/actor-multiple-skin/

## Expected experience

No spelling errors are present on the "Using Multiple Skin Attachments for an Actor" page.

**Comment by sptramer** [comment]
Closing as the animation editor documentation will be rewritten soon- this is old docs ported from LY 1.x that will be retired.
