### ISSUE TITLE
[Formatting] Blank bullet points in the menu on left side

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#129]
Link to the page: https://o3deorg.netlify.app/docs/atom-guide/core-systems/

The left side menu section for Programmer Guide includes three blank bullet points.
![image](https://user-images.githubusercontent.com/80751316/111632390-b5650a80-87f4-11eb-92eb-7bbd88f8cbff.png)

**Comment by FiniteStateGit** [comment]
Page no longer exists, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
