### ISSUE TITLE
[BUG][WEBSITE]  Google search results only include API results, no other o3de docs results are shown

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de.org#1292]
## Describe the bug

Google search results do not include any results except those in the API (https://o3de.org/docs/api)

I suspect someone will need to register the site under Google webmaster tools to investigate this issue.

This might also be partly caused by all of our page html titles being the same - i.e. `Open 3D Engine` 

## Reproduction steps

Google does not return any results from O3DE docs except the API docs.

This search works only returns api results
`site:https://o3de.org/docs`

Nothing is returned for welcome guide, release notes, learning-guide, user-guide, atom-guide, etc.

Example Google searches:
`site:https://o3de.org/docs/welcome-guide`
`site:https://o3de.org/docs/release-notes`

This search does not return the actual release notes pages
`o3de release notes`

This search returns no pages in https://o3de.org/docs/welcome-guide
`o3de welcome guide`

This search using the exact meta title for the Atom learn page in docs, does not return the actual page:
`o3de Learn about the Atom …`

## Expected behavior

Google search results provide results from our entire documentation

## Screenshots

n/a

## Other information

* **OS**: Windows 10
* **Browser**: Chrome latest

**Comment by AMZN-alexpete** [comment]
This issue was accidentally closed because it was linked to a PR that just allowed investigating this issue.

**Comment by AMZN-alexpete** [comment]
The following pages are incorrectly marked as duplicates of https://o3de.org/docs/ and are being excluded from the Google index.
[O3DE Excluded-Duplicate-without-user-selected-canonical.csv](https://github.com/o3de/o3de.org/files/7694672/O3DE.Excluded-Duplicate-without-user-selected-canonical.csv)

**Comment by erickson-doug** [comment]
Wow; thanks for this deep dive! Do you have a recommendation, here?

**Comment by AMZN-alexpete** [comment]
I've created 2 PRs to help with this issue of duplicates.
#1 Fix the duplicated page titles https://github.com/o3de/o3de.org/pull/1332
#2 Remove the duplicated search index from every page https://github.com/o3de/o3de.org/pull/1336

The page title change has gone through so we'll see if the new Google index accepts them.

**Comment by AMZN-alexpete** [comment]
Added another PR to try if the other changes don't address the issue.
#3 Remove hidden navigation HTML https://github.com/o3de/o3de.org/pull/1338
