### ISSUE TITLE
Import cleanup issues

### ISSUE THREAD

**Issue by celestehorgan** [o3de/o3de.org#13]
Content itself:

- [x] Search-and-replace  "Lumberyard" -> "O3DE"
- [ ] Remove Amazon copyright notice
- [ ] Code samples: "lumberyard version" 
- [ ] Address link titles in topics: https://deploy-preview-12--o3deorg.netlify.app/docs/userguide/lumberyard-programming-concepts/#lumberyard-programming-concepts
- [x] Periods after links have spaces after them
- [ ] Some headers have square brackets around them: https://deploy-preview-12--o3deorg.netlify.app/docs/userguide/configurator/projects/#-command-line- 
- [ ] https://deploy-preview-12--o3deorg.netlify.app/docs/userguide/gems/builtin/chatplay/#gem-twitch-chatplay-setup comb through for callouts
- [ ] Search for any stray italicizing: https://deploy-preview-12--o3deorg.netlify.app/docs/userguide/components/entity-system-pg-gems-code/#component-entity-system-pg-gems-code-updating-adding-system-components
- [ ] 

Conrefs: 
- [x] "&AKY;" -> "O3DE"
- [x] &ALYlong; -> ?
- [x] &ly-launcher; -> ? 
- [x] &gem; -> Gem

Website:

- [ ] Change language in footer CNCF -> ?
- [ ] Add image lightbox to help with text legibility in large images
- [ ] https://deploy-preview-12--o3deorg.netlify.app/docs/userguide/lmbr-exe/#lmbr-exe - manage HRs (empty headers? investigate) 
- [ ] Add a link checker (either at build or to the site itself) to ease link/header changes.

Etc:

- [ ] Replace the lumberyard icon https://deploy-preview-12--o3deorg.netlify.app/docs/userguide/editor/intro/#lumberyard-editor-intro 
- [ ]

**Comment by micronAMZN** [comment]
Cleaning up stale issues.
