### ISSUE TITLE
[Formatting] Inconsistent ordering between the chapter list and the page

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#130]
Link to page: https://o3deorg.netlify.app/docs/atom-guide/tutorials/

Sections listed on the page are in different order then on the chapter list on the left. 
![image](https://user-images.githubusercontent.com/80751316/111633175-80a58300-87f5-11eb-9920-03895d944668.png)

**Comment by FiniteStateGit** [comment]
Page no longer exists, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
