### ISSUE TITLE
[ISSUE][DOCS] Using AzTest page contains two broken links

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de.org#1306]
## Describe the issue

The [O3DE Test Onboarding](https://o3de.org/docs/user-guide/testing/aztest/aztest/TODO) link in the [Using AzTest](https://o3de.org/docs/user-guide/testing/aztest/aztest/) page is broken.
Please note that there are two occurrences of the broken link on the page, first in the _CTest_ section: 

![image](https://user-images.githubusercontent.com/86953108/146182892-ed08839f-b808-49e4-8d69-992554ab4ab4.png)

and second in the _Links_ section at the bottom of the page:

![image](https://user-images.githubusercontent.com/86953108/146182968-82bbf71c-15d9-4193-9e47-f242162a2f55.png)

## Impacted page(s)

[Using AzTest](https://o3de.org/docs/user-guide/testing/aztest/aztest/)

## Expected experience

The link leads to a correct page.

**Comment by sptramer** [comment]
Related to missing content on the site which is being submitted as part of #1298.

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as Fixed.
