### ISSUE TITLE
[Dead Links]: O3DE Learning guide /Samples /EBus /Usage and Examples

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#131]
Link to page:
  https://o3deorg.netlify.app/docs/learning-guide/samples/ebus/examples

  Components and EBuses:
  Best Practices:
  Link to page:
  https://o3deorg.netlify.app/docs/user-guide/engine/ebus/entity-system-pg-components-ebuses-best-practices.md

  Single handler:
  Link to page:
  https://o3deorg.netlify.app/docs/user-guide/deadlink#ebus-in-depth-configuration-single

  Many handlers:
  Link to page:
  https://o3deorg.netlify.app/docs/user-guide/deadlink#ebus-in-depth-configuration-many

  EBus with addresses and a single handler:
  Link to page:
  https://o3deorg.netlify.app/docs/user-guide/deadlink#ebus-in-depth-configuration-addresses-single-handler

  EBus with addresses and many handlers:
  Link to page:
  https://o3deorg.netlify.app/docs/user-guide/deadlink#ebus-in-depth-configuration-addresses-many-handlers

  The following links leads to a 404 page.

**Comment by FiniteStateGit** [comment]
Page no longer exists, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
