### ISSUE TITLE
[ISSUE][DOCS] Update Script Canvas Text Replacement topic for style

### ISSUE THREAD

**Issue by micronAMZN** [o3de/o3de.org#1310]
## Describe the issue

The Script Canvas text replacement topic is being approved for a deadline, but could use a little bit of organization and style improvement.

## Impacted page(s)

/user-guide/scripting/script-canvas/editor-reference/text-replacement/

**Comment by willihay** [comment]
Refer to review comments in PR that was closed instead of merged: https://github.com/o3de/o3de.org/pull/1251
