### ISSUE TITLE
[Formatting] Inconsistent information between chapter and menu

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#132]
Link to page: https://o3deorg.netlify.app/docs/atom-guide/core-systems/shaders/azsl-reference/

Sections listed on the page are in different order then on the chapter list on the left.
![image](https://user-images.githubusercontent.com/80751316/111634219-96677800-87f6-11eb-8204-db941217af07.png)

**Comment by FiniteStateGit** [comment]
Page no longer exists, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
