### ISSUE TITLE
[SITE][FEATURE] Ability to view and embed PDF directly on the page

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de.org#1331]
## Describe the feature you'd like available on the website

I would like the ability to embed and view PDF's directly on the Docs page. I heard this is possible with a plugin with Hugo CMS.

## Proposed implementation

With an available plugin or script already written by the Hugo community. I have seen that there's already a plugin for it.

## Available alternatives

An alliterative is nothing. Having no embedded PDF is fine, but not ideal. 

## Supplements

I believe this is the plugin here:
https://github.com/anvithks/hugo-embed-pdf-shortcode

**Comment by sptramer** [comment]
Enabling this feature is risky and there is no good obvious reason to do so. This needs to be discussed by the SIG - we would like to know why this feature is being requested, since there are plenty of alternatives, such as "downloading and viewing a PDF locally."
