### ISSUE TITLE
[DOCS] [Testing] Best practices for automated test writing

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de.org#1333]
## Describe the issue briefly

While introductions to test tools exist, there is no guide on what to prefer/avoid when writing test code. Not providing guidance can result in contributors facing unexpectedly lengthy pull request reviews, which have a large amount of feedback on tests.

Where possible avoid duplicating existing documentation: link to existing content on general test writing advice, test terminology, documentation on 3rd party tools, and existing o3de testing documentation. Content should be relating towards test writing specifically for O3DE.

Refer to attachment for prototype documentation content, which should be considered a non-authoritative starting point: [draft_best_practices.md](https://github.com/o3de/o3de.org/files/7804699/draft_best_practices.md)

## Which page(s) / section(s) are affected?

This documentation should be added to the [User Guide for Testing](https://o3de.org/docs/user-guide/testing/). It should also be linked to by the page requested in https://github.com/o3de/o3de.org/issues/1330 (if this issue is delivered first, add a note to the other issue with the document location)

## Does this work have an engineering dependency? What is it?

No

**Comment by evanchia-ly-sdets** [comment]
@Kadino to clarify task and acceptance criteria. We would like a document for new users getting started in testing to answer the question, "What kind of tests should I start writing for my given work?"

**Comment by Kadino** [comment]
Tests of older styles exist in the test collateral, and there can be newer and cleaner ways to write tests. Try to focus on readable examples in the latest utilities. Those examples (in the repo) should document themself, and not rely on the o3de.org site.

**Comment by Kadino** [comment]
Include recommendations of the depth of testing, and dependencies used in tests, and how test "fragility" isn't necessarily unwanted.
