### ISSUE TITLE
[ISSUE][DOCS] Update BJDS error guidance

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#1344]
## Describe the issue

#1313 was merged early by the request of sig-ui-ux. This ticket is to complete the requested revisions of the content.

## Impacted page(s)

Pages under `docs/tools-ui/patterns/error`.

## Expected experience

Please address review comments to complete the revision of content.

**Comment by amzn-leenguy** [comment]
Please assign this to me.

**Comment by micronAMZN** [comment]
Closing, no longer relevant. New guidance forthcoming.
