### ISSUE TITLE
[SITE][FEATURE] Add new Premier Member logo to homepage in Community section

### ISSUE THREAD

**Issue by cmassey11** [o3de/o3de.org#1370]
## Supplements

<img width="1152" alt="Screen Shot 2022-01-24 at 1 23 40 PM" src="https://user-images.githubusercontent.com/92753297/150850164-5837bb35-9bc1-4180-88a8-6b55b1b8fb13.png">

**Comment by AMZN-daimini** [comment]
Picking this up.
Using this svg logo from o3d.foundation
https://o3d.foundation/wp-content/uploads/sites/126/2022/01/microsoft-corporation.svg
