### ISSUE TITLE
Docs for Adding the Multiplayer Gem Doesn't Compile

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de.org#1395]
## Describe the issue
The steps to enable multiplayer gem doesn't work, and results in a compilation error

Following the steps here to add the Multiplayer Gem doesn't work, and results in a compilation error.
https://www.o3de.org/docs/user-guide/gems/reference/multiplayer/multiplayer-gem/configuration/

I'm using the 21.11.2 installer found here:
https://o3debinaries.org/download/windows.html

## Impacted page(s)
https://www.o3de.org/docs/user-guide/gems/reference/multiplayer/multiplayer-gem/configuration/

## Expected experience
Project should compile without errors

**Comment by sptramer** [comment]
@AMZN-Gene - Is this addressed by https://github.com/o3de/o3de.org/pull/1402?

**Comment by AMZN-Gene** [comment]
> 

Yep! Good catch, thank you!
