### ISSUE TITLE
[Obsolete Information] "Programmer Guide" chapter refers to Lumberyard documentation

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#140]
Link to page: https://o3deorg.netlify.app/docs/atom-guide/core-systems/frame-rendering/

In Frame Rendering chapter in Programmer Guide in Atom Renderer, the first image refers to Lumberyard instead of O3DE.
![image](https://user-images.githubusercontent.com/80751316/111640091-24922d00-87fc-11eb-9838-2705ed25899b.png)

**Comment by chanmosq** [comment]
Fixed during initial documentation development.
