### ISSUE TITLE
[ISSUE][DOCS] Debugging with Lua Editor page contains outdated images

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de.org#1400]
## Describe the issue
The Debugging with Lua Editor documentation page contains multiple outdated images. 
There are two outdated images in the "Add sample Lua Script to an entity" section:
![LuaScriptComponentPage](https://user-images.githubusercontent.com/86952082/152169380-c2047e68-a386-42b6-a25f-cf3a3e05d128.PNG)
This is how the Lua Script component looks currently:
![LuaScriptComponentCurrent](https://user-images.githubusercontent.com/86952082/152171880-b4ff5c44-7d3f-4701-b88b-6c319410d69f.png)

There are five outdated images in the "Connect to O3DE Editor with GridHub" section and one in the "Setting breakpoints" section that are showing an older Lua Editor UI:
![ConnectToGridhub](https://user-images.githubusercontent.com/86952082/152171428-5f9522de-f3b8-4e99-b7f1-fc41bc147736.PNG)
![ConnectToGridhub1](https://user-images.githubusercontent.com/86952082/152171457-8d82780b-29d6-4a36-ada7-8d65c1d8c1a3.PNG)
![SettingBreakpoints](https://user-images.githubusercontent.com/86952082/152171484-6180bf3d-ef23-4594-ab36-237021447ec5.PNG)
This is how the Lua Editor UI looks currently:
![LuaEditorCurrent](https://user-images.githubusercontent.com/86952082/152171585-58654f47-a55f-4da0-9408-4442fcc4857a.png)

## Impacted page(s)
https://www.o3de.org/docs/user-guide/scripting/lua/debugging-tutorial/

## Expected experience

Images of the Editor on the documentation page are up to date with how they look like in engine.

**Comment by AMZN-daimini** [comment]
> @o3de/sig-content - Is Lua Editor still actively maintained, or is it considered to be deprecated? Does the SIG have a statement on this? I don't believe it's receiving dev resources and we may want to remove it from the docs site. Huawei seems to be regularly contributing bugfixes?

As far as I understand, the Lua Editor is not in active development. We've been wanting to replace it with a Visual Studio Code / other IDE integration for a while, so that we can deprecate the whole tool and offer a replacement for the API ref functionality, but it's been hard to prioritize the effort.

**Comment by sptramer** [comment]
Recommendation for @o3de/sig-docs - We accept this issue for the current `main` (Lua Editor still ships) and remove it from any upcoming `development` split as proposed by https://github.com/o3de/sig-docs-community/issues/32. Will re-evaluate at next triage.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed.
