### ISSUE TITLE
[Formatting] Inconsistent ordering between the chapter list and the page and missing hyperlink

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#141]
Link to page: https://o3deorg.netlify.app/docs/atom-guide/core-systems/rpi/

Sections listed on the page are in different order then on the chapter list on the left.

![image](https://user-images.githubusercontent.com/80751316/111640939-f3fec300-87fc-11eb-9e1e-65b9eb0372d6.png)

In addition one of the points (Pass System) is not a hyperlink.

**Comment by FiniteStateGit** [comment]
Page no longer exists, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
