### ISSUE TITLE
[BROKEN LINK] Multiple broken links to the Gradient pages on "Gradient Surface Tag Emitter Component" page

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de.org#1417]
## Which page has the broken link?

https://www.o3de.org/docs/user-guide/components/reference/surface-data/gradient-surface-tag-emitter/

## Which link was broken?

Links to the Gradient pages, in "Dependencies" section.

[Altitude Gradient](https://www.o3de.org/docs/user-guide/components/reference/surface-data/gradients/altitude-gradient)
[Constant Gradient](https://www.o3de.org/docs/user-guide/components/reference/surface-data/gradients/constant-gradient)
[FastNoise Gradient](https://www.o3de.org/docs/user-guide/components/reference/surface-data/gradients/fastnoise-gradient)
[Image Gradient](https://www.o3de.org/docs/user-guide/components/reference/surface-data/gradients/image-gradient)
[Perlin Noise Gradient](https://www.o3de.org/docs/user-guide/components/reference/surface-data/gradients/perlin-noise-gradient)
[Random Noise Gradient](https://www.o3de.org/docs/user-guide/components/reference/surface-data/gradients/random-noise-gradient)
[Reference Gradient](https://www.o3de.org/docs/user-guide/components/reference/surface-data/gradients/reference-gradient)
[Shape Falloff Gradient](https://www.o3de.org/docs/user-guide/components/reference/surface-data/gradients/shape-falloff-gradient)
[Slope Gradient](https://www.o3de.org/docs/user-guide/components/reference/surface-data/gradients/slope-gradient)
[Surface Mask Gradient](https://www.o3de.org/docs/user-guide/components/reference/surface-data/gradients/surface-mask-gradient)

## Know where it should go?

Could not find the documentation for any Gradient.

**Comment by FiniteStateGit** [comment]
Confirmed the links are now working with #1351 merged, closing this issue as resolved.

**Comment by LB-JakubSkorupka** [comment]
Issue verified as fixed.
