### ISSUE TITLE
[BROKEN LINK] Tools UI Developer’s Guide contains a link to a 404 page

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de.org#1418]
## Which page has the broken link?

https://www.o3de.org/docs/tools-ui/

## Which link was broken?

https://www.o3de.org/docs/tools-ui/ui-dev-messages ("O3DE’s Message Guidelines" in the Tools UI Developer’s Guide Contents table)

## Know where it should go?

Unsure where the link should redirect to.

**Comment by sptramer** [comment]
https://github.com/o3de/o3de.org/pull/1426
