### ISSUE TITLE
[ISSUE][DOCS] Multiple content issues with Open 3D Branding Guidelines PDF file

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de.org#1419]
## Describe the issue

Open 3D Branding Guidelines PDF file has multiple issues with its contents, and they will be described below along with their Expected experience:

1. Only one out of the four links in PDF is a hyperlink:
A hyperlinked page link: 
www.linuxfoundation.org/trademark-usage - Page 3 - "Credit Requirements"
![WorkingLink](https://user-images.githubusercontent.com/86952082/153600813-de1bdd0c-51de-4b9e-aee6-3697db5d7d61.PNG)
Not hyperlinked page links/reference: 
"Google Fonts", and docs.o3de.org/docs/tools-ui/ - Page 10 - "Typography"
It should be noted that due to not having a hyperlink Google Fonts cannot be accessed without knowing the link (It should most likely redirect to https://fonts.google.com/)
It should also be noted that http://docs.o3de.org/docs/tools-ui/ link can be copied and properly redirects to a page when entered into the browser search bar.
![NoHyperlinks1](https://user-images.githubusercontent.com/86952082/153600829-9ed9927e-5c90-4a17-aa9a-c7a632eecaee.PNG)
docs.o3de.org/docs/tools-ui/ - Page 23 - Last slide
It should be noted that docs.o3de.org/docs/tools-ui/ link can be copied and properly redirects to a page when entered into the browser search bar.
![NoHyperlinks2](https://user-images.githubusercontent.com/86952082/153600833-1c796677-ad2c-493d-835c-74a93ced7a1b.PNG)
**Expected experience**: All of the provided links should be hyperlinks.

2. Some of the images provided are deprecated:
Page 16 - "Application Mock-up"
![Screenshots1](https://user-images.githubusercontent.com/86952082/153603385-32d9a04c-3598-4102-8af7-54cc1442963e.PNG)
Current start-up/About splash screen:
![CurrentAboutScreen](https://user-images.githubusercontent.com/86952082/153604072-08378878-02dd-4bb8-b48f-10523e1202c7.PNG)
Page 17 - "Website Mock-up"
![Screenshots2](https://user-images.githubusercontent.com/86952082/153603387-71842021-5739-4449-a6a0-3735b2291021.PNG)
Current website homepage:
![CurrentWebsite](https://user-images.githubusercontent.com/86952082/153604225-411c00bf-1b55-456b-ab3b-907b66e62655.PNG)
Page 19 - "O3DE Icon Mock-up"
![Screenshots3](https://user-images.githubusercontent.com/86952082/153603392-c648b097-0c8e-4c95-857b-72fe68af8d05.PNG)
Current Project Manager:
![CurrentPM](https://user-images.githubusercontent.com/86952082/153604360-87352cdd-4f44-4601-8415-a189c0ff78d2.PNG)
**Expected experience**: Displayed images should be up to date with how they look in engine.

## Impacted page(s)

https://www.o3de.org/files/Open-3D-Branding-Guidelines-June-2021.pdf (Accessed from the "Download O3DE Branding Guidelines PDF" hyperlink under the "O3DE Branding Guidelines" section on the https://www.o3de.org/docs/tools-ui/branding-guidelines/ page)

**Comment by sptramer** [comment]
@amzn-leenguy - Looks like this needs to be addressed by whoever put these materials together - can you help us figure out who the owner is?

**Comment by amzn-leenguy** [comment]
Updated. Can someone else upload this me on my behalf please? @sptramer 

Thanks

Intentionally did not update the Project Manager Screenshot because there's going to be updates to screen soon.

URLs all good now. Amended last updated date too.

[Open-3D-Branding Guidelines-February-2022.pdf](https://github.com/o3de/o3de.org/files/8094114/Open-3D-Branding.Guidelines-February-2022.pdf)
s

**Comment by sptramer** [comment]
@cmassey11 - Please get Lee's updated PDF onto the Linux Foundation website. Will also ping in Discord.

**Comment by micronAMZN** [comment]
same as https://github.com/o3de/o3de.org/issues/1972

**Comment by LB-ArturZieba** [comment]
Confirming the issue has been closed and will be tracked in the https://github.com/o3de/o3de.org/issues/1972 instead.
