### ISSUE TITLE
[Dead Links]: O3DE User guide /Appendix /Common Tasks, EBuses, and Handlers

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#143]
Link to page;
  https://o3deorg.netlify.app/docs/user-guide/appendix/available-ebus

  Reacting to Session Events:
  Link to page:
  https://o3deorg.netlify.app/docs/user-guide/deadlink

  Using O3DE Networking:
  Link to page:
  https://o3deorg.netlify.app/docs/user-guide/deadlink

  Direct Access to EBus Handlers:
  Link to page:
  https://o3deorg.netlify.app/docs/user-guide/deadlink

  Tick Bus and Components:
  Link to page:
  https://o3deorg.netlify.app/docs/user-guide/engine/ebus/tick.md

  The following links leads to a 404 page.

**Comment by FiniteStateGit** [comment]
Page no longer exists, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
