### ISSUE TITLE
[ISSUE][DOCS] Create global or localized wind forces with PhysX page is outdated

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de.org#1438]
## Describe the issue

The "Create global or localized wind forces with PhysX" page is outdated as it refers to slices - Step 10.
"Perspective" is used instead of "Viewport" - Step 9.
The page also contains outdated information that "PhysX Configuration" can be accessed by opening the "File" menu.
Currently the "PhysX Configuration" is available in the "Tools" menu.

## Impacted page

https://www.o3de.org/docs/user-guide/interactivity/physics/nvidia-physx/wind-provider/

## Expected experience

The page is up to date, there are no slice references, up to date tool naming is used.

**Comment by LB-JakubSkorupka** [comment]
The documentation page mentioned in the issue in currently not available as the link redirects to the 404 page. Would you like us to create a separate issue for this?

**Comment by micronAMZN** [comment]
The page has been moved to tutorials. https://www.o3de.org/docs/learning-guide/tutorials/physx/wind-provider/
