### ISSUE TITLE
[ISSUE][DOCS] UI Interactive Components and Visual Components documentation pages should be laid out similarly to the Layout Components documentation page

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de.org#1444]
## Describe the issue

UI Components > Interactive Components documentation page contains only the names of Interactive Components, and the UI Components > Visual Components documentation page contains only a description of what the Visual Components do. UI Components > Layout Components documentation page (https://www.o3de.org/docs/user-guide/interactivity/user-interface/components/layout/) contains a table of all Layout Components with their descriptions, which is more user friendly.

## Impacted page(s)

https://www.o3de.org/docs/user-guide/interactivity/user-interface/components/interactive/
https://www.o3de.org/docs/user-guide/interactivity/user-interface/components/visual/

## Expected experience

UI Components > Interactive Components and UI Components > Visual Components documentation pages are updated to be laid like the UI Components > Layout Components documentation page (Contain the tables of their respective components with short descriptions).

**Comment by FiniteStateGit** [comment]
To address this issue directly, a `Section topics` heading could be added to `user-interface/components/_index.md` and each of the component categories' index page. 

I would like to remove the `transform` and `other` directories as part of a PR for this issue.  The transform2d component is documented on 3 pages; it could be done on a single page.  There is no discernable functional difference between uncategorized components and those in the `other` category.  

The tooltip components are a single page category, they work in tandem, I only recommend renaming the `linkTitle` to match other categories.  The Dynamic components do *not* work together, Dynamic Scroll Box and Dynamic Layout should have separate pages.  Dynamic Layout would fit well in the `layout` category, I'd like to move it there.  Dynamic Scroll Box is dependent on UI Scroll Box and should be placed with it in the same category (even though it is not an interactive component).

Section topics for the main UI component page would list (after some re-ordering):
Working with UI components (single page)
UI Transform2D                  (single page)
Visual components             (directory)
Interactive components      (directory)
Layout components            (directory)
Tooltip components            (single page)
UI Fader                               (single page)
UI Flipbook                          (single page)
UI Mask                               (single page)
UI Spawner                          (single page)
