### ISSUE TITLE
[ISSUE][DOCS] Configuring Canvas Properties documentation page multiple issues

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de.org#1448]
## Describe the issue
There are multiple issues with the Configuring Canvas Properties documentation page, they will be listed here along with their Expected experience:
1. Configuring Canvas Properties contains a deprecated image of the UI Canvas pane:
![ui-editor-canvas-properties](https://user-images.githubusercontent.com/86952082/155720938-471441a0-ca2d-4774-a321-b2548aecb853.png)
Current UI Canvas pane:
![UICanvas](https://user-images.githubusercontent.com/86952082/155720997-a5a6a7a6-ecda-4d1f-b87a-353350559850.PNG)
**Expected experience**: Documentation does not contain deprecated images.

2. Rendering Properties section - "Draw order" does not mention its default value, while other described properties do (e.g. "Is pixel aligned - Selected by default"). The default "Draw order" value is 0.
**Expected experience**: "Draw order" description mentions its default value to remain consistent with other descriptions on this documentation page.

3. Input Properties section - "Handle multi-touch" and "Handle navigation" descriptions mention that these properties are cleared by default, while they are selected by default currently in engine. "Handle multi-touch - Cleared by default. When this property is selected, ...", "Handle navigation - Cleared by default. When this property is selected, ...". 
**Expected experience**: Default value of the "Handle multi-touch" and "Handle navigation" properties is corrected in their description to remain consistent with how they appear in engine.

## Impacted page(s)

https://www.o3de.org/docs/user-guide/interactivity/user-interface/canvases/canvas-properties/

**Comment by chanmosq** [comment]
Created a PR to resolve this - https://github.com/o3de/o3de.org/pull/1570

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed.
