### ISSUE TITLE
[BROKEN LINK] Debugging Asset Processor Issues contains broken image link.

### ISSUE THREAD

**Issue by FiniteStateGit** [o3de/o3de.org#1460]
## Which page has the broken link?

https://www.o3de.org/docs/user-guide/assets/asset-processor/debugging/

## Which link was broken?

https://www.o3de.org/images/user-guide/asset_processor/create-logging-tab.png

## Know where it should go?

https://www.o3de.org/images/user-guide/assets/asset_processor/create-logging-tab.png

**Comment by willihay** [comment]
Good catch. There's even a second error in that link. The directory is `asset-processor`, not `asset_processor`.
