### ISSUE TITLE
[Dead Links]: O3DE User guide /Appendix /CVARs /Debugging Issues

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#150]
Link to page:
https://o3deorg.netlify.app/docs/user-guide/appendix/cvars/debugging

Legacy:
Link to page:
https://o3deorg.netlify.app/docs/user-guide/deadlink#legacy

CryEntity Removal gem:
Link to page:
https://o3deorg.netlify.app/docs/user-guide/deadlink

Project Configurator:
Link to page:
https://o3deorg.netlify.app/docs/user-guide/deadlink

Command Line:
Link to page:
https://o3deorg.netlify.app/docs/user-guide/deadlink

The following links leads to a 404 page.

**Comment by FiniteStateGit** [comment]
No dead links found on page: https://o3deorg.netlify.app/docs/user-guide/appendix/cvars/debugging .
@LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issues, the page no longer has dead links.
