### ISSUE TITLE
[Obsolete Links]: O3DE User guide /Appendix /CVARs /Debugging Issues : Multiple links are pointing to Lumberyard materials

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#151]
Link to page:
https://o3deorg.netlify.app/docs/user-guide/appendix/cvars/debugging/

The following links on the page lead to the Lumberyard material:
Character skeleton debugging:
https://docs.aws.amazon.com/lumberyard/latest/userguide/lumberyard-documentation-archive.html

Mannequin debugging:
Link to page:
https://docs.aws.amazon.com/lumberyard/latest/userguide/lumberyard-documentation-archive.html

**Comment by FiniteStateGit** [comment]
Page no longer links to Lumberyard materials. @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
