### ISSUE TITLE
Feature Request：Introduce the ReflectionProbeVisualization materialtype in the O3DE Documentation

### ISSUE THREAD

**Issue by liukaikai-g** [o3de/o3de.org#1512]
**Is your feature request related to a problem? Please describe.**
I find that I can create the materials in the Material Editor, but I can't find the instructions for them in the O3DE Documentation, can you add instructions for them.

**Describe the solution you'd like**
Introduce the ReflectionProbeVisualization materialtype in the O3DE Documentation.

**Describe alternatives you've considered**

**Additional context**

**Comment by chanmosq** [comment]
@liukaikai-g Thanks for opening this ticket! We do need to create docs for ReflectionProbeVisualization, and other material types. In the meantime, you'll find all the materials docs at https://www.o3de.org/docs/atom-guide/look-dev/materials/. We have a [tutorial](https://www.o3de.org/docs/atom-guide/look-dev/materials/create-standardpbr-material/) for using the Material Editor to create StandardPBR, and I'm guessing what you're looking for is something similar for ReflectionProbeVisualization.

**Comment by chanmosq** [comment]
Spoke to @dmcdiarmid-ly - **ReflectionProbeVisualization** material type is not expected to be edited or used by users; it's specifically for internal use by the Reflection Probe systems (which you can integrate via the [Reflection Probe component](https://www.o3de.org/docs/user-guide/components/reference/atom/reflection-probe/)). 

Closing this ticket and created this new one (https://github.com/o3de/o3de/issues/8700) to hide material type from Material Editor.
