### ISSUE TITLE
[ISSUE][DOCS] There is no indication on the Setting Up Atom Projects site that the AtomTest project is deprecated 

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de.org#1533]
## Describe the issue

The Setting Up Atom Projects documentation site contains information on how to setup and build the AtomTest project, which according to the comment in https://github.com/o3de/o3de-atom-sampleviewer/issues/397 is in deprecation and has not been maintained.

## Impacted page(s)

https://www.o3de.org/docs/atom-guide/setup-atom-projects/

## Expected experience

Deprecated features are clearly labeled.

**Comment by chanmosq** [comment]
Looking into this now.
