### ISSUE TITLE
O3DE website update for 22.05.0 release

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de.org#1535]
## Describe the feature you'd like available on the website

We need to update the O3DE website, including the doc site, with the new release information and the new logo and color scheme.

## Proposed implementation

**Release number update**
The changes will need to be made in the following locations:
1. [Download page](https://www.o3de.org/download/) (for both windows and linux) needs to be updated with the new release number: 22.05.0
    - O3DE Stable 21.11 release --> O3DE Stable 22.05.0 Release
3. "https://o3debinaries.org/download/windows.html" (for both windows and linux) needs to be updated with the new release number (22.05.0)
4. "https://o3debinaries.org/download/windows.html" (for both windows and linux) the download button needs to point to the correct build location. 
    - @amzn-changml to provide the build location.
6. [Release note](https://www.o3de.org/docs/release-notes/) page update with the latest release note.
     * Move the version 2111.2 to the archive section
     * Update the page with the new release version: 22.05.0. Note the latest source code and the latest version should be using the same version number.

**Logo update**
1. we need to replace the old O3DE logo with the new one. This includes the following locations
    - Logo on the banner area
    - Logo in the tutorials, such as getting stated guide
    - Logos on the Community page
3. The CSS needs to be updated with the new color palette. this includes: button, hover state, hyperlinks, tabs, etc.
4. This maybe scope outside of the website, but we also need to update the logos on all of our social media pages, such as youtube, twitter, fb, discord, ghi, etc.
5. The [Branding guideline page on O3DE.org](https://www.o3de.org/docs/tools-ui/branding-guidelines/) should also be updated with the new logo, logo asset packet, and the link to the official branding guideline doc

Note @FiniteStateGit also provided a list of logo locations that we need to look at to make sure they will be replaced with the correct logo file and info.

## Available alternatives

N/A.

**Comment by FiniteStateGit** [comment]
| Directory | File |
| - | - |
| static |  |
| static |  |
| static |  |
| static |  |

**Comment by Ulrick28** [comment]
Looking at this ticket, do we want to remove any reference to version and instead say 'download latest version'?

**Comment by yuyihsu** [comment]
@cmassey11 can you confirm if LF will own this ticket and work on the web update indicated in this ticket?

**Comment by cmassey11** [comment]
> 

@yuyihsu - Khahil (@theheels) is running point on this website update project. Looks like he may need someone to give him permissions to this repo. He will also respond to you in Discord.

**Comment by theheels** [comment]
> 2. The CSS needs to be updated with the new color palette. this includes: button, hover state, hyperlinks, tabs, etc.
@yuyihsu Does a new color pallet already exist for these assets, or does that need to be created?

**Comment by theheels** [comment]
@yuyihsu Giving this one a follow up. Do we have an existing color palette for the site?

**Comment by LB-ArturZieba** [comment]
We have noticed that the https://www.o3de.org/docs/tools-ui/branding-guidelines/ is not mentioned in this issue, should it be reported as a separate issue, or is this comment sufficient?

**Comment by yuyihsu** [comment]
@theheels Based on the new logo update, my understanding is that we will not update the color palette on O3DE, it will remain to be the same shades of blue we have today. So I believe we don't need to update the color palette on the website, just need to replace the logo with the new logo.

If you want to check out the current color palette, I believe the current CSS files should have all of the data you need. Or you can check out the branding guideline for the current logo, it has the color palette defined in it: https://www.o3de.org/docs/tools-ui/branding-guidelines/

**Comment by chanmosq** [comment]
Closing this issue because of staleness.
