### ISSUE TITLE
[DOCS] Document how to use source control for projects

### ISSUE THREAD

**Issue by FiniteStateGit** [o3de/o3de.org#1553]
## Describe the issue briefly

Create content for a drafted page.

Page metadata:
title: "Projects and Source Control"
weight: 500
draft: true

Related issues: 
https://github.com/o3de/o3de.org/issues/1509
https://github.com/o3de/o3de.org/issues/964

## Which page(s) / section(s) are affected?

content\docs\user-guide\project-config\project-source-control.md

**Comment by chanmosq** [comment]
Closing this issue in favor of related issues, #1509 and #964, which provide a clearer request for documentation. 

Because this is a placeholder page, it serves no purpose in the docs and should be removed. https://github.com/o3de/o3de.org/pull/2227
