### ISSUE TITLE
[DOCS] Document how to implement navigation and pathfinding

### ISSUE THREAD

**Issue by FiniteStateGit** [o3de/o3de.org#1555]
## Describe the issue briefly

Create content for a drafted page.

Page metadata:
title: Navigation and Pathfinding
draft: true

## Which page(s) / section(s) are affected?

content\docs\user-guide\interactivity\navigation-and-pathfinding\_index.md

## Does this work have an engineering dependency? What is it?

It might.  O3DE doesn't ship with a pathfinding component.  Navigation and pathfinding could be implemented as a script or custom component.  There are two third-party gems available, KytheraAI and https://github.com/AMZN-Olex/RecastNavigationO3DE.  KytheraAI is not fully reflected to behavior context, while RecastNavigationO3DE is.  Recast needs to be updated for an impactful change: https://github.com/o3de/o3de/pull/7609.

**Comment by sptramer** [comment]
Declined due to the fact that pathfinding and AI are not included in a core distributed Gem at this time. Would suggest deleting the draft page.
