### ISSUE TITLE
[DOCS] Document how textures are supported and processed in Atom.

### ISSUE THREAD

**Issue by FiniteStateGit** [o3de/o3de.org#1563]
## Describe the issue briefly

Create content for a drafted page.

Page metadata:
title: "Textures"
description: "Learn about how textures are supported and processed in Atom Renderer."
toc: true
weight: 300

## Which page(s) / section(s) are affected?

content\docs\atom-guide\look-dev\textures\_index.md

**Comment by chanmosq** [comment]
Textures are documented here: https://www.o3de.org/docs/user-guide/assets/texture-settings/

Linked a PR to remove page: https://github.com/o3de/o3de.org/pull/2225
