### ISSUE TITLE
[Dead Links]: O3DE User guide /visualization /animation /animation-editor /creating-simulated-objects

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#158]
Samples Project :
Link to page:
https://o3deorg.netlify.app/docs/userguide/samples/projects/samples.md

Step 1: Creating a Motion Set:
Link to page:
https://o3deorg.netlify.app/docs/userguide/animation/editor/quick-start#creating-a-motion-set-with-animation-editor

**Comment by FiniteStateGit** [comment]
Page no longer exists, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
