### ISSUE TITLE
[Dead Links]: O3DE User guide /visualization /animation /animation-editor /retargeting-animations

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#160]
Importing Assets into O3DE:
Link to page:
https://o3deorg.netlify.app/docs/userguide/assets/importing.md

**Comment by FiniteStateGit** [comment]
Page no longer exists, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
