### ISSUE TITLE
[Dead Links]: O3DE User guide /visualization /animation /animation-editor /math-nodes

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#161]
quaternions:
Link to page:
https://o3deorg.netlify.app/docs/userguide/ly-glos-chap#quarternion

[See the AWS documentation website for more details]
Link to page:
https://o3deorg.netlify.app/docs/userguide/animation/editor/math-nodes

**Comment by FiniteStateGit** [comment]
Page no longer exists, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
