### ISSUE TITLE
[Dead Links]: O3DE User guide /visualization/animation/character-editor/components

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#164]
Adding Components to an Entity:
Link to page:
https://o3deorg.netlify.app/docs/userguide/components/working-adding.md

**Comment by FiniteStateGit** [comment]
Page no longer exists, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
