### ISSUE TITLE
User experience survey+O3DCon promotion banner on the website

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de.org#1654]
## Describe the feature you'd like available on the website

We are launching the O3DE UX survey on 5/20, and we'd like to use the website banner to promote the UX survey to get more traction to the survey.

## Proposed implementation

The promotional banner has been built for the game jam promotion last year. We would like to use the same banner to promote the UX survey.

The banner is currently disabled: [https://github.com/o3de/o3de.org/blob/main/layouts/partials/top-banner.html](https://github.com/o3de/o3de.org/blob/main/layouts/partials/top-banner.html
)
And here's the PR that introduced the banner: [https://github.com/o3de/o3de.org/pull/1025/files](https://github.com/o3de/o3de.org/pull/1025/files)

Suggested message to display on the banner:
![image](https://user-images.githubusercontent.com/75449675/169318270-bcf41e1c-8858-4a01-920f-79e3cd8576b3.png)

Message for mobile version:

We Want to Hear From You!
Take the O3DE Survey

## Available alternatives

We should display this banner on the following sections of the website:
1. Landing page
2. Download page
3. Docs site

**Comment by chanmosq** [comment]
@yuyihsu Can you provide the link to the survey please?

**Comment by chanmosq** [comment]
@yuyihsu Any updates if this issue should be closed or resolved? If resolved, can you provide a link to the survey?

**Comment by yuyihsu** [comment]
Closing this ticket as the survey has ended in June.
