### ISSUE TITLE
As a Dev I Want to Know About .CFG Files

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de.org#1657]
## Describe the issue briefly
CFG's are commonly used in for triggering opening apps and triggering cvars but there isn't much documentation on them.

Questions to Answer
Q: How do I open my app with a cfg's?
  - A: Use the commandline arg _console-command-file_. Example: Example: start .\build\windows\bin\profile\MultiplayerSample.GameLauncher.exe --console-command-file=client.cfg

Q: Does the order of elements matter in the cfg file?
   - A: Yes. Once a CFG is loaded, each line is ran into cvar console in the order it's written.

## Which page(s) / section(s) are affected?
https://www.o3de.org/docs/user-guide/editor/console-cvars-commands/

## Does this work have an engineering dependency? What is it?
No. This is all explaining stuff that already exists.

**Comment by sptramer** [comment]
This is really a request for general documentation on:

* What are .CFG files for?
* How do I load them?
* How should I author .CFG files to make sure things run correctly? (Networking-specific for some, other-specific for certain other CVar-base config scenarios.)

**Comment by willihay** [comment]
This issue was also addressed more broadly in [Issue Console Commands](https://development--o3deorg.netlify.app/docs/user-guide/settings/issue-az-console-commands/#sequencing-when-console-commands-are-invoked).
