### ISSUE TITLE
[ISSUE][DOCS] Terrain World documentation page contains deprecated image and has deprecated/missing information 

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de.org#1670]
## Describe the issue

Terrain World documentation page contains deprecated image under the Terrain World Properties section:
![image](https://user-images.githubusercontent.com/86952082/170246972-1ff0892b-60f1-4cce-9b99-2da10f392020.png)
Currently:
![TerrainWorldComponent](https://user-images.githubusercontent.com/86952082/170247126-190b08de-2692-4012-a755-d9782a4cfcb8.PNG)

Height Query Resolution (m) property information in the table under the Terrain World Properties section is deprecated, as it lists its Value and Default as Vector2, while it is a Number.

The table under the Terrain World Properties section is also missing information about the Surface Data Query Resolution (m)

## Impacted page(s)

https://www.o3de.org/docs/user-guide/components/reference/terrain/world/

## Expected experience

Documentation contains current information.

**Comment by FiniteStateGit** [comment]
This issue was resolved in a recently merged PR, #1884.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed.
