### ISSUE TITLE
[ISSUE][DOCS] Terrain World Renderer documentation page contains deprecated image and is missing information

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de.org#1671]
## Describe the issue

Terrain World Renderer documentation page contains deprecated image under the Properties section:
![image](https://user-images.githubusercontent.com/86952082/170251984-db1bcb0e-99ad-437e-8fa9-0327a04fb39b.png)
Current:
![TerrainWorldRendererComponent](https://user-images.githubusercontent.com/86952082/170252002-46dc32b4-53d5-487f-b087-a67f0c2a99f6.PNG)

There is also no information about existing properties of the Terrain World Renderer component:
* Height based texture blending
* Detail material render distance
* Detail material fade distance
* Detail material scale
* Mesh render distance
* First LOD distance

## Impacted page(s)

https://www.o3de.org/docs/user-guide/components/reference/terrain/world-renderer/

## Expected experience

Documentation contains current information.

**Comment by FiniteStateGit** [comment]
This issue was resolved in a recently merged PR, #1884.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed.
