### ISSUE TITLE
[DOCS] Multiple issues with Networking CVars

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#1672]
## Describe the issue briefly

Walk the engine testing by @o3de/sig-ui-ux revealed the following issues regarding CVars specifically related to Networking, which should be categorized together:

* It's currently unclear if the ordering of CVar setting is critical for either a game client or game server.
     - This will be fixed by #1673
* Unclear where and when CVars need to be set in order to get specific types of networking or multiplayer behavior.
     - This will be fixed by #1673
* Current naming conventions for CVars make it unclear which settings affect what - there is a reliance on prefixing or suffixing, such as `editorsv` and `sv_`, which are inconsistently applied.
    - Resolved. See https://www.o3de.org/docs/user-guide/networking/settings/
* The `isdedicated` CVar is not adequately explained and is initially set to `false` and is appropriate, but causes confusion - this CVar controls whether or not Editors can connect as a client, not whether or not the server is a "dedicated host".
    - This will be fixed by #1673.

Host and Connect cvar is missing from:
https://www.o3de.org/docs/user-guide/networking/settings/

## Which page(s) / section(s) are affected?

Networking and multiplayer sections:
* https://www.o3de.org/docs/user-guide/networking/
* https://www.o3de.org/docs/user-guide/gems/reference/multiplayer/multiplayer-gem/overview/

## Does this work have an engineering dependency? What is it?

No

**Comment by sptramer** [comment]
Also related to needed RFC: Automated reference generation for CVars.

**Comment by lmbr-pip** [comment]
@sptramer We have a general CVAR naming guide here: https://www.o3de.org/docs/user-guide/appendix/cvars/#common-cvar-prefixes

And a whole networking CVAR set of docs here: https://www.o3de.org/docs/user-guide/networking/settings/

Not sure what else we need

**Comment by rainbj** [comment]
"Host" and "connect" cvar are not on this cvar pages that will be needed for testing.

**Comment by lmbr-pip** [comment]
host and connect are not cvars, they are legacy cry actions I believe hence they are missing from initial docs. They are covered elsewhere in settings.

**Comment by AMZN-Gene** [comment]
Seems bad to not include host and connect legacy cry actions since they are really useful, but good to know it's covered elsewhere.
Closed.
