### ISSUE TITLE
[ISSUE][DOCS] Lack of information about linking hyperlinks in the source code

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de.org#1705]
## Describe the issue

Some hyperlinks have provided URL with **www** domain, while others do not. There is no information about providing hyperlinks to the source code in either way. For example:
![image](https://user-images.githubusercontent.com/100559077/173370900-dd2c6a10-2ec6-4504-83a9-28f769cd8a05.png)
![image](https://user-images.githubusercontent.com/100559077/173370929-28d7436a-2c4b-4be4-8a33-ce2516c5eebe.png)

## Impacted page(s)

https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md

## Expected experience

There is an information about linking hyperlinks in the source code.

**Comment by FiniteStateGit** [comment]
Closing this issue as coding standards are not maintained by sig-docs-community.  Their standards are linked already from the documentation website.
