### ISSUE TITLE
[Obselete Information]: O3DE User guide /Appendix /CVARs /Debugging Issues: Unexpected results by multiple debugging commands

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#171]
Link to page:
  https://o3deorg.netlify.app/docs/user-guide/appendix/cvars/debugging

 "Using Console Debug Views 
  The viewport window displays debugging information by default when you are in gameplay mode (Ctrl+G). You can toggle this 
  information on or off by pressing the tilde (~) key. Use the following console variables and values to generate viewing modes in 
  the viewport that are useful for debugging".

1.) p_draw_helpers 1:

  - Expected Result:
     Shows physics proxy meshes in addition to the render geometry.

  - Actual Result:
    Unknown command.

2.) e_TerrainBBoxes:

  - Expected Result:
    Displays terrain bounding boxes.

  - Actual Result:
    Unknown Command

3.) p_debug_joints:

  -  Expected Result:
     Shows the mass of objects in kilograms and the joint that is linked to the object. 
     (To display joints, you must first enable p_draw_helpers 1)

  -  Actual Result:
     Unknown Command.

4.)  r_TexBinModes 6 :

   - Expected Result:
     Applies a uniform, flat, gray material with normal map information to every surface in the level.

5.)  e_DebugDraw 8 :                                                                

   - Expected Result
     Displays RenderWorld statistics (with view cones).
     
   - Actual Result:
     Free Slot

6.) e_DebugDraw 9 : 

   - Expected Result:
     Displays RenderWorld statistics (with view cones without lights).
   
   - Actual Result:
     Free Slot
 
7.)  e_DebugDraw 10 : 

   - Expected Result :
      Displays render geometry with simple lines and triangles.

   - Actual Result :
     Deprecated option, use "r_showlines 2 instead

8.)  e_DebugDraw 11 :
    
   - Expected Result
     Displays render occlusion geometry.

   - Actual Result:
     Free Slot

9.)  e_DebugDraw 12 : 

   - Expected Result :
     Displays render occlusion geometry without render geometry.

   - Actual Result ;
     Free Slot

10.)  e_DebugDraw 18 : 

    - Expected Result : 
      Displays streaming information (required streaming speed).

    - Actual result : 
      Free Slot

11.) p_profile_enitties 1 : 

    - Expected Result : 
      Runs your scene and looks for fluctuations. You can use this console variable to identify which entities are causing large 
      peaks.

    - Actual Result : 
      Unknown Command

      Pointed commands has unexpected results, or no results at all.

**Comment by LB-MateuszSzweda** [comment]
Verified as fixed on 11/17/2022 the page from the description was correctly removed and result in 404 Page not found on multiple web browsers.
