### ISSUE TITLE
[Obsolete Information]: Asset Memory Analyzer Gem: Certain steps cannot be followed

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#172]
Link: https://o3deorg.netlify.app/docs/user-guide/gems/reference/asset-memory-analyzer/

Due to the earlier section not being completable ("Enable the Asset Memory Analyzer") it's not possible to complete steps listed within "View Live Asset Memory Analysis with ImGUI", "Export an Asset Memory Analysis Snapshot to a File", "View a JSON Asset Memory Analysis Snapshot in a Browser", as there is no Asset Memory Analyzer gem enabled within the editor and there is no AssetMemoryAnalyzer tab when enabling the ImGUI overlay in play mode.

**Comment by FiniteStateGit** [comment]
Page is now found at: https://o3deorg.netlify.app/docs/user-guide/gems/reference/debug/asset-memory-analyzer/

**Comment by LB-RobertBaczkowski** [comment]
The issue described still occurs on the new page.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the engine side (GitHub Development (7580155), and Stabilization 22.05 Installer were verified). No references on the [o3de.org](http://o3de.org/) as is were found, however in the [github.com/o3de/o3de.org](http://github.com/o3de/o3de.org) repository there still exists a folder referencing the Asset Memory Analyzer gem: https://github.com/o3de/o3de.org/tree/main/static/docs/api/gems/assetmemoryanalyzer.
