### ISSUE TITLE
[Obsolete materials]: Asset Memory Analyzer Gem: Page contains images from Lumberyard editor

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#173]
Link: https://o3deorg.netlify.app/docs/user-guide/gems/reference/asset-memory-analyzer/

The page contains multiple images displaying Lumberyard UI and name:
![image](https://user-images.githubusercontent.com/80751316/111760017-86a36e80-889e-11eb-9673-adf1a79a8001.png)
![image](https://user-images.githubusercontent.com/80751316/111760166-acc90e80-889e-11eb-9c71-b61e6a84fffc.png)
![image](https://user-images.githubusercontent.com/80751316/111760171-afc3ff00-889e-11eb-9f49-f652f388d708.png)
![image](https://user-images.githubusercontent.com/80751316/111760177-b2beef80-889e-11eb-9ef2-14e14e61e9ef.png)
![image](https://user-images.githubusercontent.com/80751316/111760182-b5214980-889e-11eb-827d-636871f033f0.png)

**Comment by FiniteStateGit** [comment]
Page is now found at: https://o3deorg.netlify.app/docs/user-guide/gems/reference/debug/asset-memory-analyzer/

**Comment by LB-RobertBaczkowski** [comment]
The issue described still occurs on the new page.

**Comment by micronAMZN** [comment]
The Asset Memory Analyzer Gem and topic have been removed from O3DE.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the engine side (Development (58adaf9)), as per https://github.com/o3de/o3de.org/issues/172#issuecomment-1125891871 this page could not have been found via regular search on o3de.org, and seems to be the last instance of the Asset Memory Analyzer Gem mention in the o3de.org repository.
