### ISSUE TITLE
[ISSUE][DOCS] libffi6 no longer needed?

### ISSUE THREAD

**Issue by Jackerty** [o3de/o3de.org#1732]
## Describe the issue

In the section "_Python 3.7 dependency on libffi_" on "_O3DE System Requirements_"  package download steps use an outdated libffi version at least for the current git version. I think this is true for the current download version of O3DE as well but I am not using Ubuntu so it is hard for me to confirm.

## Impacted page(s)

[welcome-guide/requirements/#python-37-dependency-on-libffi](https://www.o3de.org/docs/welcome-guide/requirements/#python-37-dependency-on-libffi)

## Expected experience

Variable LIBFFI_PACKAGE_NAME to be libffi7.

**Comment by willihay** [comment]
@o3de/sig-platform please confirm

**Comment by spham-amzn** [comment]
> @o3de/sig-platform please confirm

Correct, beginning with python-3.7.12-rev2-linux, libffi is now statically linked into the python distribution, so it no longer has a dependency on the system lib.

**Comment by Jackerty** [comment]
So, the whole section about libffi dependency should be removed?
