### ISSUE TITLE
[ISSUE][DOCS] "Physics materials" documentation page should be reworked

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de.org#1743]
## Describe the issue

"Physics materials" documentation page should be reworked from the ground up, as it mentions PhysX Materials in context of the Physics Libraries which are currently deprecated. While some of the provided information is still current, and can be reused (for example https://www.o3de.org/docs/user-guide/interactivity/physics/nvidia-physx/materials/#physics-material-properties), most of the information, and screenshots on the page show/mention the old physics library system.

## Impacted page(s)

https://www.o3de.org/docs/user-guide/interactivity/physics/nvidia-physx/materials/

## Expected experience

Documentation contains current information.

**Comment by moraaar** [comment]
Closing this as it was already done here: https://github.com/o3de/o3de.org/pull/1970

There are no more references to physics material library.
