### ISSUE TITLE
[ISSUE][DOCS] Mentions of Physics Material Library in documentation

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de.org#1744]
## Describe the issue

This issue will be used as a tracking tool for issues, and pull requests regarding the deprecated Physics Material Library mentions in the documentation. Currently the Physics Material Library has been changed to standalone PhysX Materials in engine. Please link any other issues/pull requests regarding the Physics Material Library mentions in the documentation, which are not listed below.

## Impacted page(s)

* Physics materials - https://www.o3de.org/docs/user-guide/interactivity/physics/nvidia-physx/materials/ - Related issue: https://github.com/o3de/o3de.org/issues/1743
* PhysX Shape Collider Component - https://www.o3de.org/docs/user-guide/components/reference/physx/shape-collider/ - Related pull request: https://github.com/o3de/o3de.org/pull/1745
* PhysX Collider Component - https://www.o3de.org/docs/user-guide/components/reference/physx/collider/ - Related pull request: https://github.com/o3de/o3de.org/pull/1751
* PhysX Character Controller Component - https://www.o3de.org/docs/user-guide/components/reference/physx/character-controller/ - Multiple issues:
   *  "PhysX Character Controller Properties" section - Component screenshot is deprecated.
   *  "PhysX Character Controller Properties" section - "Library (Physics Materials)", and "Slot (Physics Materials)" properties should be reduced to a "Physics Material" property, similar to the https://www.o3de.org/docs/user-guide/components/reference/physx/collider/ documentation page.
   *  "PhysX Character Controller Properties" section - The property table is missing "Value" and "Default" columns, which contain used values, their ranges, and defaults (Please refer to the https://www.o3de.org/docs/user-guide/components/reference/physx/collider/#base-properties for context).
   * "Differences Between PhysX and Legacy Character Physics Components" section - This section should be renamed, as it references the Legacy Character Physics Component, which are not present in the engine. It should be noted that the text under this section does not contain deprecated information.
* PhysX Collision Groups - https://www.o3de.org/docs/user-guide/interactivity/physics/nvidia-physx/configuring/configuration-collision-groups/ - Related pull request: https://github.com/o3de/o3de.org/pull/1765
* PhysX System Global Configuration - https://www.o3de.org/docs/user-guide/interactivity/physics/nvidia-physx/configuring/configuration-global/ - Multiple issues:
   * "PhysX System Global Configuration" section - Tool screenshot is deprecated.
   * "Physics materials" section - Should be removed, as currently this section is not present in the PhysX Configuraton (PREVIEW) tool.
   * All of the tables on this documentation page (sections: "System configuration", "Scene configuration", "Editor configuration", "Wind configuration"), are missing "Value" and "Default" columns, which contain used values, their ranges, and defaults (Please refer to the https://www.o3de.org/docs/user-guide/components/reference/physx/collider/#base-properties for context).
* Scene Settings PhysX Tab - https://www.o3de.org/docs/user-guide/assets/scene-settings/physx-tab/ - Multiple issues:
   * "PhysX tab properties", and "Convex asset" sections - Tool screenshots are deprecated.
   * All of the tables on this documentation page (sections: "PhysX tab properties", "Triangle mesh asset", "Convex asset", "Primitive asset", "Decompose meshes"), are missing "Value" and "Default" columns, which contain used values, their ranges, and defaults (Please refer to the https://www.o3de.org/docs/user-guide/components/reference/physx/collider/#base-properties for context).

## Expected experience

Documentation contains current information.

**Comment by LB-ArturZieba** [comment]
I have verified that the mentioned physics material library information was addressed. However, there are still a few issues mentioned that are still present: 
* PhysX Character Controller Component:
   * "PhysX Character Controller Properties" section - Component screenshot is deprecated.
   * "PhysX Character Controller Properties" section - The property table is missing "Value" and "Default" columns, which contain used values, their ranges, and defaults (Please refer to the https://www.o3de.org/docs/user-guide/components/reference/physx/collider/#base-properties for context).
   * "Differences Between PhysX and Legacy Character Physics Components" section - This section should be renamed, as it references the Legacy Character Physics Component, which are not present in the engine. It should be noted that the text under this section does not contain deprecated information.
* PhysX System Global Configuration:
   *  All of the tables on this documentation page (sections: "System configuration", "Scene configuration", "Editor configuration", "Wind configuration"), are missing "Value" and "Default" columns, which contain used values, their ranges, and defaults (Please refer to the https://www.o3de.org/docs/user-guide/components/reference/physx/collider/#base-properties for context).
* Scene Settings PhysX Tab:
   * All of the tables on this documentation page (sections: "PhysX tab properties", "Triangle mesh asset", "Convex asset", "Primitive asset", "Decompose meshes"), are missing "Value" and "Default" columns, which contain used values, their ranges, and defaults (Please refer to the https://www.o3de.org/docs/user-guide/components/reference/physx/collider/#base-properties for context).

Should I open a separate ticket for these, or reopen this issue?

**Comment by moraaar** [comment]
> I have verified that the mentioned physics material library information was addressed. However, there are still a few issues mentioned that are still present:
> 
> * PhysX Character Controller Component:
>   
>   * "PhysX Character Controller Properties" section - Component screenshot is deprecated.
>   * "PhysX Character Controller Properties" section - The property table is missing "Value" and "Default" columns, which contain used values, their ranges, and defaults (Please refer to the https://www.o3de.org/docs/user-guide/components/reference/physx/collider/#base-properties for context).
>   * "Differences Between PhysX and Legacy Character Physics Components" section - This section should be renamed, as it references the Legacy Character Physics Component, which are not present in the engine. It should be noted that the text under this section does not contain deprecated information.
> * PhysX System Global Configuration:
>   
>   * All of the tables on this documentation page (sections: "System configuration", "Scene configuration", "Editor configuration", "Wind configuration"), are missing "Value" and "Default" columns, which contain used values, their ranges, and defaults (Please refer to the https://www.o3de.org/docs/user-guide/components/reference/physx/collider/#base-properties for context).
> * Scene Settings PhysX Tab:
>   
>   * All of the tables on this documentation page (sections: "PhysX tab properties", "Triangle mesh asset", "Convex asset", "Primitive asset", "Decompose meshes"), are missing "Value" and "Default" columns, which contain used values, their ranges, and defaults (Please refer to the https://www.o3de.org/docs/user-guide/components/reference/physx/collider/#base-properties for context).
> 
> Should I open a separate ticket for these, or reopen this issue?

All those points are not related with Physics Materials (which is the title of this ticket). Those 3 points are unrelated and I think the best way would be to create one new issue for each point. Otherwise we will never close issues.

Please create one issue for each point and I'll address them one by one when I have time.

Thanks.

**Comment by LB-ArturZieba** [comment]
I have submitted these as separate issues as requested, they can be found here:
* https://github.com/o3de/o3de.org/issues/2334
* https://github.com/o3de/o3de.org/issues/2335
* https://github.com/o3de/o3de.org/issues/2336

**Comment by moraaar** [comment]
Thanks @LB-ArturZieba
