### ISSUE TITLE
[ISSUE][DOCS] Create a Custom Tool Gem in C++ to Extend Open 3D Engine Editor documentation page contains #include <ShapeExampleWidget.h> code line that results in the project configuration fail

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de.org#1758]
## Describe the issue
In this tutorial, the file **ShapeExampleWidget.cpp** code line `#include <ShapeExampleWidget.h>` contains `<>` which results in the project configuration to fail. However, changing it to `#include "ShapeExampleWidget.h"` makes the project compile succesfully, possibly the documentation needs mentioned code line to be updated. Please, note that in the previous builds version with `<>` did not cause any issues. For more detailed information, please refer to the attached log file.

## Impacted page(s)
https://www.o3de.org/docs/learning-guide/tutorials/extend-the-editor/shape-example-cpp/#dependent-modules

## Additional files
[CMakeProjectBuildError.log](https://github.com/o3de/o3de.org/files/8999326/CMakeProjectBuildError.log)

## Expected experience
Code lines used from this tutorial compile the project succesfully.

**Comment by LB-TomaszSerwanski** [comment]
Issue verified as fixed.
