### ISSUE TITLE
[ISSUE][DOCS] Creating and Simulating a PhysX Ragdoll contains deprecated information and screenshots

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de.org#1766]
## Describe the issue

The **Creating and Simulating a PhysX Ragdoll** page contains deprecated information and images of the Editor.

For example - 

![image](https://user-images.githubusercontent.com/86951967/176443892-2d6517b2-af10-4313-b70e-84218f08e354.png)

There is no such node in **AnimGraph** as "Ragdoll" mentioned in step 2 on above screenshot.

## Impacted page(s)

https://www.o3de.org/docs/user-guide/visualization/animation/animation-editor/creating-and-simulating-physx-ragdoll/

## Expected experience

Documentation contains current information and screenshots.

**Comment by moraaar** [comment]
**[Update]** The impacted page link is not valid anymore, it's now the following one:

https://www.o3de.org/docs/user-guide/visualization/animation/animation-editor/ragdoll/ragdoll-physics-setup/
