### ISSUE TITLE
[DOCS] Programmer's Docs on Building a Gem 

### ISSUE THREAD

**Issue by chanmosq** [o3de/o3de.org#1769]
## Describe the issue briefly

Users who are developing their own code Gems in O3DE need guidance on how to properly build their Gems. Currently, there appears to be a lack of information in the User Guide > Programming > Gem Development section.

Things this doc should address:

- What command(s) to use to build via command line
- What instructions to use to build via Visual Studio 2019
- Regarding how to troubleshoot a Gem, there should be a link to a general build troubleshooting page

## Which page(s) / section(s) are affected?
A new page or section in https://www.o3de.org/docs/user-guide/programming/gems/

## Does this work have an engineering dependency? What is it?

Anything related to engineering of Gem Development system, either through command line or a configuration tool.

**Comment by sptramer** [comment]
Troubleshooting is a separate topic that shouldn't be included in build instructions. Build troubleshooting is general advice for the whole project.

**Comment by chanmosq** [comment]
Good callout! Updated the issue above.
