### ISSUE TITLE
[ISSUE][DOCS] O3DE System Requirements documentation page contains a potentially misleading link

### ISSUE THREAD

**Issue by LB-KacperSzczepanski** [o3de/o3de.org#1770]
## Describe the issue
A link to “Visual C++ Redistributable for Visual Studio 2019” is outdated and leads to a download page with “Microsoft Visual C++ Redistributable for Visual Studio 2022”. However when installing the version x64 and x86 it can be noticed that an actual name of redistributable is “Microsoft Visual C++ 2015-2022 Redistributable”. The arm64 version is the only one named “Microsoft Visual C++ 2022 Redistributable”. There is no information about compatibility in documentation page or on the page it links to.
## Impacted page(s)
https://www.o3de.org/docs/welcome-guide/requirements/
## Expected experience
 Either documentation includes an information which versions of redistributable are backwards compatible or “Visual C++ Redistributable for Visual Studio 2019” link leads to the older downloads page where the 2019 version is available. https://visualstudio.microsoft.com/vs/older-downloads/

**Comment by chanmosq** [comment]
This has been resolved. It no longer explicitly states "2019", it just says the "latest version" of the redistributable

**Comment by LB-MateuszPlatakis** [comment]
Confirming the issue has been closed as completed.
