### ISSUE TITLE
[SITE][FEATURE] Add Here Global logo as a General Member 

### ISSUE THREAD

**Issue by theheels** [o3de/o3de.org#1786]
## Describe the feature you'd like available on the website

Adding Here Global's logo to the website as a general member.

## Supplements

Logo link: https://drive.google.com/file/d/1cizDXcxBOSaN2HZsedgIouf0sBYPF2Lj/view?usp=sharing

**Comment by chanmosq** [comment]
Confirmed with @o3de/lf that this is stale.
