### ISSUE TITLE
[ISSUE][DOCS] Material Node documentation page contains formatting error

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de.org#1831]
## Describe the issue
There is an issue regarding formatting on the [Material Node](https://www.o3de.org/docs/user-guide/visualization/cinematics/track-view/nodes-material/) documentation page.
* To add a Material node in the Track View section - The numbered list should increment after the image.

![Screenshot from 2022-07-22 13-26-02](https://user-images.githubusercontent.com/99716227/180430151-f8f55251-fbfb-4f04-986f-c75f09ab0d5d.png)

## Impacted page(s)

[Material Node](https://www.o3de.org/docs/user-guide/visualization/cinematics/track-view/nodes-material/)

## Expected experience

Documentation contains no formatting errors.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed.
