### ISSUE TITLE
[ISSUE][DOCS] Using Animation Curves documentation page contains formatting errors

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de.org#1832]
## Describe the issue
There are issues regarding formatting on the [Using Animation Curves](https://www.o3de.org/docs/user-guide/visualization/cinematics/track-view/editor-animation-curves/) documentation page.
* To edit elements in a curve section - There is an empty bullet point in the list.
* To adjust a spline key section - There is an empty bullet point in the list.

![Screenshot from 2022-07-22 13-35-22](https://user-images.githubusercontent.com/99716227/180431571-469a28c9-4f2a-447b-8227-40134d9dcff9.png)

## Impacted page(s)

[Using Animation Curves](https://www.o3de.org/docs/user-guide/visualization/cinematics/track-view/editor-animation-curves/)

## Expected experience

Documentation contains no formatting errors.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed.
