### ISSUE TITLE
[ISSUE][DOCS] Docs landing page should provide information about what "main" version is

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de.org#1834]
## Describe the issue

Theres no indication on https://www.o3de.org/docs/ what version the docs refer to. Users have to know the convention to understand how to read these docs.

There should be a clear call out about what engine version pages are referencing.

```
Note: Documentation is for the xx.xx version of O3DE. For previous versions go here.
```

Would also like a callout to bleeding edge developer documentation here to.

## Impacted page(s)

https://www.o3de.org/docs/ 

## Expected experience

* Docs is very clear about what version of the engine they are for.

Hopefully covered in existing issues:
* We have a link to developer docs on this page so folks working in GitHub get access to latest docs.
* We have links to previous release versions of the engine ie 2205, 2110 etc, so I can find the most relevant docs for the engine version I am using (https://github.com/o3de/o3de.org/issues/1289)

**Comment by sptramer** [comment]
Should be addressed as part of versioning RFC https://github.com/o3de/sig-docs-community/discussions/46
