### ISSUE TITLE
[SITE][FEATURE] As a Engine Developer, I would like to easily browse and search for the engine extension related content, and see them located outside of the User Guide

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de.org#1837]
## Describe the feature you'd like available on the website

During the WTE research for WF8, several users had issues finding the help content they need to extend the engine. In the task when asked to build a python gem, some users browsed the site and spent a long time in the "User Guide" looking for help. They went to "Gems", "Project Manager", "Build", and finally "Gem Development" under Programming to look for the info, some users also went to the "Tools UI Developer’s Guide" and API references and failed to find the info they needed. None of them went to the Tutorial section in the first place, even through Search. 

Considering that in the current IA design on the Docs site, the contents for engine users and engine developers are mixed together, and the help contents for engine users occupied 80% of the site contents. This makes it hard for the Engine Developers to identify the info they need, and they are required to spend extra cognitive load to read through the titles to make sure they didn't miss any important info. 

Users also mentioned that they'd prefer to have a separate section that only contains the help content for engine development, and don't mix these contents with the engine user guide.

For those users who started from search, they also had a hard time finding their way to the tutorials section. The results for engine development and user guide are mixed, and actual link was listed down in the search result list.

![image](https://user-images.githubusercontent.com/75449675/180866275-a18dfc39-4bb2-4d65-834a-0205aee4ffee.png)

## Proposed implementation

Separate out the help content for Engine Extensions from the User Guide. Put the Engine Extension related content in a separate section that only tailors to the Engine Development/Tool Engineers.

We should also reconsider the position of the "Tools UI Developer’s Guide" and consider combining it with the Engine extension guide.

## Available alternatives

N/A

## Supplements

N/A

**Comment by sptramer** [comment]
Closing as duplicate of #1838; same request for content restructuring, remainder is known issues such as site search problems.

**Comment by sptramer** [comment]
Related to restructuring issues of #1838, needs to be addressed by the SIG as part of overall content organization.

**Comment by yuyihsu** [comment]
Close as dup (https://github.com/o3de/o3de.org/issues/1719)
