### ISSUE TITLE
[SITE][FEATURE] Engine Developers scan through the first few titles in the tutorials and skip the entire section

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de.org#1838]
## Describe the feature you'd like available on the website

During the WTE research, when the engine developers looked for the relevant engine extension help content, they only scan through the first few titles in the Tutorial section and determined there were no relevant info for them in that section. However, due to the current IA design on the Docs site, the contents for engine users and engine developers are mixed together, and the help contents for engine users occupied 80% of the site contents. This makes it hard for the Engine Developers to identify the info they need, and they are required to spend extra cognitive load to read through the titles to make sure they didn't miss any important info.

## Proposed implementation

Suggest to separate out the Engine Extension related content from the user guide. Have the Engine extension related help contents on their own section.

## Available alternatives

N/A
## Supplements

N/A

**Comment by sptramer** [comment]
This is actually a request to separate out a software manual ("how to use O3DE") from a developer's manual ("how to develop with O3DE"). Needs the SIG involvement to fully address this issue.

**Comment by yuyihsu** [comment]
Close as dup (https://github.com/o3de/o3de.org/issues/1837).
