### ISSUE TITLE
[ISSUE][DOCS] Finding Nodes documentation page contains spelling error

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de.org#1849]
## Describe the issue
There is an issue regarding spelling on the [Finding Nodes](https://www.o3de.org/docs/user-guide/scripting/script-canvas/editor-reference/nodes/finding-nodes/) documentation page:
* To find all instances of a node section - `To scroll to the left, starting at the rightmost node occurence, press F7. ` - `occurence` should be `occurrence`.

## Impacted page(s)

[Finding Nodes](https://www.o3de.org/docs/user-guide/scripting/script-canvas/editor-reference/nodes/finding-nodes/)

## Expected experience

Documentation contains no spelling errors.

**Comment by FiniteStateGit** [comment]
Fixed by #1863

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed.
