### ISSUE TITLE
[ISSUE][DOCS] Creating Script Canvas Nodes from the Behavior Context documentation page contains spelling error

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de.org#1850]
## Describe the issue
There is an issue regarding spelling on the [Creating Nodes from the Behavior Context](https://www.o3de.org/docs/user-guide/scripting/script-canvas/programmer-guide/behavior-context/) documentation page:
* Script Canvas architecture section - `The combination of the Script Canvas and behavior context archictectures includes the following benefits: ` - `archictectures` should be `architectures`.

## Impacted page(s)

[Creating Nodes from the Behavior Context](https://www.o3de.org/docs/user-guide/scripting/script-canvas/programmer-guide/behavior-context/)

## Expected experience

Documentation contains no spelling errors.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed.
