### ISSUE TITLE
[ISSUE][DOCS] Creating Custom Nodes in Script Canvas documentation page contains spelling error

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de.org#1853]
## Describe the issue
There is an issue regarding spelling on the [Creating Custom Nodes](https://www.o3de.org/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/) documentation page:

* Creating Custom Nodes in Script Canvas section - `You might wish to a create custom node in the following scenarios:` -  should be `You might wish to create a custom node in the following scenarios:`.

## Impacted page(s)

[Creating Custom Nodes](https://www.o3de.org/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/)

## Expected experience

Documentation contains no spelling errors.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed.
