### ISSUE TITLE
[ISSUE][DOCS] Customizing the Entity Icon documentation page contains formatting errors

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de.org#1862]
## Describe the issue
There is an issue regarding formatting on the [Customizing the Entity Icon](https://www.o3de.org/docs/user-guide/editor/entity-inspector-customize-icon/) documentation page.

* To customize an entity icon section - The numbered list should increment after the image.

![Customizing the Entity Icon](https://user-images.githubusercontent.com/99716227/181707635-034179df-beb9-408f-8deb-ebb58bf2f0b5.png)

## Impacted page(s)

[Customizing the Entity Icon](https://www.o3de.org/docs/user-guide/editor/entity-inspector-customize-icon/)

## Expected experience

Documentation contains no formatting errors.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed.
