### ISSUE TITLE
[Obsolete Information] "PhysX Character Controller" chapter refers to Lumberyard documentation

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#189]
Link to page: https://o3deorg.netlify.app/docs/user-guide/components/reference/physx-character-controller/

In "Differences Between PhysX and Legacy Character Physics Components" chapter in Components in O3DE User guide, the last link refers to Lumberyard instead of O3DE.
https://docs.aws.amazon.com/lumberyard/latest/userguide/lumberyard-documentation-archive.html

**Comment by FiniteStateGit** [comment]
Page now found at: https://o3deorg.netlify.app/docs/user-guide/components/reference/physx/character-controller/
Links now refer to O3DE documentation. @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
