### ISSUE TITLE
[Formatting] There is formatting issue between text and picture

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#190]
Link to page: https://o3deorg.netlify.app/docs/user-guide/components/reference/physx-rigid-body-physics/

At the bottom of the page picture overlaps with text.

![image](https://user-images.githubusercontent.com/80751316/111762644-85277580-88a1-11eb-8938-6c73f49a52be.png)

**Comment by FiniteStateGit** [comment]
Working on this, page now found at: https://o3deorg.netlify.app/docs/user-guide/components/reference/physx/rigid-body-physics/

**Comment by FiniteStateGit** [comment]
Hello @LB-RobertBaczkowski this issue should be resolved with #870 merged.  Thank you for raising the issue.

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue.
