### ISSUE TITLE
[Dead links]: Dynamic vegetation: Multiple links redirect to a missing page

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#191]
Link: https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/

The following links lead to missing pages: 
Enabling Gems
(https://o3deorg.netlify.app/docs/user-guide/deadlink)
static vegetation system
(https://o3deorg.netlify.app/docs/user-guide/deadlink)
Dynamic Vegetation Concepts
(https://o3deorg.netlify.app/docs/user-guide/gems/vegetation/concepts.md)
Dynamic Vegetation Procedures
(https://o3deorg.netlify.app/docs/user-guide/gems/vegetation/procedures.md)

**Comment by FiniteStateGit** [comment]
Page now found at: https://o3deorg.netlify.app/docs/user-guide/gems/reference/environment/vegetation/
Broken links and mentions of AWS in pages linked therein.

**Comment by FiniteStateGit** [comment]
The links listed in this issue have been removed or now refer to O3DE documentation.  Broken links and text mentioning AWS have separate issues filed: https://github.com/o3de/o3de.org/issues/193 and https://github.com/o3de/o3de.org/issues/196

@LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
No dead links on https://o3deorg.netlify.app/docs/user-guide/gems/reference/environment/vegetation/ . Closing the issue as per the comment above.
