### ISSUE TITLE
[Obsolete Information] "Using Multiple Skin Attachments for an Actor" chapter refers to Lumberyard documentation

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#192]
Link to page: https://o3deorg.netlify.app/docs/user-guide/components/reference/actor-multiple-skin/

In "Using Multiple Skin Attachments for an Actor" chapter in Components in O3DE User guide, hyperlink "Open 3D Engine Downloads" refers to Lumberyard instead of O3DE.

destination of hyperlink: https://aws.amazon.com/lumberyard/downloads/

**Comment by FiniteStateGit** [comment]
Page now found at: https://o3deorg.netlify.app/docs/user-guide/components/reference/animation/actor-multiple-skin/

All links now point to O3DE docs, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
