### ISSUE TITLE
[ISSUE][DOCS] HttpRequestor - Expand documentation to cover component ordering

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de.org#1920]
## Describe the issue

Dev was confused about how to use HttpRequestor due to lack of awareness of component ordering: https://github.com/o3de/o3de/issues/8351.

Add to the HttpRequestor docs:
* How to declare a dependency on the component so users can understand when its activated.
    * Note about when HttpRequestor is activated generally in the startup sequence
* Note about recent change to control behaviour on EC2 instances
* Add component diagram as per https://docs.unity3d.com/Manual/ExecutionOrder.html%5B%5D(https://unity3d.com/files/images/ogimg.jpg)

## Impacted page(s)

https://www.o3de.org/docs/user-guide/gems/reference/network/http-requestor/ 

## Expected experience
Page resolves confusion expressed by user trying to use gem.

**Comment by FiniteStateGit** [comment]
@lmbr-pip Are you planning to work on these documentation changes or would you be providing more information on the changes you are requesting?

**Comment by lmbr-pip** [comment]
Fixed by https://github.com/o3de/o3de.org/pull/1989
