### ISSUE TITLE
Website Search Returns No Results for CVAR prefixes

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de.org#1924]
## Describe the bug
Searching for editorsv or editorsv_ cvar prefix returns no results

## Reproduction steps
Open o3de.org
In the search bar search for "editorsv"
Notice there are no results
![image](https://user-images.githubusercontent.com/32776221/185979459-50ea4340-5ff0-45cd-86da-cba5ac0a7523.png)

## Expected behavior
The page with all of editorsv cvars should appear
https://www.o3de.org/docs/user-guide/networking/settings/

**Comment by FiniteStateGit** [comment]
As a quick fix we could add content to the page that calls out the prefixes used for cvars.  Alternatively, larger changes to our current search implementation or new search solutions could address this and similar problems.

**Comment by NiklasHenricson** [comment]
@sptramer @FiniteStateGit 

Applied the fix in the repo. It now searches properly. The document indentations were wrong on the tables and some wrong displaced areas.

![image](https://user-images.githubusercontent.com/5524755/190937541-c77b7260-814a-4481-b48e-3db4442836d3.png)

**Comment by willihay** [comment]
Proposed fix: Use the prefix by itself in the introduction to the tables that we have for each prefix.

For example, change: "The following console variables control client behavior."

To: "The `cl` CVARs control client behavior."

**Comment by AMZN-Gene** [comment]
@NiklasHenricson is your fix on O3DE.org now? The pr said it was checked into “main” but the search still returns empty today.

**Comment by AMZN-Gene** [comment]
> Proposed fix: Use the prefix by itself in the introduction to the tables that we have for each prefix.
> 
> For example, change: "The following console variables control client behavior."
> 
> To: "The `cl` CVARs control client behavior."

+1.

**Comment by AMZN-Gene** [comment]
Still an issue in both development and 21.10 versions of o3de.org
![image](https://user-images.githubusercontent.com/32776221/212623683-56653780-e5ff-4bf2-bfe2-7350bd6dbd96.png)
