### ISSUE TITLE
[Dead links]: Dynamic vegetation concepts: Multiple links redirect to a missing page

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#193]
Link: https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/concepts/

The following links lead to missing pages:
Vegetation Layer Spawner > Required Components/Optional Components/Incompatible Components > [See the AWS documentation website for more details]
(https://o3deorg.netlify.app/docs/user-guide/deadlink)
Gradients category (only one per entity) > Required Components > [See the AWS documentation website for more details]
(https://o3deorg.netlify.app/docs/user-guide/deadlink)
Gradient Modifiers category (only one per entity) > Required Components/Incopatible Components > [See the AWS documentation website for more details]
(https://o3deorg.netlify.app/docs/user-guide/deadlink)

**Comment by FiniteStateGit** [comment]
Page now found at: https://o3deorg.netlify.app/docs/user-guide/gems/reference/environment/vegetation/concepts/

**Comment by LB-RobertBaczkowski** [comment]
Issue still occurs at the new page.

**Comment by LB-RobertBaczkowski** [comment]
Confirmed that there are no dead links on the page, which can now be found here:

https://o3de.org/docs/user-guide/gems/reference/environment/vegetation/concepts/
