### ISSUE TITLE
[BUG][WEBSITE] Netlify build image reaching end of support

### ISSUE THREAD

**Issue by willihay** [o3de/o3de.org#1934]
## Describe the bug

The currently selected Netlify build image will no longer be supported after November 15th. A different build image should be selected and tested before then to keep the website building.

## Reproduction steps

Refer to the alert on the O3DE Netlify site.

**Comment by sptramer** [comment]
Fixed! There were no issues in the image migration (I was a little worried about Go) but it looks like everything is correctly configured on Netlify's end for an easy deploy.
