### ISSUE TITLE
[ISSUE][DOCS] Shared Cache documentation page is missing

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de.org#1935]
## Describe the issue

Shared Cache documentation link in the Asset Processor directs to a nonexistent web page https://www.o3de.org/docs/user-guide/assets/asset-processor/asset-cache-server/.
## Impacted page(s)

https://www.o3de.org/docs/user-guide/assets/asset-processor/asset-cache-server/

## Expected experience

Documentation page is opened in the default browser when opening it in Asset Processor.

**Comment by FiniteStateGit** [comment]
Documentation can be found in the development branch: https://development--o3deorg.netlify.app/docs/user-guide/assets/asset-processor/asset-cache-server/
