### ISSUE TITLE
[Obsolete Information] "Programmer’s Guide to Entities and Components" chapter refers to Lumberyard documentation

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#194]
Link to page: https://o3deorg.netlify.app/docs/user-guide/components/development/

In "Programmer’s Guide to Entities and Components" chapter in Components in O3DE User guide, hyperlink "Open 3D Engine C++ API Reference" refers to Lumberyard instead of O3DE.

destination of hyperlink: https://docs.aws.amazon.com/lumberyard/latest/apireference/

**Comment by FiniteStateGit** [comment]
All links on page refer to O3DE documentation, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Confirmed that all links now correctly redirect to other pages in the O3DE User Guide.
