### ISSUE TITLE
[SITE][LOGO] Add Members

### ISSUE THREAD

**Issue by theheels** [o3de/o3de.org#1955]
## Describe the feature you'd like available on the website

Add the following members logos at the following tiers:

Premier member: Oppo
General member: Heroic Labs
Associate member: Kutztown University of Pennsylvania 

In addition, please change the word "Partner" is changed to "Member" where the member logos are listed on the site.

## Proposed implementation

N/A

## Available alternatives

N/A

## Supplements

[Logo folder](https://drive.google.com/drive/folders/1nqijv2hWC4o4hKmOlXaggwUYlu3sxxIc)

**Comment by uoduckswtd1** [comment]
@chanmosq @willihay @aFinchy 
Please add these member logos to the website.

**Comment by ShaunaGordon** [comment]
@Naomi-Wash Is this even applicable anymore?

**Comment by Naomi-Wash** [comment]
No longer applicable.
