### ISSUE TITLE
[SITE][FEATURE] Block merges on PRs that have a needs-edit label

### ISSUE THREAD

**Issue by willihay** [o3de/o3de.org#1957]
## Describe the feature you'd like available on the website

The o3de.org GH repo should block any attempt to merge a PR that has a needs-edit label. Contributors with merge privileges do not necessarily understand or look for the needs-edit label, and therefore can (and have) merge PRs that were still waiting for an editor to review.

## Proposed implementation

Add a rule for the repo that checks for the needs-edit label on a PR and blocks merging until this label has been cleared.

We should also include this in the documentation on the PR workflow in the Contributor Guide:
https://www.o3de.org/docs/contributing/to-docs/submit-a-pr/

**Comment by willihay** [comment]
This is a similar feature request to https://github.com/o3de/o3de.org/issues/1385

**Comment by chanmosq** [comment]
Closing this issue because it doesn't apply to o3de.org maintenance process
