### ISSUE TITLE
[Dead links]: Dynamic vegetation procedures: Multiple links redirect to a missing page

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#196]
Link: https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/

The following links lead to missing pages:
Creating a Vegetation Layer
(https://o3deorg.netlify.app/docs/user-guide/gems/vegetation/procedures/layer.md)
Using Gradients to Create Random Distribution
(https://o3deorg.netlify.app/docs/user-guide/gems/vegetation/procedures/gradient-random.md)
Adding Scale, Rotation, and Position Modifiers
(https://o3deorg.netlify.app/docs/user-guide/gems/vegetation/procedures/adding-modifiers.md)
Saving the Vegetation Area as a Slice
(https://o3deorg.netlify.app/docs/user-guide/deadlink)
Expanding Vegetation Coverage
(https://o3deorg.netlify.app/docs/user-guide/gems/vegetation/procedures/coverage.md)
Blocking Vegetation in Select Areas
(https://o3deorg.netlify.app/docs/user-guide/gems/vegetation/procedures/blockers.md)

**Comment by FiniteStateGit** [comment]
Page now found at: https://o3deorg.netlify.app/docs/user-guide/gems/reference/environment/vegetation/procedures/

**Comment by LB-RobertBaczkowski** [comment]
Issue still occurs as described on the new page.

**Comment by LB-RobertBaczkowski** [comment]
Confirmed that there are no dead links on the page, which can now be found here:

https://o3de.org/docs/user-guide/gems/reference/environment/vegetation/procedures/
