### ISSUE TITLE
[BROKEN LINK] - Vegetation Docs

### ISSUE THREAD

**Issue by dirk2947** [o3de/o3de.org#1965]
## Which page has the broken link?

https://www.o3de.org/docs/user-guide/gems/reference/environment/vegetation

## Which link was broken?

In the **Provides** section every link from

[Vegetation Asset List](https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/vegetation-asset-list)

till

[Vegetation Layer Spawner](https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/layer-spawner)

as well as a few links below in the **System components** section and **API Links**:

[Vegetation Area System](https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/vegetation-area-system-component)
[Vegetation Instance System](https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/vegetation-instance-system-component)
API: https://www.o3de.org/docs/api/gems//docs/user-guide/components/reference/vegetation/index.html
Source Code: [Vegetation Gem API Reference ](https://github.com/o3de/o3de/tree/development/Gems//docs/user-guide/components/reference/Vegetation/Code)

**Comment by FiniteStateGit** [comment]
@chanmosq The list of broken links from InSite:

https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/vegetation-asset-list
https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/vegetation-layer-debugger
https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/vegetation-layer-blocker-mesh
https://www.o3de.org/docs/user-guide/components/reference/vegetation-modifiers/vegetation-altitude-filter
https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/vegetation-asset-list
https://www.o3de.org/docs/user-guide/components/reference/vegetation-modifiers/vegetation-altitude-filter
https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/vegetation-layer-blocker
https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/vegetation-asset-weight-selector
https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/vegetation-asset-weight-selector
https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/vegetation-instance-system-component
https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/vegetation-layer-blender
https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/vegetation-layer-blender
https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/layer-spawner
https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/layer-spawner
https://github.com/o3de/o3de/tree/development/Gems/docs/user-guide/components/reference/Vegetation/Code
https://www.o3de.org/docs/api/gems/docs/user-guide/components/reference/vegetation/index.html
https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/layer-spawner
https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/layer-spawner
https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/vegetation-asset-list-combiner
https://www.o3de.org/docs/user-guide/components/reference/docs/user-guide/components/reference/vegetation/vegetation-area-system-component
