### ISSUE TITLE
[Obsolete Information] "Reflecting a Component for Serialization and Editing" chapter refers to Lumberyard documentation

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#198]
Link to page: https://o3deorg.netlify.app/docs/user-guide/components/development/reflection/

In Reflecting a Component for Serialization and Editing chapter in Components in O3DE User guide, hyperlinks refer to Lumberyard instead of O3DE.

hyperlinks:
SerializeContext Class Reference
Open 3D Engine C++ API Reference
EditContext Class Reference
 Open 3D Engine C++ API Reference
links:
https://docs.aws.amazon.com/lumberyard/latest/apireference/class_a_z_1_1_serialize_context.html
https://docs.aws.amazon.com/lumberyard/latest/apireference/
https://docs.aws.amazon.com/lumberyard/latest/apireference/class_a_z_1_1_edit_context.html
https://docs.aws.amazon.com/lumberyard/latest/apireference/

**Comment by FiniteStateGit** [comment]
Links now refer to O3DE documentation, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
All links redirect correctly, closing the issue.
