### ISSUE TITLE
Remove Gamepoch logo from Website[SITE][FEATURE] 

### ISSUE THREAD

**Issue by theheels** [o3de/o3de.org#1993]
## Describe the feature you'd like available on the website

Remove Gamepoch as a member from the website.

## Available alternatives

N/A

**Comment by lmbr-pip** [comment]
@OBWANDO - Can you confirm that GamePoch should be removed from the https://www.o3de.org/ page?

They are still shown as a member on https://o3d.foundation/

**Comment by uoduckswtd1** [comment]
Confirming that the Gamepoch logo should be removed from the https://www.o3de.org/ page. It is also being removed from the O3DF site.

**Comment by lmbr-pip** [comment]
Confirmed with O3DFoundation that logo should be removed. Has now been removed from O3DFoundation site.
