### ISSUE TITLE
[BROKEN LINK] Tools UI Page - O3DE UI Component Development Guidelines

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de.org#2000]
## Which page has the broken link?

https://www.o3de.org/docs/tools-ui/

## Which link was broken?

O3DE UI Component Development Guidelines
https://www.o3de.org/docs/tools-ui/ux-patterns/component-card/overview

## Know where it should go?

https://www.o3de.org/docs/tools-ui/ux-patterns/component-card/

(instead it goes to https://www.o3de.org/docs/tools-ui/ux-patterns/component-card/overview << which is broken)

**Comment by FiniteStateGit** [comment]
Issue has been fixed on https://www.o3de.org/docs/tools-ui/, link no longer points to overview page.
