### ISSUE TITLE
[BROKEN LINK] Tools UI Page - O3DE’s Message Guidelines

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de.org#2001]
## Which page has the broken link?

https://www.o3de.org/docs/tools-ui/

## Which link was broken?

O3DE’s Message Guidelines
https://www.o3de.org/docs/tools-ui/ux-patterns/error/overview

## Know where it should go?

https://www.o3de.org/docs/tools-ui/ux-patterns/error/

(instead it goes to https://www.o3de.org/docs/tools-ui/ux-patterns/error/overview << which is broken)

**Comment by FiniteStateGit** [comment]
Message guidelines now links correctly to https://www.o3de.org/docs/tools-ui/ux-patterns/error/.
