### ISSUE TITLE
[Formatting] Incorrect section enumeration

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#201]
Link to page: https://o3deorg.netlify.app/docs/user-guide/components/development/expose-animation/

In "Exposing Custom Components to Track View for Animation" section in "Components" in "O3DE User Guide" chapter, numbered bullet points are all set to "1" and displayed a line above the section's content.

**Comment by FiniteStateGit** [comment]
Hello @LB-RobertBaczkowski this issue should be resolved with #871 merged.  Thank you for raising the issue.

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue.
