### ISSUE TITLE
Update O3DE version on download page for 22.10

### ISSUE THREAD

**Issue by willihay** [o3de/o3de.org#2015]
## Describe the issue briefly

For release 22.10, update the O3DE version on the download page.

Also, consider mentioning experimental support for Ubuntu 22.04 LTS in the requirements list.

## Which page(s) / section(s) are affected?

https://www.o3de.org/download/

Source: `layouts/partials/download/*.*`

Note: on `getting-started-linux.html`, change "(Ubuntu 20.04 LTS)" to "(Ubuntu)" to remove version specific info that will get outdated.

## Does this work have an engineering dependency? What is it?

stabilization/2210 branch

**Comment by chanmosq** [comment]
Done
