### ISSUE TITLE
[Obsolete Information] "Components and EBuses: Best Practices" chapter refers to Lumberyard documentation

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#202]
Link to page: https://o3deorg.netlify.app/docs/user-guide/components/development/entity-system-pg-components-ebuses-best-practices/

In Components and EBuses: Best Practices chapter in Components in O3DE User guide, hyperlinks refer to Lumberyard instead of O3DE.

hyperlinks:
EBus API Reference
Open 3D Engine C++ API Reference
links:
https://docs.aws.amazon.com/lumberyard/latest/apireference/EBus.html
https://docs.aws.amazon.com/lumberyard/latest/apireference/

**Comment by FiniteStateGit** [comment]
All links on page now refer to O3DE documentation, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
All links are correct, closing the issue.
