### ISSUE TITLE
[SITE][FEATURE] Make o3de.org search bar automatically focus when opened

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de.org#2020]
## Describe the feature you'd like available on the website
Currently clicking the magnifying glass button in the top right corner of the https://www.o3de.org/ page opens up a search bar, but does not automatically focus it. This can sometimes lead the user to click the button, start typing and notice afterwards that the search bar itself has to be focused.

Image of the page/button for reference:
![o3deorgSearchBar](https://user-images.githubusercontent.com/86952082/194051284-1350e502-b449-4fa2-9972-ccf1074657ca.PNG)

## Proposed implementation
Make the magnifying glass button automatically focus the opened search bar.

## Available alternatives
Keep the search bar visible at all times.

**Comment by ShaunaGordon** [comment]
@Naomi-Wash Pretty sure this is a main site thing

**Comment by Naomi-Wash** [comment]
Closing this out as this issue was addressed with the O3DE website revamp.
