### ISSUE TITLE
[Obsolete Information] "Behavior Context in Depth" chapter refers to Lumberyard documentation

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#203]
Link to page: https://o3deorg.netlify.app/docs/user-guide/components/development/behavior-context/

In Behavior Context in Depth chapter in Components in O3DE User guide, hyperlinks refer to Lumberyard instead of O3DE.

hyperlinks:
BehaviorContext Class Reference
Open 3D Engine C++ API Reference
links:
https://docs.aws.amazon.com/lumberyard/latest/apireference/class_a_z_1_1_behavior_context.html
https://docs.aws.amazon.com/lumberyard/latest/apireference/

**Comment by FiniteStateGit** [comment]
Page no longer contains links to Lumberyard documentation, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
There are no links on the page, closing the issue.
