### ISSUE TITLE
[BUG][WEBSITE] Blogs missing next page button

### ISSUE THREAD

**Issue by aFinchy** [o3de/o3de.org#2031]
## Describe the bug

Community page is missing a "Next Page" Button to see the next page of blogs. 

https://www.o3de.org/community/
https://www.o3de.org/community/page/2/

## Reproduction steps

When you visit https://www.o3de.org/community/ you can see the current new blogs, but to see the recent ones, you need to go to URL and add "/page/2/"

## Other information

This would apply a fix till the new site is re-designed.

**Comment by chanmosq** [comment]
I think this will be handled by site redesign.
@uoduckswtd1 Can this be taken care of in the website redesign?

**Comment by uoduckswtd1** [comment]
Yes @chanmosq. This will be addressed with the site redesign.
