### ISSUE TITLE
[SITE][FEATURE] Remove Here Global Logo from website

### ISSUE THREAD

**Issue by theheels** [o3de/o3de.org#2044]
## Describe the feature you'd like available on the website

Remove Here Globals logo from the member section.

## Available alternatives

N/A

## Supplements

N/A

**Comment by uoduckswtd1** [comment]
@aFinchy @willihay 
Please remove the HERE Global logo from the website. Thanks!

**Comment by aFinchy** [comment]
On it. Will create a PR today or tomorrow for this.

**Comment by uoduckswtd1** [comment]
Awesome -- thanks @aFinchy.

**Comment by aFinchy** [comment]
I went to go do this today and sae it was already updated. Closing issue. 

If you believe it's a mistake, please re-open.
