### ISSUE TITLE
[Formatting]: Blocking Vegetation in Select Areas: Multiple images are inline with text

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#206]
Link: https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/blockers/

Multiple images on the page are placed inline with the text causing them to break page layout (most noticeable when resizing the page's width).

Mentioned images:
![Blocking1](https://user-images.githubusercontent.com/80751316/111785946-88c8f580-88bd-11eb-88ab-85214350853b.PNG)
![Blocking2](https://user-images.githubusercontent.com/80751316/111785948-89618c00-88bd-11eb-9de2-dcdc21704e7a.PNG)

**Comment by FiniteStateGit** [comment]
Hello @LB-RobertBaczkowski this issue should be resolved with #870 merged.  Thank you for raising the issue.

**Comment by FiniteStateGit** [comment]
Page now found at: https://o3deorg.netlify.app/docs/user-guide/gems/reference/environment/vegetation/procedures/blockers/.

**Comment by LB-RobertBaczkowski** [comment]
Fix confirmed.
