### ISSUE TITLE
[Formatting]: Creating a Vegetation Layer: Multiple images are inline with text

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#207]
Link: https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/layer/

Multiple images on the page are placed inline with the text causing them to break page layout (most noticeable when resizing the page's width).

Mentioned images:
![Layer1](https://user-images.githubusercontent.com/80751316/111786208-d47b9f00-88bd-11eb-9930-3bdd2440f62d.PNG)
![Layer2](https://user-images.githubusercontent.com/80751316/111786212-d5143580-88bd-11eb-8ae0-47e137a1a3e4.PNG)
![Layer3](https://user-images.githubusercontent.com/80751316/111786214-d5accc00-88bd-11eb-83c1-1149670f434f.PNG)
![Layer4](https://user-images.githubusercontent.com/80751316/111786216-d5accc00-88bd-11eb-927f-1a53c3590442.PNG)

**Comment by FiniteStateGit** [comment]
Hello @LB-RobertBaczkowski this issue should be resolved with #870 merged.  Thank you for raising the issue.

**Comment by LB-RobertBaczkowski** [comment]
The page has been moved to https://o3de.org/docs/user-guide/gems/reference/environment/vegetation/procedures/layer/. The issue no longer occurs.
