### ISSUE TITLE
[DOCS] There are no instructions how to build the Atom Sample Viewer Standalone on Linux

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de.org#2075]
## Describe the issue briefly
Documentation page for Atom Sample Viewer lacks information of specific commands how to build the AtomSampleViewerStandalone for Linux. It could be helpful for inexperienced user to have this information presented similarly to https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/ with tabs for different systems.

## Which page(s) / section(s) are affected?

* https://www.o3de.org/docs/atom-guide/setup-atom-projects/ - Setting up Atom Renderer

**Comment by chanmosq** [comment]
In addition, information about building Atom Sample Viewer now belongs in their repo's readme: https://github.com/o3de/o3de-atom-sampleviewer
