### ISSUE TITLE
[Formatting]: Creating Weight-Based Random Selection: Multiple images are inline with text

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#208]
Link: https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/selection-random/

Multiple images on the page are placed inline with the text causing them to break page layout (most noticeable when resizing the page's width).

Mentioned images:
![Weight1](https://user-images.githubusercontent.com/80751316/111786509-2b817400-88be-11eb-8e64-0c1fd07f7161.PNG)
![Weight2](https://user-images.githubusercontent.com/80751316/111786510-2c1a0a80-88be-11eb-888b-9c0f5a678178.PNG)
![Weight3](https://user-images.githubusercontent.com/80751316/111786513-2cb2a100-88be-11eb-9e14-7a4e36711d96.PNG)
![Weight4](https://user-images.githubusercontent.com/80751316/111786515-2cb2a100-88be-11eb-8147-e40f656b943d.PNG)

**Comment by FiniteStateGit** [comment]
Hello @LB-RobertBaczkowski this issue should be resolved with #870 merged.  Thank you for raising the issue.

**Comment by LB-RobertBaczkowski** [comment]
The page has been moved to https://o3de.org/docs/user-guide/gems/reference/environment/vegetation/procedures/selection-random/ . The issue no longer occurs.
