### ISSUE TITLE
[ISSUE][DOCS] "Update and existing project" has wrong --pp command instead of -pp

### ISSUE THREAD

**Issue by dirk2947** [o3de/o3de.org#2085]
## Describe the issue
https://docs.o3de.org/docs/user-guide/build/distributable-engine/#project-association
`scripts\o3de.bat register --pp W:\MyProject`
the command is wrong, it should be -pp instead of -- for the long version of the command.

## Impacted page(s)
https://docs.o3de.org/docs/user-guide/build/distributable-engine/#project-association
Is the only page I encountered the issue

**Comment by chanmosq** [comment]
The typo has been fixed. This is the correct URL for that page: https://www.o3de.org/docs/user-guide/build/distributable-engine/#project-association
