### ISSUE TITLE
Multiplayer Version Mismatch Detection

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de.org#2103]
## Describe the issue briefly
As a developer I'd like a multiplayer document about multiplayer version mismatch detection.
https://github.com/o3de/sig-network/blob/main/rfcs/rfc-net-20221020-2-netversion.md

## Which page(s) / section(s) are affected?
Multiplayer version mismatch detection should be a child of the multiplayer page: https://www.o3de.org/docs/user-guide/networking/multiplayer/

## Does this work have an engineering dependency? What is it?
No. There is already an RFC explaining the feature though.
https://github.com/o3de/sig-network/blob/main/rfcs/rfc-net-20221020-2-netversion.md

# Multiplayer Version Mismatch

## What is the relevance of this feature?
As a developer I want to know if two multiplayer endpoints are running the same multiplayer version.

For example, it's important for servers and clients to be running the same version of all the multiplayer components (components which communicate to each other over the network) since any mismatch could lead to unexpected behavior. The Multiplayer Versioning feature will warn users immediately upon attempting to connect two endpoints if there is a mismatch.

## How it works:
1. AzAutoGen creates a unique 64-bit hash value for each auto-component xml it digests.
    1. The 64-bit hash will be stored in the ComponentData class that’s passed to the global MultiplayerComponentRegistry
2. During application start up, as all the gems are registering their components with the MultiplayerComponentRegistry, the MultiplayerComponentRegistry will combine each component’s hash to create its own 64-bit system version hash.
3. The MultiplayerComponentRegistry’s version hash is sent from the connector (ie: client) to the acceptor (ie: server) as part of the MultiplayerPackets::Connect packet.
4. Server will compare the client’s version-hash with its own to make sure it matches
    1. If there's a multiplayer system version mismatch then...
        1. A version mismatch packet is exchanged containing the version hash of each individual auto-component in order that the server and client know exactly which components are out-of-date.
        2. Error logs will be reported
        3. An AZ::Event is broadcast (Developers can subscribe to the event via AZ::Interface<IMultiplayer>::Get()->AddVersionMismatchHandler).

## Relevant Console Variables (CVars)
**sv_versionMismatch_autoDisconnect**  *true | false* Determines if the server will automatically disconnect a client that has a different multiplayer version. It's recommended to keep this true; even minor differences between the version of a multiplayer component can cause unexpected behavior.

**sv_versionMismatch_sendManifestToClient**  *true | false* Determines if the server will send all its individual multiplayer component version information to the client when there's a mismatch? Upon receiving the information, the client will print the mismatch information to the game log. Provided for debugging during development, but you may want to mark false in release builds.

**bg_viewportConnectionStatus** *true | false* If true, the viewport connection status system will display an on-screen warning whenever a connection was made between two endpoints with differing versions. Warnings will also appear in logs even when this cvar is disabled, however the on-screen display makes the mismatch more apparent, so is helpful during development.

**Comment by chanmosq** [comment]
@AMZN-Gene It seems like you've gotten this partially documented already, assigning this to you. But let me know if we should change that.

**Comment by chanmosq** [comment]
This is blocked by getting `main` synced with `development`
