### ISSUE TITLE
[BUG][WEBSITE] Remove docs.o3de.org subdomain

### ISSUE THREAD

**Issue by FiniteStateGit** [o3de/o3de.org#2110]
## Describe the bug

The website is available through an unused subdomain docs.o3de.org, which may be interfering with google indexing.  

- We need to remove this subdomain from our DNS hierarchy.
- We should check for and remove any links that exist that use this subdomain (1 known link).

**Comment by OBWANDO** [comment]
Ticket filed with LF IT (LFIT-3420)
