### ISSUE TITLE
[ISSUE][DOCS] Selecting the 22.05 version of documentation sends the user to an empty page

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de.org#2118]
## Describe the issue

Selecting 22.05 from the Version dropdown menu sends the user to an empty page: https://2205--o3deorg.netlify.app/docs/welcome-guide/requirements/
It should be noted that choosing the development version will display the documentation page, but the version dropdown menu will not be present.
## Impacted page(s)

https://2205--o3deorg.netlify.app/docs/welcome-guide/requirements/ - 22.05 version documentation page
https://development--o3deorg.netlify.app/docs/welcome-guide/requirements/ - Development documentation page

## Expected experience

Documentation pages for all versions should display information correctly.

**Comment by willihay** [comment]
Fixed in the PR listed earlier.

**Comment by LB-TomaszSerwanski** [comment]
The issue verified as fixed.
