### ISSUE TITLE
As a Dev I want to Know How to Open 2 Different AssetProcessors at Once

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de.org#2135]
## Describe the issue briefly
I wanted to open the Editor and Game Launchers for 2 different projects; but it wasn't possible because the 2nd AssetProcessor would open and then fail with an error about needing to change the port. It took a long time to figure out how to get this working.

In order to get 2 asset processors running, each one needs to connect to a different port. You can achieve this by creating a new setreg or using an existing set reg and defining a different port.

```
{
    "Amazon": {
        "AzCore": {
            "Bootstrap": {
		    "remote_port": 45642
            }
        }
    }
}
```

![image](https://user-images.githubusercontent.com/32776221/204678561-3bb98daa-fa46-46a3-b155-438bc132c5e3.png)

## Which page(s) / section(s) are affected?
Not sure,  maybe settings or configuration?
https://www.o3de.org/docs/user-guide/assets/asset-processor/configuration/
https://www.o3de.org/docs/user-guide/assets/asset-processor/settings/
![image](https://user-images.githubusercontent.com/32776221/204680460-233e23dc-7318-4855-8e6f-342156bff2de.png)

## Does this work have an engineering dependency? What is it?
N/A

**Comment by lmbr-pip** [comment]
Need to add this to https://development--o3deorg.netlify.app/docs/user-guide/assets/asset-processor/settings/ or similar documentation
