### ISSUE TITLE
Google search returns outdated docs links

### ISSUE THREAD

**Issue by willihay** [o3de/o3de.org#2161]
## Which page has the broken link?

The top result from a search for "o3de network serializer" returns a link to https://www.o3de.org/docs/user-guide/networking/serializers/ which has been moved to a new location. (Fortunately we have a redirect in place.)

The top result from a search for "o3de reflection probe" returns a link to an **API reference** that has been removed: https://www.o3de.org/docs/api/gems/atom/class_a_z_1_1_render_1_1_reflection_probe_feature_processor

**Comment by willihay** [comment]
@AMZN-alexpete Do you know how to force Google to do a reindex of our website?

**Comment by AMZN-alexpete** [comment]
I believe the Google search tools give you that option https://search.google.com/

**Comment by chanmosq** [comment]
The site may have automatically reindexed already. The above searches refer to the correct docs.
