### ISSUE TITLE
[DOCS] [BJDS] Update to Banner and New files for BJDS Logo

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de.org#2175]
## Describe the issue briefly

I would like to update the Blue Jay Design System (BJDS) section of the website with a new banner and new ZIP file of logo assets for it.

Check list of things I want updated:

1. Replace banner with the one attached below for the Branding Guidelines Page.
2. Replace banner on the Landing page for Tools-UI with one attached below.
3. Replace zip file with the one attached below on the branding guidelines page.
4. Update all instances of the word "BlueJay Design System" with "Blue Jay Design System" (it has a space between Blue and Jay now) It appears four times listed in the section below.

## Which page(s) / section(s) are affected?

https://www.o3de.org/docs/tools-ui/branding-guidelines/#bluejay-design-system-logo-pack
(heading, blurb and name of zip file)
https://www.o3de.org/docs/tools-ui/
(Intro Paragraph)

## Does this work have an engineering dependency? What is it?

No.

**Comment by amzn-leenguy** [comment]
![bjds-banner](https://user-images.githubusercontent.com/82846749/208211224-dbd9c757-aeb9-4e9b-a200-fcb44ec4d654.png)

**Comment by amzn-leenguy** [comment]
[BlueJay Design System Logo Pack.zip](https://github.com/o3de/o3de.org/files/10250210/BlueJay.Design.System.Logo.Pack.zip)

**Comment by amzn-leenguy** [comment]
[Blue Jay Design System Logo Pack.zip](https://github.com/o3de/o3de.org/files/10250213/Blue.Jay.Design.System.Logo.Pack.zip)

**Comment by amzn-leenguy** [comment]
![bjds-front-banner](https://user-images.githubusercontent.com/82846749/208212570-01888565-852a-4dd2-8d21-f1eda538fbe1.jpg)
![bjds-front-banner2](https://user-images.githubusercontent.com/82846749/208212571-06a4ccaa-f527-4d14-a989-195128c4a7a6.jpg)

Looking for feedback on which banner i should replace the front page with. Would love opinions on either one.

**Comment by chanmosq** [comment]
I also updated all instance of "BlueJay" to "Blue Jay" in other pages, as well as the blog post introducing BJDS. I'm not sure what the rules around updates to the blog post for a situation like this, so if I must undo those changes let me know! @aFinchy Am I allowed to update the logo name in the blog post even after it's been released?

**Comment by amzn-leenguy** [comment]
> I also updated all instance of "BlueJay" to "Blue Jay" in other pages, as well as the blog post introducing BJDS. I'm not sure what the rules around updates to the blog post for a situation like this, so if I must undo those changes let me know! @aFinchy Am I allowed to update the logo name in the blog post even after it's been released?

Fantastic. Thank you! Great approach. I've left a few comments, but mostly flawless :)
