### ISSUE TITLE
[BROKEN LINK] Tools UI Page

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de.org#2181]
## Which page has the broken link?

https://www.o3de.org/docs/tools-ui/

## Which link was broken?
1. "O3DE UI Component Development Guidelines" 
2. "O3DE’s Message Guidelines"

## Know where it should go?

1. https://www.o3de.org/docs/tools-ui/ux-patterns/component-card/
2. https://www.o3de.org/docs/tools-ui/ux-patterns/error/

**Comment by amzn-leenguy** [comment]
The issue in the URL is that it has /overview in it, but the correct link should not have the word /overview in it

**Comment by FiniteStateGit** [comment]
Issues have been fixed on https://www.o3de.org/docs/tools-ui/, links no longer point to overview pages.
