### ISSUE TITLE
[Obsolete materials]: Configuring Image Processing: Page contains images about Lumberyard

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#223]
Link to page: https://o3deorg.netlify.app/docs/user-guide/assets/pipeline/configuring-image-processing/

The picture on the page includes information about Lumberyard instead of O3DE.

![image](https://user-images.githubusercontent.com/80751316/111789378-5f11cd80-88c1-11eb-92c7-ce659bad2b51.png)

**Comment by sptramer** [comment]
Page removed.
