### ISSUE TITLE
[DOCS] Missing Legacy game samples

### ISSUE THREAD

**Issue by Anthony-Gaudino** [o3de/o3de.org#2232]
## Describe the issue briefly

I remember seeing before the Legacy Game SDK and other examples available for download at orde.org, but I can't find them anymore.

The Legacy SDK is a game sample. It was also available in Lumberyard website.
<img width="1315" alt="Screenshot 2023-02-07 at 06 50 06" src="https://user-images.githubusercontent.com/2439728/217169560-25b2540c-3197-472a-8501-24cb878138f0.png">

There were other projects available on the Lumberyard webpage too.

## Which page(s) / section(s) are affected?

https://www.o3de.org/docs/learning-guide/samples/

## Does this work have an engineering dependency? What is it?

No

**Comment by chanmosq** [comment]
There is no Legacy Game Sample in o3de.org. You can find numerous sample games in the `o3de` org, such as [NewsPaperDeliveryGame](https://github.com/o3de/NewspaperDeliveryGame) and [MultiplayerSampleGame](https://github.com/o3de/o3de-multiplayersample). These projects may have some of the features you're looking for samples for
