### ISSUE TITLE
[DOCS] In the future, add a developers showcase (AAA game studios/small indies/solo indie) made with O3DE

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de.org#2250]
## Describe the issue briefly
Main page add showcases and through link youtube(video)/official site/game links other, only projects made with **Open 3D Engine (O3DE)**

![image](https://user-images.githubusercontent.com/17591539/219305674-2c011aa9-5439-4f13-ba11-53ba14602607.png)

e.g. sample site Godot showcase

![image](https://user-images.githubusercontent.com/17591539/219304902-b7e7e8b1-22bb-4c78-ad25-a17dd93111fc.png)

**Comment by chanmosq** [comment]
A showcase page is in the upcoming website plans!
Here is a preview of the plan with some placeholder images. The **Go to showcase** button will lead to a new Showcase page. 
<img width="611" alt="Screenshot_2023-02-22_at_6 16 47_PM" src="https://user-images.githubusercontent.com/75444793/221012939-04e84a26-8137-46bc-8238-e8bfd4a48578.png">

The complete O3DE Website plan is up on Figma. Here's a link to the showcase page specifically: https://www.figma.com/file/LCRhOYaja2UqTPlxon5O0N/O3DE_Website?node-id=2579%3A13325&t=tptXif1wc7gwdxMI-0

**Comment by Naomi-Wash** [comment]
We've launched this page in the website revamp: https://o3de.org/showcase/
