### ISSUE TITLE
[BROKEN LINK]

### ISSUE THREAD

**Issue by aurodev** [o3de/o3de.org#2251]
## Which page has the broken link?
https://docs.o3de.org/docs/user-guide/platforms/android/generating_android_project_windows/

## Which link was broken?
https://docs.o3de.org/docs/user-guide/platforms/android/generating_android_project_windows/

https://docs.o3de.org/docs/user-guide/platforms/android/generating_android_project_windows/

**Comment by chanmosq** [comment]
When resolving this issue, the correct link should be o3de.org, not docs.o3de.org

**Comment by chanmosq** [comment]
The correct URL should be https://o3de.org/docs/user-guide/platforms/android/generating_android_project_windows/. 

@aurodev Where are you seeing the broken links? 

We're aware of a current issue where Google search results return broken link docs from docs.o3de.org, which is a deprecated address now

**Comment by chanmosq** [comment]
Closing this issue in favor of https://github.com/o3de/o3de.org/issues/2161

These broken docs links are referring to an older URL address
