### ISSUE TITLE
[ISSUE][DOCS] Atom Renderer Features page contains broken links and spelling error

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de.org#2253]
## Describe the issue
There are issues regarding broken links and spelling error on the [Atom Renderer Features](https://www.o3de.org/docs/atom-guide/features/) documentation page:
* [Lighting section](https://www.o3de.org/docs/atom-guide/features/#lighting) - there are broken links:
Diffuse Probe Grid - https://www.o3de.org/docs/api/gems/Atom/class_a_z_1_1_render_1_1_diffuse_probe_grid_feature_processor_interface.html
Reflection Probes - https://www.o3de.org/docs/api/gems/Atom/class_a_z_1_1_render_1_1_reflection_probe_feature_processor.html

* [Meshes section](https://www.o3de.org/docs/atom-guide/features/#meshes) -
`Skinned Mesh Feature Processer API` - should be `Skinned Mesh Feature Processor API`

Please note that this issue should be considered as a Major.
## Impacted page(s)

[Atom Renderer Features](https://www.o3de.org/docs/atom-guide/features/)

## Expected experience

Documentation contains no errors.

**Comment by ShaunaGordon** [comment]
This was fixed by #2311
