### ISSUE TITLE
[Obsolete Information]: O3DE User guide: Engine programmer’s reference refers to 1.24 version of O3DE, which does not exist

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#229]
Link to page: https://o3deorg.netlify.app/docs/user-guide/engine/

In Programming with O3DE chapter there is reference to O3DE version 1.24 , which does not exist. (legacy of Lumberyard)

**Comment by FiniteStateGit** [comment]
The chapter is now titled 'Introduction to O3DE programming'.  A search of the source code produced no result for 1.24 in the context of versioning.  @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
The obsolete information is not included on the subpages for "Introduction to O3DE programming." Closing the issue.
