### ISSUE TITLE
[Obsolete Information] "Working with the Event Bus (EBus) system" chapter refers to Lumberyard documentation

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#230]
Link to page: https://o3deorg.netlify.app/docs/user-guide/engine/ebus/

In Working with the Event Bus (EBus) system Engine programmer’s reference in O3DE User guide, hyperlinks refer to Lumberyard instead of O3DE.

Hyperlinks:
EBus API Reference
Open 3D Engine C++ API Reference
https://docs.aws.amazon.com/lumberyard/latest/apireference/struct_a_z_1_1_e_bus_traits.html
https://docs.aws.amazon.com/lumberyard/latest/apireference/namespace_a_z.html#abd62fbe2e48ab376e0cce1a0ff0ea873adb4f7ff88b3cc15c6c585c284600a3dd
https://docs.aws.amazon.com/lumberyard/latest/apireference/class_a_z_1_1_entity_id.html
https://docs.aws.amazon.com/lumberyard/latest/apireference/struct_a_z_1_1_bus_internal_1_1_e_bus_broadcaster.html#aa622f2e4e0b27e0554a8d450d1af5385
https://docs.aws.amazon.com/lumberyard/latest/apireference/struct_a_z_1_1_bus_internal_1_1_e_bus_eventer.html#aed9aca9df1d88a51f34838100787c8cd
https://docs.aws.amazon.com/lumberyard/latest/apireference/struct_a_z_1_1_bus_internal_1_1_e_bus_broadcaster.html#a4d3c8f6502a4358a36c763356c47063f
https://docs.aws.amazon.com/lumberyard/latest/apireference/struct_a_z_1_1_bus_internal_1_1_e_bus_eventer.html#aee2aef13279c7fab83d9229f26cace1a
https://docs.aws.amazon.com/lumberyard/latest/apireference/struct_a_z_1_1_bus_internal_1_1_e_bus_broadcaster.html#ad0588a3dab7547dccdc516377e90c4a4
https://docs.aws.amazon.com/lumberyard/latest/apireference/struct_a_z_1_1_bus_internal_1_1_e_bus_eventer.html#a930172ceeea2692b0eb5c6b85d83d53d
https://docs.aws.amazon.com/lumberyard/latest/apireference/class_a_z_1_1_e_bus.html#a95b9e7e9c5b00de0356853b8be5c3649
https://docs.aws.amazon.com/lumberyard/latest/apireference/class_a_z_1_1_e_bus.html#a766031c060a297361903f0bbba31081b
https://docs.aws.amazon.com/lumberyard/latest/apireference/namespace_a_z.html#abd62fbe2e48ab376e0cce1a0ff0ea873a66ba162102bbf6ae31b522aec561735e
Links:
https://docs.aws.amazon.com/lumberyard/latest/apireference/EBus.html
https://docs.aws.amazon.com/lumberyard/latest/apireference/
https://docs.aws.amazon.com/lumberyard/latest/apireference/struct_a_z_1_1_e_bus_traits.html
https://docs.aws.amazon.com/lumberyard/latest/apireference/namespace_a_z.html#abd62fbe2e48ab376e0cce1a0ff0ea873adb4f7ff88b3cc15c6c585c284600a3dd
https://docs.aws.amazon.com/lumberyard/latest/apireference/class_a_z_1_1_entity_id.html
https://docs.aws.amazon.com/lumberyard/latest/apireference/struct_a_z_1_1_bus_internal_1_1_e_bus_broadcaster.html#aa622f2e4e0b27e0554a8d450d1af5385
https://docs.aws.amazon.com/lumberyard/latest/apireference/struct_a_z_1_1_bus_internal_1_1_e_bus_eventer.html#aed9aca9df1d88a51f34838100787c8cd
https://docs.aws.amazon.com/lumberyard/latest/apireference/struct_a_z_1_1_bus_internal_1_1_e_bus_broadcaster.html#a4d3c8f6502a4358a36c763356c47063f
https://docs.aws.amazon.com/lumberyard/latest/apireference/struct_a_z_1_1_bus_internal_1_1_e_bus_eventer.html#aee2aef13279c7fab83d9229f26cace1a
https://docs.aws.amazon.com/lumberyard/latest/apireference/struct_a_z_1_1_bus_internal_1_1_e_bus_broadcaster.html#ad0588a3dab7547dccdc516377e90c4a4
https://docs.aws.amazon.com/lumberyard/latest/apireference/struct_a_z_1_1_bus_internal_1_1_e_bus_eventer.html#a930172ceeea2692b0eb5c6b85d83d53d
https://docs.aws.amazon.com/lumberyard/latest/apireference/class_a_z_1_1_e_bus.html#a95b9e7e9c5b00de0356853b8be5c3649
https://docs.aws.amazon.com/lumberyard/latest/apireference/class_a_z_1_1_e_bus.html#a766031c060a297361903f0bbba31081b
https://docs.aws.amazon.com/lumberyard/latest/apireference/namespace_a_z.html#abd62fbe2e48ab376e0cce1a0ff0ea873a66ba162102bbf6ae31b522aec561735e

**Comment by FiniteStateGit** [comment]
Page now links to O3DE documentation, @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
No links on the page redirect to incorrect sites. Closing the issue.
