### ISSUE TITLE
[Obsolete Information]: O3DE User guide: Script Canvas Editor Shortcuts chapter refers to Lumberyard forum

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#237]
Link to page: https://o3deorg.netlify.app/docs/user-guide/scripting/script-canvas/shortcuts/

In Script Canvas Editor Shortcuts chapter there is hyper link which refers to the Lumberyard forum.

Hyperlink: forums
Link: https://forums.awsgametech.com/

**Comment by sptramer** [comment]
Page has been deleted.
