### ISSUE TITLE
GameLift Docs Missing VC_Redist Install Step

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de.org#2370]
In order to run O3DE server on GameLift with Windows 2012 servers, GameLift fleet must first install Microsoft C/C++ runtime libraries. 
![image](https://user-images.githubusercontent.com/32776221/233437271-59d48bf4-8f68-4fc8-b784-a832c69df56a.png)

## Impacted page(s)
https://www.o3de.org/docs/user-guide/gems/reference/aws/aws-gamelift/build-packaging-for-windows/

## Expected experience
O3DE project are built using Microsoft C++. As such, GameLift fleets must install Microsoft C and C++ (MSVC) runtime libraries before starting ServerLauncher otherwise the app will crash. 

Be sure the server package contains an install.bat and VC_redist.x64.exe. GameLift automatically runs install.bat upon launching a fleet; its only role is to run _VC_redist.x64.exe_
_install.bat_
```sh
VC_redist.x64.exe /q  
```

Note: This is only required when using WIndow 2012 Servers. If using Windows 2016 Server you must NOT install VC_redist.x64.exe as doing causes issues.

**Comment by lmbr-pip** [comment]
This is called out in the docs: https://www.o3de.org/docs/user-guide/gems/reference/aws/aws-gamelift/build-packaging-for-windows/

"Create a build install script called install.bat in the package base folder and add the following content to the file. For more information about the build install script, please check Upload a custom server build to GameLift

VC_redist.x64.exe /q
"

This sounds more like a docs search issue ;)
