### ISSUE TITLE
[Formatting] Incorrect section enumeration

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#239]
Link to page: https://o3deorg.netlify.app/docs/user-guide/visualization/animation/use-parameters-to-adjust-animation-during-runtime/

In "To adjust the animation during runtime" section in "Using Parameters to Adjust the Animation During Runtime" in "O3DE User Guide" chapter, numbered bullet points after point "5" are set to point "3" again.

**Comment by FiniteStateGit** [comment]
Hello @LB-RobertBaczkowski this issue should be resolved with #872 merged.  Thank you for raising the issue.

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue.
