### ISSUE TITLE
[BUG][WEBSITE] o3de.org is showing as simple html

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de.org#2429]
## Describe the bug

O3DE.org is currently showing in html. 

## Reproduction steps

    1. Go to o3de.org
    2. Notice there is no dynamic content, only html links

## Expected behavior

Website has dynamic content, menus, buttons, etc. 

## Screenshots

![Screenshot_20230610-134155~2.png](https://github.com/o3de/o3de.org/assets/58790905/ea2f2060-ac85-49fa-99c4-93060ee6e186)

**Comment by gotwig** [comment]
Issue seems to be that browser is trying to load css from this path:
https://www.o3de.org/docs/css/style.721521edc80f286b64e0b12938f774a15af9242ab4532ae8182b5eb9dd12dd48.css

HOWEVER it should load it from this path I believe:
https://www.o3de.org/css/style.721521edc80f286b64e0b12938f774a15af9242ab4532ae8182b5eb9dd12dd48.css
