### ISSUE TITLE
[BROKEN LINK] Windows download link points to Linux download page

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de.org#2473]
## Which page has the broken link?

https://o3de.org/download/

If you click on the "Windows" tab again the link is fixed.  I think there is a logic error when first loading the page - maybe it detects your OS is Windows and updates the tab but not the download URL?

## Which link was broken?

"Download Package" button link points to https://o3debinaries.org/download/linux.html even though active download tab is "Windows"

## Know where it should go?

https://o3debinaries.org/download/windows.html

**Comment by ShaunaGordon** [comment]
Reported as resolved through previous work.
