### ISSUE TITLE
AL2023 Setup Required for Building (and Running) an O3DE Project

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de.org#2484]
1. I want to know the system requirements for building O3DE engine on Amazon Linux 2023.

```
sudo dnf install cmake    						
sudo dnf install clang    						
sudo dnf install mesa-libGLU					
sudo dnf install libxcb-devel					
sudo dnf install libxkbcommon-devel		
sudo dnf install libxkbcommon-x11-devel
sudo dnf install zlib-devel
sudo dnf install libunwind-devel
sudo dnf install libzstd-devel
sudo dnf install pcre2-devel             
sudo dnf install fontconfig-devel               
sudo dnf install mesa-libGL-devel
sudo dnf install git
sudo dnf install git-lfs
sudo dnf install binutils-devel # Only for PopcornFx
sudo dnf install ninja-build
```

3. I also want to know the runtime requirement for an O3DE project, for example, if I want to run my game server on AL2023, which libraries to I need to install?

## Which page(s) / section(s) are affected?
https://docs.o3de.org/docs/welcome-guide/requirements/
Add another tab called "Amazon Linux 2023" next to the "20.04 LTS" and "22.04 LTS" Tabs

## Does this work have an engineering dependency? What is it?
Yes. O3DE will need to officially support AL2023 and add it to Jenkins builds?

**Comment by spham-amzn** [comment]
Ubuntu 22.04 + 24.04 remains the only 'official' supported Linux distributions (per sig-platform). Adding official support for other distros will require an approval from sig-platform and sig-build, and would require setting up additional AR jobs for that platform. For now, additional distro support can be unofficially supported through community contributions as long as it does not break ubuntu.

**Comment by spham-amzn** [comment]
If additional platform support is desired for official support, please create an RFC for it and attend the sig-platform weekly meeting to discuss the issue and start the process of getting it on the roadmap. (see https://lists.o3de.org/g/o3de-calendar/calendar for the schedule)
