### ISSUE TITLE
[BUG][WEBSITE] Spotify logo shows YouTube tooltip

### ISSUE THREAD

**Issue by Fergal-C** [o3de/o3de.org#2501]
## Describe the bug
Hovering over the Spotify logo, in the "Follow" section, at the bottom of o3de.org page, displays a YouTube tooltip.

Steps to reproduce 

    1. Scroll to the bottom of the o3de.org page
    2. Hover over the Spotify logo in the "Follow" section
    3. View the tooltip
   

## Expected behavior
Spotify tooltip to appear.

## Screenshots

![SpotifyYouTube](https://github.com/o3de/o3de.org/assets/20088633/cf508a8b-3d19-4448-bc27-2a2d23c69d42)

## Other information

* **OS**: NAME, VERSION
 Windows 10 PC

* **Browser**: NAME, VERSION
Microsoft Edge 118.0.2088.69 (Official build) (64-bit)

**Comment by PunugupatiSaikumar** [comment]
Hi, I would like to work on this, can you please accept my pull request?
Thank You.

**Comment by ShaunaGordon** [comment]
@Naomi-Wash main site

**Comment by Naomi-Wash** [comment]
Verified that this is no longer a bug.
