### ISSUE TITLE
[BROKEN LINK] https://www.docs.o3de.org/docs/learning-guide/tutorials/first-project/

### ISSUE THREAD

**Issue by Tortenschachtel** [o3de/o3de.org#2563]
## Which page has the broken link?

https://www.docs.o3de.org/docs/welcome-guide/
Section "Get Started Tutorials", first tutorial

## Which link was broken?

Title: "Create your first game: Pong!"
Link: https://www.docs.o3de.org/docs/learning-guide/tutorials/first-project/

**Comment by ShaunaGordon** [comment]
Duplicate of #2560
