### ISSUE TITLE
[BROKEN LINK]

### ISSUE THREAD

**Issue by idpokute** [o3de/o3de.org#2608]
## Which page has the broken link?

https://docs.o3de.org/docs/learning-guide/tutorials/

## Which link was broken?

`Looking to get started?` section has a link to 
[Create your first O3DE game: Pong](https://docs.o3de.org/docs/learning-guide/tutorials/first-project/)

which redirects to 404 page now

## Know where it should go?

I guess this is the right page: https://docs.o3de.org/docs/learning-guide/samples/follow-along/pong/

**Comment by ShaunaGordon** [comment]
Duplicate of #2560
