### ISSUE TITLE
[BROKEN LINK]

### ISSUE THREAD

**Issue by breezzz** [o3de/o3de.org#2615]
## Which page has the broken link?

https://docs.o3de.org/docs/welcome-guide/

## Which link was broken?

`<a href="/docs/learning-guide/tutorials/first-project/">Create your first game: Pong!</a>`

https://docs.o3de.org/docs/learning-guide/tutorials/first-project/

**Comment by gustavokennedy** [comment]
Hello @breezzz! I can make any necessary adjustments.

We just need to know where it should be redirected to?

Will it be here? https://github.com/o3de/o3de.org/blob/development/content/docs/learning-guide/samples/follow-along/_index.md

**Comment by breezzz** [comment]
@gustavokennedy Good job! Thank you!

**Comment by ShaunaGordon** [comment]
Fixed by #2629
