### ISSUE TITLE
[BUG][WEBSITE] https://www.youtube.com/@Open3DEngine/videos

### ISSUE THREAD

**Issue by Hotshot5000** [o3de/o3de.org#2619]
## Describe the bug

At the top you can see 23.10 release but now we have a newer release 24.09. It's best if users see the project as active and constantly updated.

```[tasklist]
### Tasks
```

**Comment by Naomi-Wash** [comment]
@Hotshot5000 Thank you for submitting this GI. The Youtube banner has been changed.
