### ISSUE TITLE
[SITE][FEATURE] Dark mode for user guide/tutorials/docs webpages

### ISSUE THREAD

**Issue by Hotshot5000** [o3de/o3de.org#2620]
## Describe the feature you'd like available on the website

Dark mode for docs pages and api reference (doxygen stuff) would be appreciated as a lot of devs use dark mode for their IDEs and desktops and going back and forth between code and docs page is jarring in the middle of the night.

**Comment by ShaunaGordon** [comment]
Duplicate of #983
