### ISSUE TITLE
[Obsolete Information]: O3DE User guide: Configure O3DE projects for Android refers to the Lumberyard documentation

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#266]
Link to page: https://o3deorg.netlify.app/docs/user-guide/platforms/android/configure-project/

In Programming with O3DE chapter there is a reference to the Lumberyard documentation.
Hyperlink: AWS Device Farm
Link: https://docs.aws.amazon.com/devicefarm/latest/developerguide

**Comment by FiniteStateGit** [comment]
Android is no longer linked at https://o3deorg.netlify.app/docs/user-guide/platforms/ which is addressed in Issue https://github.com/o3de/o3de.org/issues/481 @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
