### ISSUE TITLE
[Obsolete Information]: O3DE User guide: O3DE iOS support chapter refers to Lumberyard documentation

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#268]
Link to page: https://o3deorg.netlify.app/docs/user-guide/scripting/script-canvas/shortcuts/

In O3DE iOS support chapter there is a hyperlink which refers to the Lumberyard documentation.

Hyperlink: O3DE Mac Support Files
Link: https://aws.amazon.com/lumberyard/downloads/

**Comment by FiniteStateGit** [comment]
Android is no longer linked at https://o3deorg.netlify.app/docs/user-guide/platforms/ which is addressed in Issue https://github.com/o3de/o3de.org/issues/478 @LB-RobertBaczkowski could this be closed?

The page linked in the issue does have a reference to the AWS forums, which is addressed in Issue https://github.com/o3de/o3de.org/issues/237

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
