### ISSUE TITLE
[Obsolete Information]: O3DE User guide: Quick Start: Running the Samples Project on iOS Devices chapter refers to Lumberyard documentation

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#269]
Link to page: https://o3deorg.netlify.app/docs/user-guide/platforms/ios/quick-start/

In Quick Start: Running the Samples Project on iOS Devices  chapter there is image which refers to Lumberyard.
![image](https://user-images.githubusercontent.com/80751316/112003704-6d5e2480-8b21-11eb-9b7a-39e3207506ed.png)

**Comment by FiniteStateGit** [comment]
iOS is no longer linked at https://o3deorg.netlify.app/docs/user-guide/platforms/ which is addressed in Issue #478 @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
The page no longer exists. Closing the issue as described.
