### ISSUE TITLE
[Obsolete Information]: O3DE User guide: Creating a Release App chapter refers to Lumberyard documentation

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#270]
Link to page: https://o3deorg.netlify.app/docs/user-guide/platforms/ios/creating-release-app/

In Creating a Release App chapter there is hyperlink which refers to Lumberyard.

Hyperlink: O3DE Logos and Branding Guidelines
Link: https://aws.amazon.com/lumberyard/support/

**Comment by FiniteStateGit** [comment]
iOS is no longer linked at https://o3deorg.netlify.app/docs/user-guide/platforms/ which is addressed in Issue #478 @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
The page no longer exists, closing the issue as described.
