### ISSUE TITLE
[Obsolete Information]: O3DE User guide: Create macOS projects in O3DE chapter refers to Lumberyard documentation

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#271]
Link to page: https://o3deorg.netlify.app/docs/user-guide/platforms/macos/

In Create macOS projects in O3DE chapter there is a hyperlink which refers to Lumberyard.

Hyperlink: Xcode 11
Link: https://developer.apple.com/xcode/download/

**Comment by FiniteStateGit** [comment]
macOS is no longer linked at https://o3deorg.netlify.app/docs/user-guide/platforms/ which is addressed in Issue #478 @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
The page no longer exists, closing the issue as described.
