### ISSUE TITLE
[Formatting]: Expanding Vegetation Coverage: Multiple images are inline with text

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#273]
Link: https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/coverage/

Multiple images on the page are placed inline with the text causing them to break page layout (most noticeable when resizing the page's width).

Mentioned images:
![Expand1](https://user-images.githubusercontent.com/80751316/112113698-6eda2c00-8bb7-11eb-99db-72ac53784836.PNG)

**Comment by FiniteStateGit** [comment]
Hello @LB-RobertBaczkowski this issue should be resolved with #870 merged.  Thank you for raising the issue.

**Comment by LB-RobertBaczkowski** [comment]
The page has been moved to https://o3de.org/docs/user-guide/gems/reference/environment/vegetation/procedures/coverage/ . The issue no longer occurs.
