### ISSUE TITLE
[Obsolete materials]: O3DE User guide: Visibility Gem: Page contains images about Lumberyard

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#278]
Link to page: https://o3deorg.netlify.app/docs/user-guide/gems/reference/visibility/

The picture on the page includes information about Lumberyard (Setup Assistant) instead of O3DE. Setup Assistant has been deprecated on O3DE.
![image](https://user-images.githubusercontent.com/80751316/112116244-5e778080-8bba-11eb-8cbd-02e8c93325c2.png)

**Comment by FiniteStateGit** [comment]
The Visibility Gem is no longer linked from https://o3deorg.netlify.app/docs/user-guide/gems/reference/ @LB-RobertBaczkowski could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
The page for the gem no longer exists and is not linked on the Reference page. Closing the issue.
