### ISSUE TITLE
[Obsolete materials]: O3DE User guide: Script Canvas Gem: Page contains images about Lumberyard

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#279]
Link to page: https://o3deorg.netlify.app/docs/user-guide/gems/reference/script-canvas/

The picture on the page includes information about Lumberyard (Setup Assistant) instead of O3DE. Setup Assistant has been deprecated on O3DE.
![image](https://user-images.githubusercontent.com/80751316/112117780-004b9d00-8bbc-11eb-8ebb-c5888a084e88.png)

**Comment by FiniteStateGit** [comment]
Page now located at: https://o3deorg.netlify.app/docs/user-guide/gems/reference/script/script-canvas/ and no longer includes images with reference to Lumberyard.
