### ISSUE TITLE
[Obsolete materials]: O3DE User guide: Scene Processing Gem: Page contains images about Lumberyard

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#280]
Link to page: https://o3deorg.netlify.app/docs/user-guide/gems/reference/scene-processing/

The picture on the page includes information about Lumberyard (Setup Assistant) instead of O3DE. Setup Assistant has been deprecated on O3DE.
![image](https://user-images.githubusercontent.com/80751316/112117935-2a9d5a80-8bbc-11eb-9217-f2e20823a84e.png)

**Comment by FiniteStateGit** [comment]
Page is now found at https://o3deorg.netlify.app/docs/user-guide/gems/reference/assets/scene-processing/ and no longer includes references to the Setup Assistance. @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
