### ISSUE TITLE
[Obsolete materials]: O3DE User guide: PhysX Debug: Page contains images about Lumberyard

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#282]
Link to page: https://o3deorg.netlify.app/docs/user-guide/gems/reference/physx-debug/

The picture on the page includes information about Lumberyard (Setup Assistant) instead of O3DE. Setup Assistant has been deprecated on O3DE.
![image](https://user-images.githubusercontent.com/80751316/112119989-25d9a600-8bbe-11eb-898d-6014571cea3a.png)

**Comment by FiniteStateGit** [comment]
Page now found at https://o3deorg.netlify.app/docs/user-guide/gems/reference/physics/nvidia/physx-debug/ and no longer includes references to the Setup Assistant. @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
