### ISSUE TITLE
[Obsolete materials]: O3DE User guide: PhysX Characters: Page contains images about Lumberyard

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#283]
Link to page: https://o3deorg.netlify.app/docs/user-guide/gems/reference/physx-characters/

The picture on the page includes information about Lumberyard (Setup Assistant) instead of O3DE. Setup Assistant has been deprecated on O3DE.
![image](https://user-images.githubusercontent.com/80751316/112120354-6afdd800-8bbe-11eb-90f5-ed60d45300f6.png)

**Comment by FiniteStateGit** [comment]
The PhysX Characters Gem is not linked from https://o3deorg.netlify.app/docs/user-guide/gems/reference/#physics @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
