### ISSUE TITLE
[Obsolete materials]: O3DE User guide: PhysX: Page contains images about Lumberyard

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#284]
Link to page: https://o3deorg.netlify.app/docs/user-guide/gems/reference/physx/

The picture on the page includes information about Lumberyard (Setup Assistant) instead of O3DE. Setup Assistant has been deprecated on O3DE.
![image](https://user-images.githubusercontent.com/80751316/112120556-a9939280-8bbe-11eb-82c0-bb7d2ce99cb0.png)

**Comment by FiniteStateGit** [comment]
Page now found at https://o3deorg.netlify.app/docs/user-guide/gems/reference/physics/nvidia/physx/ and no longer includes references to the Setup Assistant. @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
