### ISSUE TITLE
[Obsolete materials]: O3DE User guide: Maestro Gem: Page contains images about Lumberyard

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#285]
Link to page: https://o3deorg.netlify.app/docs/user-guide/gems/reference/maestro/

The picture on the page includes information about Lumberyard (Setup Assistant) instead of O3DE. Setup Assistant has been deprecated on O3DE. Also the image is referring to Lumberyard instead of O3DE.
![image](https://user-images.githubusercontent.com/80751316/112120932-fbd4b380-8bbe-11eb-879f-1dd737fff1f4.png)

**Comment by FiniteStateGit** [comment]
Page now found at https://o3deorg.netlify.app/docs/user-guide/gems/reference/animation/maestro/ and no longer includes references to the Setup Assistant. @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
