### ISSUE TITLE
[Obsolete materials]: O3DE User guide: Input Management Framework Gem: Page contains images about Lumberyard

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#286]
Link to page: https://o3deorg.netlify.app/docs/user-guide/gems/reference/input/

The picture on the page includes information about Lumberyard (Setup Assistant) instead of O3DE. Setup Assistant has been deprecated on O3DE.
![image](https://user-images.githubusercontent.com/80751316/112123916-0f354e00-8bc2-11eb-897d-2beb93adfe17.png)

**Comment by FiniteStateGit** [comment]
The Input Management Framework Gem is no longer linked at https://o3deorg.netlify.app/docs/user-guide/gems/reference/#input
@LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
