### ISSUE TITLE
[Obsolete materials]: O3DE User guide: Gestures Gem: Page contains images about Lumberyard

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#287]
Link to page: https://o3deorg.netlify.app/docs/user-guide/gems/reference/gestures/

The picture on the page includes information about Lumberyard (Setup Assistant) instead of O3DE. Setup Assistant has been deprecated on O3DE.
![image](https://user-images.githubusercontent.com/80751316/112124356-8c60c300-8bc2-11eb-89f0-db72479d5d2b.png)

**Comment by FiniteStateGit** [comment]
Page now found at https://o3deorg.netlify.app/docs/user-guide/gems/reference/input/gestures/ and no longer includes references to the Setup Assistant.  @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
