### ISSUE TITLE
[Obsolete materials]: O3DE User guide: GameState Samples Gem: Page contains images about Lumberyard

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#288]
Link to page: https://o3deorg.netlify.app/docs/user-guide/gems/reference/game-state-samples/

The picture on the page includes information about Lumberyard (Setup Assistant) instead of O3DE. Setup Assistant has been deprecated on O3DE.
![image](https://user-images.githubusercontent.com/80751316/112124684-e792b580-8bc2-11eb-8d7a-6c937ab85c13.png)

**Comment by FiniteStateGit** [comment]
The page is now found at https://o3deorg.netlify.app/docs/user-guide/gems/reference/gameplay/game-state-samples/ and no longer includes references to the Setup Assistant. @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
