### ISSUE TITLE
[Obsolete materials]: O3DE User guide: GameState Gem: Page contains images about Lumberyard

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#289]
Link to page: https://o3deorg.netlify.app/docs/user-guide/gems/reference/game-state/

The picture on the page includes information about Lumberyard (Setup Assistant) instead of O3DE. Setup Assistant has been deprecated on O3DE.
![image](https://user-images.githubusercontent.com/80751316/112125238-80293580-8bc3-11eb-9e34-15aa6fb14992.png)

**Comment by FiniteStateGit** [comment]
The page is now found at https://o3deorg.netlify.app/docs/user-guide/gems/reference/gameplay/game-state/ and no longer includes references to the Setup Assistant. @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
