### ISSUE TITLE
[Formatting]: Reusing Vegetation in Multiple Areas: An image is inline with text

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#290]
Link: https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/reuse/

An image on the page is placed inline with text causing it to break the page layout (most noticeable when resizing the page's width).

The image:
![Reusing](https://user-images.githubusercontent.com/80751316/112117156-53712000-8bbb-11eb-9db5-b02e5a1779ce.PNG)

**Comment by FiniteStateGit** [comment]
Hello @LB-RobertBaczkowski this issue should be resolved with #870 merged.  Thank you for raising the issue.

**Comment by LB-RobertBaczkowski** [comment]
The page has been moved to https://o3de.org/docs/user-guide/gems/reference/environment/vegetation/procedures/reuse/ . The issue no longer occurs.
