### ISSUE TITLE
[Formatting] O3DE User guide: Render to Texture: Section topic is repeated  

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#295]
Link to page: https://o3deorg.netlify.app/docs/user-guide/gems/reference/render-to-texture/

In Render to Texture chapter in O3DE User guide, the chapter topic is repeated.
![image](https://user-images.githubusercontent.com/80751316/112119435-aa77f480-8bbd-11eb-84fb-61f4172b2560.png)

**Comment by FiniteStateGit** [comment]
The Render to Texture Gem is no longer linked at https://o3deorg.netlify.app/docs/user-guide/gems/reference/
@LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
