### ISSUE TITLE
[Obsolete Information] O3DE User guide: Gems: Landscape Canvas Gem There is a reference to WAF which is no longer supported

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#296]
Link to page: https://o3deorg.netlify.app/docs/user-guide/gems/reference/landscape-canvas/

In Landscape Canvas Gem chapter in Gems section in O3DE User guide there is reference to WAF, which is no longer supported by O3DE. It was replaced by CMake.

Also in following chapter there are references to Lumberyard.

**Comment by FiniteStateGit** [comment]
Page now found at https://o3deorg.netlify.app/docs/user-guide/gems/reference/environment/landscape-canvas/ and no longer includes references to WAF or Lumberyard. @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
