### ISSUE TITLE
[Obsolete Information] Using Amazon GameLift: Video link leads to Lumberyard's video on Youtube

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#297]
Link to page: https://o3deorg.netlify.app/docs/user-guide/gems/reference/gamelift/gamelift-using/

In Using Amazon GameLift chapter in O3DE User Guide there is link to video which leads to a Lumberyard video on Youtube instead of an O3DE-related video.

**Comment by FiniteStateGit** [comment]
The page is now found at: https://o3deorg.netlify.app/docs/user-guide/gems/reference/aws/aws-gamelift/  
All references to AWS documentation are properly marked as external links on this page and sub-pages.  Pages no longer include any reference to Lumberyard videos.  @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described, all external links are marked correctly.
