### ISSUE TITLE
[Formatting]: O3DE User guide: Cannot collapse/open collapsible chapters in the left navigation menu using chevrons

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#300]
Link: https://o3deorg.netlify.app/docs/welcome-guide/

Collapsible chapters in the navigation menu on the left cannot be opened using the chevrons next to their name. They are opened only when their corresponding chapter is the currently viewed page.

**Comment by FiniteStateGit** [comment]
The navigation menu now opens and collapses properly. @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
