### ISSUE TITLE
[Obsolete Information]: Dynamic vegetation: Multiple images contain deprecated information.

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#301]
Link: https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/

The following images contain deprecated information as of the current build: main-spectra-windows-all-18 (e.g. Component has different properties currently than the ones displayed on the image):
Blocking Vegetation in Select Areas(https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/blockers/): 
![image](https://user-images.githubusercontent.com/80751316/112126737-08f4a100-8bc5-11eb-83f2-de2b222461e4.png)

Creating a Vegetation Layer (https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/layer/):
![image](https://user-images.githubusercontent.com/80751316/112127071-5a049500-8bc5-11eb-8925-394ae31afaed.png)

Creating Weight-Based Random Selection (https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/selection-random/):
![image](https://user-images.githubusercontent.com/80751316/112127288-92a46e80-8bc5-11eb-917c-f4cb1bfaffbe.png)
![image](https://user-images.githubusercontent.com/80751316/112127296-959f5f00-8bc5-11eb-939c-4071fb046509.png)

**Comment by willihay** [comment]
This issue has been addressed. New locations for the topics containing these screenshots:
https://www.o3de.org/docs/user-guide/components/reference/vegetation/vegetation-asset-list/
https://www.o3de.org/docs/user-guide/components/reference/vegetation/vegetation-layer-blocker/
