### ISSUE TITLE
[Obsolete Information]: Dynamic vegetation: Multiple chapters cannot be followed along with due to inability to replicate listed steps

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#302]
Links:
https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/
https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/concepts/
https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/
https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/adding-modifiers/
https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/blockers/
https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/layer/
https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/selection-random/
https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/coverage/
https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/place-random/
https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/reuse/
https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/gradient-random/

Listed links contain instructions regarding creation and modification of vegetation layers, which cannot be verified due to vegetation not being viewable in the viewport in the currently used build: main-spectra-windows-all-18. This is caused by the lack of default terrain.

**Comment by willihay** [comment]
The conditions leading to this issue have been resolved. A default terrain is available.

**Comment by LB-KacperMetelski** [comment]
Issue verified as Fixed.
