### ISSUE TITLE
[Incorrect links] Hyperlink leads the User to Documentation Archive

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#316]
deprecated input system:
Link to page:
https://docs.aws.amazon.com/lumberyard/latest/legacyreference/input-legacy.html

**Comment by FiniteStateGit** [comment]
Page now found at: https://o3de.org/docs/user-guide/interactivity/input/ and no longer includes references to the Deprecated Input System. @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described.
