### ISSUE TITLE
[Obsolete Information]: /O3DE User guide /Packaging and release /Asset bundler /What is the Open 3D Engine Asset Bundler?: Asset Bundler Batch Tool

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#326]
Link to page:
https://o3deorg.netlify.app/docs/user-guide/packaging/asset-bundler/overview/

All tutorial links redirect to 404 pages. Asset Bundler Batch Tool is impossible to use following the instruction in O3DE.
 
"To get started using the Asset Bundler, read the following tutorials" :

- Work with Asset Bundling and the O3DE Starter Game: 
https://o3deorg.netlify.app/docs/user-guide/tutorials/packaging/tutorial-release.md

"This tutorial uses the Starter Game packaged with O3DE and walks you through the general asset bundling process"

- Creating Basic Asset Bundles:
https://o3deorg.netlify.app/docs/user-guide/tutorials/packaging/tutorial-release.md

"This tutorial covers the most simple case for asset bundling and release, using a single seed. Once you’ve worked through this topic, read the extended tutorials for multiple packages and delta patches" . 

Multiple packages:
https://o3deorg.netlify.app/docs/user-guide/tutorials/packaging/tutorial-multiple-bundles.md

Delta Patches:
https://o3deorg.netlify.app/docs/user-guide/tutorials/packaging/tutorial-content-patches.md

Create your own Asset Builders:
https://o3deorg.netlify.app/docs/user-guide/tutorials/assets/custom-builder.md

The missing asset scanning tools:
https://o3deorg.netlify.app/docs/user-guide/packaging/asset-bundler/assets-verifying.md
 
Asset Catalog:
https://o3deorg.netlify.app/docs/user-guide/assets/asset-type-adding.md

Asset Bundling & Release Build Tutorial - Delta Bundles, Patching Content:
https://wiki.agscollab.com/plugins/servlet/samlsso?redirectTo=%2Fpages%2Fviewpage.action%3FpageId%3D81283760

**Comment by FiniteStateGit** [comment]
@sptramer @LB-RobertBaczkowski Asset bundler documentation has been updated.  Can this issue be closed?

**Comment by LB-RobertBaczkowski** [comment]
This issue can be closed, as the information has been updated. However, there's one dead link on the page, which was reported separately as https://github.com/o3de/o3de.org/issues/1224.
