### ISSUE TITLE
[Dead Links]: O3DE User guide /interactivity /user-interface /editor /components /components-spawner

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#354]
Samples Project:
Link to page:
https://o3deorg.netlify.app/docs/userguide/samples/projects/samples.md

**Comment by LB-RobertBaczkowski** [comment]
Reopening the issue, as one internal link is referring to a section that is not on the page: Example UISpawner Component (https://o3de.org/docs/user-guide/interactivity/user-interface/editor/components/components-spawner/#ui-spawner-component-example).

**Comment by sptramer** [comment]
Section can either be removed or have a sample written for it (or both; first one, then the other.)

**Comment by FiniteStateGit** [comment]
A search for `#ui-spawner-component` in the source didn't return any matches.  May have been resolved with #921.

**Comment by LB-RobertBaczkowski** [comment]
The internal link has been removed, closing the issue.
