### ISSUE TITLE
[Obsolete Information]: O3DE User guide /Testing and optimization /Profiler /Profiler Tutorial /

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#365]
Link to page:
https://o3deorg.netlify.app/docs/user-guide/testing/profiler/tutorial/

3DE’s built-in applications don't have AzFramework::TargetManagementComponent added by default. Profiler tool is unable to connect to the GridHub.

Profiler Tutorial:

Registering Your Application: 
https://o3deorg.netlify.app/docs/user-guide/testing/profiler/tutorial/#profiler-registering-application

To enable Profiler to capture information from your application, you must first register the application in GridHub. To do so, add AzFramework::TargetManagementComponent to the application’s SystemComponent".

"Note: O3DE’s built-in applications already have this component added by default".

Presented instructions are impossible to be done step by step without Profiler tool connected to the GridHub.

Using Profiler for VRAM:
https://o3deorg.netlify.app/docs/user-guide/testing/profiler/vram/

Using the Profiler for CPU Usage:
https://o3deorg.netlify.app/docs/user-guide/testing/profiler/cpu/

**Comment by LB-MateuszSzweda** [comment]
Verified as fixed on 11/17/2022 the pages from the description were correctly removed and result in 404 Page not found on multiple web browsers.
