### ISSUE TITLE
Assets | Use semantic names for comparisons with bundler

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#392]
In the existing asset bundler documentation (`/docs/user-guide/packaging/asset-bundler/`) there's the use of numeric identifiers for operations instead of semantic, human-readable names. These should be replaced anywhere that the numeric arguments are used for `--comparisonType`:

>     0 -> delta
>     1 -> union
>     2 -> intersection
>     3 -> complement
>     4 -> filePattern
>     5-> intersectionCount

**Comment by FiniteStateGit** [comment]
@sptramer Delta operations were updated to include semantic names I believe: https://o3deorg.netlify.app/docs/user-guide/packaging/asset-bundler/list-operations/.  Can this be closed?

**Comment by willihay** [comment]
Verified that there are no more instances of a numeric identifier being used instead of a human-readable name for the bundler comparisonType.
