### ISSUE TITLE
[OBSOLETE] Update canvas placement to use new physics engine

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#400]
**Page**: `content\docs\user-guide\interactivity\user-interface\editor\placing-canvases-3d.md`

**Description**: This page is simply out of date, and uses information from the legacy physics system of earlier pre-O3DE products. It should be cleaned up and updated to be accurate.

**Comment by willihay** [comment]
Updated in PR https://github.com/o3de/o3de.org/pull/1852
