### ISSUE TITLE
[IMPROVEMENT] Serialization inheritance mechanisms

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#402]
**Section**: content\docs\user-guide\engine\serialization

**Description**: As part of the object registration documentation for serialization, should add a more in-depth explanation of how inheritance (including multiple inheritance) is treated by the system.

**Comment by willihay** [comment]
Closing in preference of a more broadly stated issue regarding this content (https://github.com/o3de/o3de.org/issues/517).
