### ISSUE TITLE
[EXAMPLE] Custom serialization contexts

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#403]
**Section**: content\docs\user-guide\engine\serialization

**Description**: There's no current example usage of custom serialization contexts or why they might be used, although the API reference is available. An example and possibly an overview of cases where they're useful should be added.

**Comment by willihay** [comment]
Many examples of using the serialization context are available in this topic: https://www.o3de.org/docs/user-guide/programming/components/reflection/serialization-context/
