### ISSUE TITLE
[Download page] create mkt content for the page

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de.org#409]
The Download page should include the following info-

- Download buttons for installer and source code download
- marketing messages highlighting the features of O3DE, and the differences between installer and source code download
- Intro of what users should do with the source code
- Release notes for the latest version
- Links to download the previous versions

Here's a design reference-
![download](https://user-images.githubusercontent.com/75449675/114092086-554f0a80-986e-11eb-85b3-e4791333056d.png)

**Comment by sptramer** [comment]
@celestehorgan @yuyihsu @erickson-doug I'm assuming this should be closed?

**Comment by yuyihsu** [comment]
we've fixed this.
