### ISSUE TITLE
[REFERENCE] gem.json reference

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#416]
*Page*: `docs\user-guide\gems\development\creating\manifest.md`

*Description*: This page needs to be updated to contain a full reference for the `gem.json` manifest that is used by each Gem. We still need to discuss where reference materials for file formats live so this can either stay here, or in a reference appendix.

**Comment by lmbr-pip** [comment]
This page is still blank: https://o3de.org/docs/user-guide/gems/development/creating/manifest/

Would be good to provide overview of the schema and requirements for fields.

**Comment by willihay** [comment]
New location should be: https://o3de.org/docs/user-guide/programming/gems/manifest/
