### ISSUE TITLE
Serialization improvements / copyedit

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#433]
The section on serialization (https://github.com/o3de/o3de.org/tree/main/content/docs/user-guide/engine/serialization) never recieved an initial copy edit pass and may contain some inaccuracies as a result.

This is a known part of the guide which is finished content but **not** finished copy, making it an ideal place for a first-time copyedit contributor.

**Comment by willihay** [comment]
[Audit] New section location: https://www.o3de.org/docs/user-guide/programming/serialization/

**Comment by willihay** [comment]
Closing in preference of a more broadly stated issue regarding this content (https://github.com/o3de/o3de.org/issues/517).
