### ISSUE TITLE
Layers information is out of date

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#435]
The information on the layers page (https://o3deorg.netlify.app/docs/user-guide/editor/layers/) for the Editor is apparently out of date. Based on a ticket export, the following information is inaccurate:

> In section "Layer-Specific Components", the following statement is false - "Any given component can appear in only one context menu."

An ambitious contributor might like to also update the screenshots on this page, or update other out of date information.

**Comment by FiniteStateGit** [comment]
Layers were removed from O3DE and page is no longer published.
