### ISSUE TITLE
Tutorial: Including Editor components in a Gem

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#437]
Since many Gems will include their own UI elements for the Editor to support custom workflows or other Gems, one of our first tutorials on how to integrate dependencies (in this case: Qt) with a Gem that provides support to an O3DE core tool (the Editor). This will let us document practices, conventions, and other things that we might want to socialize as part of the initial wave of Gems as well.

**Comment by chanmosq** [comment]
This tutorial shows how to extend the Editor by creating a new tool in editor tool, working with Qt, and interfacing with O3DE components. There's a version for C++ and Python, as you can use either language to create a tool. 

https://www.o3de.org/docs/learning-guide/tutorials/extend-the-editor/

I believe that covers the need for this tutorial.
