### ISSUE TITLE
Clean formatting in code blocks

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#439]
During the export of materials from our original documentation source, some information like typesetting within code blocks was lost - this affects both language selection **and** placeholder text. The placeholder text is often fairly clear about the intent, and could be modified within the parameters of the new style guide (to enclose replacable elements with `<...>`).

Obviously, many code samples are out of date and need other types of evaluation. This issue is almost certainly part of a larger cleanup project.

**Comment by willihay** [comment]
Many fixes have been made to content that was imported from the original source. Specific issues can be filed from here on out.
