### ISSUE TITLE
Creating Gems with code

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#448]
This will be a new tutorial showing the process for taking _uncompiled_ code and including it in a Gem for distribution. 

## Key concepts

*    Creating a new Gem
*    Conventions for structuring a Gem
*    Writing CMake files for the Gem (note: While we will offload most of the reference stuff to CMake, tutorial content like this isn't bad.)

Optional and potentially suggested:

*    Preparing a Gem for distribution (this might be especially important for asset-only Gems, which ship as binaries.)
* Using the Gem in a project

**Comment by chanmosq** [comment]
This task will produce documentation that addresses the following questions in this [discussion comment](https://github.com/o3de/sig-docs-community/discussions/16#discussioncomment-1591717):

>  Where to expand your main game project code by creating new classes and writing code (not gems)?

**Comment by chanmosq** [comment]
This task is partially done by this tutorial: https://github.com/o3de/o3de.org/pull/1119

**Comment by chanmosq** [comment]
Closing thanks to new [Component docs](https://github.com/o3de/o3de.org/pull/1494) and a [code template](https://github.com/o3de/o3de/pull/8462) to create components.
