### ISSUE TITLE
Build workflow instructions - Linux host+target dedicated

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#479]
## Describe the issue briefly.

We need instructions on how to build for each viable host platform. This is critical day-one content for any platform which we declare support. Currently, we are targeting support for Linux as a host platform for dedicated O3DE servers. This topic will cover building dedicated server projects **only** and does not cover Linux clients. This separation is in part due to the staggering of Linux milestones in engineering.

## Which page(s) / section(s) are affected?

* Basic build instructions: https://o3deorg.netlify.app/docs/user-guide/build/
* Linux platform instructions: https://o3deorg.netlify.app/docs/user-guide/platforms/linux/

## Does this work have an engineering dependency? What is it?

Yes. This documentation requires the stable support for the following available in O3DE:

* Linux dedicated server

**Comment by willihay** [comment]
Issue has been addressed with instructions in the locations mentioned in this issue, as well as in the Get Started guide (e.g. https://www.o3de.org/docs/welcome-guide/create/creating-projects-using-cli/creating-linux/ ).
