### ISSUE TITLE
Build workflow instructions - Android target

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#481]
## Describe the issue briefly.

We need instructions on how to build for each viable target platform. This is critical day-one content for any platform which we declare support. Currently, we are targeting support for Android as a target platform from _any_ host platform.

## Which page(s) / section(s) are affected?

* https://o3deorg.netlify.app/docs/user-guide/platforms/android/

**NOTE:** Because any host can target Android, only the Android section needs updates. However there should be a tabbed code box similar to the Build landing page which allows you to select a host platform for building Android as a target, for quickstart.

## Does this work have an engineering dependency? What is it?

Yes. This documentation requires the stable support for the following available in O3DE:

* Android target support
* Support for each host (Linux, macOS, Win10) building to Android as a target.

**NOTE:** If Android target support is stable before host->Android support is stable for all platforms, this ticket should be broken up upon work starting.

**Comment by thefranke** [comment]
Is this ticket still valid? We have the following docs.

Wiki entry:
https://github.com/o3de/wikicollection/wiki/Android-Build-Notes

Markdown files:
https://github.com/o3de/o3de.org/blob/main/content/docs/user-guide/platforms/android/_index.md
https://github.com/o3de/o3de.org/blob/main/content/docs/user-guide/platforms/android/generating_android_project_windows.md

**Comment by willihay** [comment]
[Audit] Initial information requested in this issue was provided in https://github.com/o3de/o3de.org/pull/811 and subsequent updates.
