### ISSUE TITLE
Minimum device specs: Android & iOS

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#483]
## Describe the issue briefly.

Users need to know which minimum devices (both hardware and OS revs/APIs) that O3DE supports. Our information is out of date and needs to be updated. This requires contacting the `sig-platforms` group to get requirements, or source-diving to find minimum allowed targets in the build system.

## Which page(s) / section(s) are affected?

* Android landing: https://o3deorg.netlify.app/docs/user-guide/platforms/android/
* iOS landing: https://o3deorg.netlify.app/docs/user-guide/platforms/ios/
* Requirements reference (#482): https://o3deorg.netlify.app/docs/user-guide/appendix/

## Does this work have a dependency on another docs issue?

Yes: #482

**Comment by willihay** [comment]
Supported host and target platforms are now covered here: https://www.o3de.org/docs/welcome-guide/supported-platforms/

Host hardware requirements are covered here: https://www.o3de.org/docs/welcome-guide/requirements/

Requirements for supported targets are covered here: https://www.o3de.org/docs/user-guide/platforms/
