### ISSUE TITLE
[Obsolete Links] Update social media links in Community Support

### ISSUE THREAD

**Issue by tdoyon-amzn** [o3de/o3de.org#491]
Updated version of #88 , which is partially fixed.

Link: https://o3deorg.netlify.app/docs/welcome-guide/community-support/

When possible, update the following links to the Open 3D Engine social media sites when they become publicly available.

Open 3D Engine on YouTube
(https://www.youtube.com/channel/UCIpwO-VpFfyZcA9h2UnIrUQ/featured)
Open 3D Engine forums
(https://forums.awsgametech.com/)
Open 3D Engine on Discord
(https://discord.com/invite/2CEQyt2)

**Comment by willihay** [comment]
The links are all working at the moment. Closing this issue as obsolete.
