### ISSUE TITLE
[NEW] Crash log debugging

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#515]
## Describe the issue briefly.

Users need to be able to look through crash logs and come to some kind of conclusion about where they can start investigating their core issue.

## Which page(s) / section(s) are affected?

New content should appear in the [core engine documentation](https://docs.o3de.org/docs/user-guide/engine/).

## Does this work have an engineering dependency? What is it?

No known dependencies.

**Comment by willihay** [comment]
New content is now available here: https://www.o3de.org/docs/user-guide/programming/debugging/
From PR https://github.com/o3de/o3de.org/pull/2174
