### ISSUE TITLE
[NEW] - Debugging hub and conceptual

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#516]
## Describe the issue briefly.

We require docs on what debugging support is available, how users may need to configure environments to support O3DE debugging, and information on the types of internal error messages produced by O3DE which a user can use to debug/diagnose issues in their project or the engine core.

## Which page(s) / section(s) are affected?

This should be a sub-section of the [core engine features](https://docs.o3de.org/docs/user-guide/engine/).

## Does this work have an engineering dependency? What is it?

No known dependencies.

**Comment by willihay** [comment]
https://www.o3de.org/docs/user-guide/programming/debugging/
