### ISSUE TITLE
[UPDATE] Asset processing on images

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#523]
## Describe the issue briefly.

Information on using the asset processor on images is very much out of date - refers to the legacy rendering and asset system, among other issues. This needs to be cleaned up and updated to reference the correct way to build image assets.

## Which page(s) / section(s) are affected?

* [Image naming conventions](https://o3deorg.netlify.app/docs/user-guide/assets/pipeline/using-image-naming-conventions/) - Should also be moved to reference
* [Generating Mipmaps](https://o3deorg.netlify.app/docs/user-guide/assets/pipeline/mipmaps/)
* [Processing presets](https://o3deorg.netlify.app/docs/user-guide/assets/pipeline/creating-image-processing-presets/)
* [Image processing configuration](https://o3deorg.netlify.app/docs/user-guide/assets/pipeline/configuring-image-processing/)

Other sections in [Asset Pipeline](https://o3deorg.netlify.app/docs/user-guide/assets/pipeline/) may be affected.

## Does this work have an engineering dependency? What is it?

No.

**Comment by micronAMZN** [comment]
These pages were removed at some point. New texture processing documentation is in #1459
