### ISSUE TITLE
[ISSUE][DOCS] Missing docs for AzAutoGen

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#551]
## Describe the issue

The existing documentation for the AzAutoGen system (nee: AzCodeGen) is incredibly out of date and describes a system no longer in use. This section needs to be dumped and rewritten, and has the advantage that the AzAutoGen replacement system is dirt-simple, has lots of internal documentation already, and has good examples in the source code as-is.

## Impacted page(s)

https://o3de.org/docs/user-guide/engine/autogen/

## Expected experience

Accurate and up to date information on AzAutoGen including:

* An overview
* An example of basic usage
* A reference for command-line options

**Comment by chanmosq** [comment]
Done. https://www.o3de.org/docs/user-guide/programming/autogen/
