### ISSUE TITLE
[ISSUE][DOCS] system requirements should be clearer about Visual Studio

### ISSUE THREAD

**Issue by thoraxe** [o3de/o3de.org#615]
## Describe the issue
Right now the Visual Studio system requirements are not super clear. There is a reference to install VS but then a note later about "you can use community version". But there's also no mention of what VS components to make sure to install.

## Impacted page(s)
`/docs/welcome-guide/setup/requirements/`

## Expected experience
Ideally, we should be more explicit about which versions of what, and also the additional components and/or steps for the VS installation/requirement.

**Comment by sptramer** [comment]
Looks valid, go ahead and submit a PR to reorganize the topic. When we find issues like these it's probably easier to get contributions than do a full triage.

**Comment by thoraxe** [comment]
fixed by #765
