### ISSUE TITLE
[ISSUE][DOCS] Kythera ID docs need a style/edit pass

### ISSUE THREAD

**Issue by erickson-doug** [o3de/o3de.org#655]
## Describe the issue

The 3D splines topic and Node Reference topics need edit and style passes. All docs need edit review.

## Impacted page(s)

Please review the pages in this (closed) pull request: https://github.com/o3de/o3de.org/pull/611 

## Expected experience

Edit and style improvements for consistency across the site.

**Comment by willihay** [comment]
Stale and outdated.
