### ISSUE TITLE
[SITE][FEATURE] Add RSS for the blog

### ISSUE THREAD

**Issue by thefranke** [o3de/o3de.org#666]
## Describe the feature you'd like available on the website

Currently the blog has no RSS: https://o3de.org/blog/
It would be immensely practical, as many (game) developers use RSS to follow resources. The blog will have a much wider constant audience with it.

## Proposed implementation

Generate RSS in the blog backend and add to the header of the page. I was not able to figure out which backend the blog is generated with (Wordpress, static blog generator...) so I do not have a specific proposal.

**Comment by willihay** [comment]
Per sig triage guidelines, adding needs-triage label to website issues

**Comment by thefranke** [comment]
You can now subscribe via RSS to o3de.org here:

https://o3de.org/feed/
