### ISSUE TITLE
[DOCS] Need replacement instructions for accessing FBX Settings' soft naming conventions

### ISSUE THREAD

**Issue by willihay** [o3de/o3de.org#668]
## Describe the issue briefly

FBX Settings has a topic on viewing soft naming conventions. Obsolete documentation on how to find these settings in Lumberyard's Project Configuration (Advanced Editor Settings - Scene Processing Config) was removed. If there's a replacement, then new instructions should be provided.

## Which page(s) / section(s) are affected?

https://o3de.org/docs/user-guide/assets/fbx-settings/settings-soft-naming/#viewing-soft-naming-conventions

## Does this work have an engineering dependency? What is it?

No sure.

**Comment by micronAMZN** [comment]
Currently, there is no replacement for this editor. The default soft naming conventions are defined with regular expressions in `SceneProcessingConfigSystemComponent.cpp`.
