### ISSUE TITLE
[DOCS] Atom Sample Viewer

### ISSUE THREAD

**Issue by chanmosq** [o3de/o3de.org#687]
## Describe the issue briefly

The Atom Guide contains the Atom Sample Viewer section, which needs documentation. What is the Atom Sample Viewer? A standalone application built using O3DE that showcases Atom's features, and demonstrates samples of how the those features are developed. 

The Atom Sample Viewer can be downloaded here: [https://github.com/o3de/o3de-atom-sampleviewer](https://github.com/o3de/o3de-atom-sampleviewer).
How to set up the ASV project can be found here: http://o3de.org/docs/atom-guide/setup-atom-projects/

## Which page(s) / section(s) are affected?

File directory: `atom-guide/atom-sample-viewer/`
- `debug-menu.md`
- `graphics-feature.md`
- `rhi.md`
- `rpi.md`

Website link: https://o3de.org/docs/atom-guide/atom-sample-viewer/

## Does this work have an engineering dependency? What is it?

This documentation depends on the Atom team who worked on the implementation of these samples. We need to gather a status update on these features and some documentation on what the sample is about, any technical details about the implementation, and what options the user can adjust to interact with the sample.

**Comment by sptramer** [comment]
Should be moved to https://github.com/o3de/o3de-atom-sampleviewer README, and removed from the website.

**Comment by willihay** [comment]
Removed in PR https://github.com/o3de/o3de.org/pull/2204, in favor of keeping the documentation in a README.md file in the [atom-sampleviewer repository](https://github.com/o3de/o3de-atom-sampleviewer).
