### ISSUE TITLE
[BROKEN LINK] Link to actual Contribution Guides are missing

### ISSUE THREAD

**Issue by spotzz** [o3de/o3de.org#690]
## Which page has the broken link?
https://o3de.org/contribute/

## Which link was broken?

Under Contribution Guides there is a link to the CoC but not one to the actual Contributing Guide or possibly guides

## Know where it should go?

In theory, each repo should have their own CONTRIBUTING.md file even if the same one is used in each location. The only one I found so far is https://github.com/o3de/o3de.org/blob/main/CONTRIBUTING.md which addresses Documentation contributions.

**Comment by erickson-doug** [comment]
@sptramer Can you investigate?

**Comment by sptramer** [comment]
Right now our contributing guides aren't very specific for O3DE, other than that you're required to follow the code of conduct and the guides on the website: https://github.com/o3de/o3de/blob/development/CONTRIBUTING.md
