### ISSUE TITLE
[BROKEN LINK] to docs in Before you do anything section

### ISSUE THREAD

**Issue by bonniekeller** [o3de/o3de.org#704]
## Which page has the broken link?

https://o3de.org/docs/contributing/to-docs/get-started/

## Which link was broken?

The link to the docs in the Before you do anything section.
It’s important to be familiar with the O3DE documentation and get a feel for its style. Take some time to browse the O3DE documentation. (https://www.o3de.org/docs doesn't work, https://3de.org/docs/ does).

## Know where it should go?

https://3de.org/docs/

**Comment by willihay** [comment]
Thanks for spotting this broken link! The correct link is not 3de.org, however. It should be [https://o3de.org/docs](https://o3de.org/docs). I will fix.

**Comment by bonniekeller** [comment]
You're welcome, I think I had a copy/paste fail there.
