### ISSUE TITLE
[BUG][WEBSITE] Search bar missing in Firefox

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#710]
## Describe the bug

The site search bar in the upper right of the website is missing on Firefox, but present on Chrome (and possibly other browsers.)

## Reproduction steps

1. Load http://o3de.org
2. Examine the upper-right of the website top menu
3. The search icon should be visible.

## Expected behavior

The search icon is visible on all browsers.

## Screenshots

![firefox-browser](https://user-images.githubusercontent.com/169061/124815855-9eb9ff00-df1c-11eb-9995-a6448cd238cb.png)
**Appearance in Firefox**

![chrome-browser](https://user-images.githubusercontent.com/169061/124815876-a5e10d00-df1c-11eb-8da2-54b1a49ac044.png)
**Appearance in Chrome**

## Other information

* **OS**:  Windows 10.0.19043 Build 19043
* **Browser**: Firefox 78.11.0esr (64-bit)

**Comment by erickson-doug** [comment]
Fixed with PR #715.
