### ISSUE TITLE
Differences between the YouTube and the written guide for "Setting up O3DE from GitHub"

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de.org#713]
## Describe the issue
It has been noticed that there are differences between the YouTube guide and the written one. Bellow are listed differences.

Requirements differences:
- free disk space 40-100 GB vs 60 GB.
- cmake version 3.20.5 vs 3.20

Guide differences:
- "git config lfs.url" command is not used in the YT version.
- commands used are different: 
`cmake -B build/windows_vs2019 -G "Visual Studio 16" -DLY_3RDPARTY_PATH=C:\o3de-packages -DLY_UNITY_BUILD=ON -DLY_VERSION_ENGINE_NAME=o3de-install -DCMAKE_INSTALL_PREFIX=C:\o3de-install`
`cmake -B build/windows_vs2019 -G "Visual Studio 16" -DLY_3RDPARTY_PATH=C:\o3de-packages -DLY_UNITY_BUILD=ON -DLY_PROJECTS=AutomatedtTesting`
and
`cmake --build build/windows_vs2019 --target INSTALL --config profile -- /m`
`cmake --build build/windows_vs2019 --target AutomatedTesting.Gamelauncher Editor --config profile -- /m`

## Impacted page(s)

[Setup page](https://docs.o3de.org/docs/welcome-guide/setup/setup-from-github/)

## Expected experience

The guides differs which may lead to the different outcome.

**Comment by willihay** [comment]
A newer setup video is available and the setup page will be updated. In general, as the presenter says, the video may lag behind the latest info in the docs.
