### ISSUE TITLE
[BROKEN LINK] Customize FBX asset export with FBX Settings

### ISSUE THREAD

**Issue by SolemnZeno** [o3de/o3de.org#770]
## Which page has the broken link?

https://o3de.org/docs/user-guide/visualization/animation/char-intro/

## Which link was broken?

O3DE has the FBX Settings tool that converts static .fbx meshes, skeletons, skins, animations, and materials into O3DE assets. For more information, see Customize FBX asset export with FBX Settings.

https://o3de.org/docs/user-guide/assets/fbx-settings/intro.md

## Know where it should go?

I believe it's supposed to go here:
https://o3de.org/docs/user-guide/assets/fbx-settings/

**Comment by PratikBorhade302** [comment]
Would like to fix this. can someone assign it to me? Not sure how I can assign to myself :)
