### ISSUE TITLE
[SITE][FEATURE] Pressing O3DE logo in o3de.org/docs/ should lead back to docs and not main page

### ISSUE THREAD

**Issue by ppinfel** [o3de/o3de.org#802]
## Describe the feature you'd like available on the website
I think it will be more natural when while in o3de.org/docs/ that pressing the O3DE logo on the upper left leads back to o3de.org/docs/ rather than o3de.org main page

**Comment by willihay** [comment]
I like where you're going with this. What if the logo still went back to o3de.org, but choosing "Learn" went to o3de.org/docs?

**Comment by ppinfel** [comment]
That might be good, but maybe "Learn" could be moved to the right side of the bar instead of next to the logo. 

I'm not really sure about this whole feature request idea anymore... Since it might catch some people off guard initially but once you know about it navigation around the site is pretty intuitive
