### ISSUE TITLE
[BROKEN LINK] to custom script node development

### ISSUE THREAD

**Issue by andreasplesch** [o3de/o3de.org#803]
## Which page has the broken link?

https://docs.o3de.org/docs/user-guide/scripting/script-canvas/best-practices/

## Which link was broken?

```[Creating Custom Nodes in Script Canvas](/docs/user-guide/engine/scripting/script-canvas/_index.md).```
https://docs.o3de.org/docs/user-guide/engine/scripting/script-canvas/_index.md

## Know where it should go?

likely https://docs.o3de.org/docs/user-guide/scripting/script-canvas/development/

see https://github.com/andreasplesch/o3de.org/commit/f2717e0c3ae69b5f7b44c4a1f481e9ab9b8142ec

if a quick PR is desirable.

**Comment by PratikBorhade302** [comment]
>if a quick PR is desirable.
Thanks for the PR. As far as I can tell you should check following page to submit the PR: https://github.com/o3de/o3de.org/blob/main/CONTRIBUTING.md#submitting-documentation-pull-requests

**Comment by andreasplesch** [comment]
Thanks for the link on how to contribute. I updated my branch (https://github.com/andreasplesch/o3de.org/tree/patch-1) to include a DCO for the last commit, and would be happy to PR. However, I am uncertain that 

- the proposed fix for the link is correct
- a fix is currently desired at all since there are many broken and unfinished pages which may be better addressed together rather than in tiny commits.
- the broken link may be intended, as a reminder to complete docs.

It is also always possible for somebody else to grab my branch and do the PR.

**Comment by andreasplesch** [comment]
@PratikBorhade302, I saw you had similar PRs and thus went ahead.

**Comment by andreasplesch** [comment]
PR #816 has a corrected DCO.

**Comment by PratikBorhade302** [comment]
@andreasplesch , great! You will have to wait for project member to review the PR :)

**Comment by willihay** [comment]
Thanks for all your work getting up to speed on contributing to the docs to fix the broken link here. And yes, the Script Canvas section needs a lot of post-migration work, and will likely be updated and reorganized, but that will take some time. We might as well fix some broken links in the meantime to help people who are actively trying to use these docs as-is.

**Comment by andreasplesch** [comment]
Super !
