### ISSUE TITLE
[BUG][WEBSITE] Right TOC appears at the bottom of the page.

### ISSUE THREAD

**Issue by chanmosq** [o3de/o3de.org#818]
## Describe the bug

Pages are supposed to render a table of contents (TOC) at the right of the page, when the page's `toc` metadata is set to true. The problem is that sometimes the TOC renders at the bottom of the page. See **Actual** in the Screenshots section. 

This problem can be seen in this page of the docs: https://o3de.org/docs/user-guide/project-config/cli-reference/

## Reproduction steps

Steps to reproduce the behavior, as a numbered list:

1. Go to the web page: https://o3de.org/docs/user-guide/project-config/cli-reference/
2. Notice that the right TOC is at the right of the side. 

## Expected behavior

The right TOC should appear on the right side. See **Expected** in the Screenshots section.

## Screenshots

**Expected:** The right TOC is at the right of the page. 
![image](https://user-images.githubusercontent.com/75444793/129643316-74d8e0a5-2894-4648-bc07-c2bd36c1e2f1.png)

**Actual:** Right TOC is at the bottom of the page. 
![image](https://user-images.githubusercontent.com/75444793/129643154-be935762-8b49-44c2-8d3f-8a5e37d95ecb.png)

## Other information

* **OS**: Windows 10
* **Browser**: Tested on Firefox and Chrome. Window width is 1200px or greater.

**Comment by FiniteStateGit** [comment]
TOC now appears on right side of page.  @chanmosq Can this be closed?

I've edited the page so Format, Usage and Optional Parameters are not repeated in the TOC in PR https://github.com/o3de/o3de.org/pull/874.

**Comment by chanmosq** [comment]
@FiniteStateGit Thanks for checking on this. It seems that the TOC does appear on the right side _without_ making any changes to the page's contents or headers. 

We can close this.
