### ISSUE TITLE
[WEBSITE] Need robots.txt to assist in indexing

### ISSUE THREAD

**Issue by sptramer** [o3de/o3de.org#829]
## Describe the issue

According to our traffic reports, the #1 requested unavailable resource remains `robots.txt` - apparently the site has attempted to be indexed ~4000 times. Adding this file would probably help with site indexing and offer us other advantages - I'm not familiar enough with modern `robots.txt` to know what we'd get out of it.

**Comment by FiniteStateGit** [comment]
From http://www.robotstxt.org/robotstxt.html :

`robots.txt`
``` txt
User-agent: *
Disallow:
```

The `robots.txt` file above allows all crawling.  If there is no `robots.txt` file present, all crawling is allowed, though perhaps some crawlers decline to.  If you wanted to make the current crawling policy explicit, I could PR the addition of `robots.txt`.

**Comment by sptramer** [comment]
Closing this for now, we have a robots.txt... although the staging sites are being indexed now as well.
