### ISSUE TITLE
[DOCS] Asset Pipeline: Review state of docs

### ISSUE THREAD

**Issue by chanmosq** [o3de/o3de.org#846]
## Describe the issue briefly

We need to review this section to verify that the content is up-to-date by communicating with the Asset Pipeline engineers or sig-content. 

**Output:** A PR that removes obsolete information and updates known information and/or GitHub issues for new documentation that's needed for this section. 

## Which page(s) / section(s) are affected?

`/docs/user-guide/assets/pipeline/*` and links to images in `/static/images/*`.

## Does this work have an engineering dependency? What is it?

Engineers who own Asset Pipeline (sig-content) to verify that the section is accurate and up-to-date, and to determine what other information we need in this section. 

## Related issues
- https://github.com/o3de/o3de.org/issues/221
- https://github.com/o3de/o3de.org/issues/220
- https://github.com/o3de/o3de.org/issues/223
- https://github.com/o3de/o3de.org/issues/222
- https://github.com/o3de/o3de.org/issues/226 (partial)
- https://github.com/o3de/o3de.org/issues/224

**Comment by micronAMZN** [comment]
Closing. The Assets topic section has been completely updated.
