### ISSUE TITLE
[BROKEN LINK] No idea how to test the game package and release.

### ISSUE THREAD

**Issue by HHWRyan** [o3de/o3de.org#847]
## Which page has the broken link?

https://o3de.org/docs/user-guide/tutorials/packaging/tutorial-release

## Which link was broken?

https://o3de.org/docs/user-guide/tutorials/packaging/tutorial-release

**Comment by PratikBorhade302** [comment]
Hi, thanks reporting the issue. can you please mention the page where you found the broken link

**Comment by FiniteStateGit** [comment]
@sptramer A search for 'tutorials/packaging' and 'tutorial-release' didn't return anything.  I think this is safe to close.
