### ISSUE TITLE
[Formatting]: Community support: Bullet point list is not easily readable

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#87]
Link to page: https://o3deorg.netlify.app/docs/welcome-guide/community-support/

The bullet point list on the Community support site is formatted so its different references are not easily distinguishable from each other:
*[Getting Started with Open 3D Engine] 
*O3DE also has an ever-growing YouTube channel that’s loaded with additional tutorial videos and presentations. Subscribe and enable notifications so you always know when new videos are released.
*[Open 3D Engine on YouTube] 
*Dive deeper into the features and usage of O3DE with the Open 3D Engine documentation.
*[Open 3D Engine documentation home] 
*Join the online community in the O3DE forums to learn from O3DE staff and users, and share your projects.
*[Open 3D Engine forums] 
*O3DE users have created an unofficial Discord. Join the conversation to share tips and get help from O3DE users.
*[Open 3D Engine on Discord] 

The bullet point list should be either removed and links paired with their description (e.g. change 
*O3DE also has an ever-growing YouTube channel that’s loaded with additional tutorial videos and presentations. Subscribe and enable notifications so you always know when new videos are released.
*[Open 3D Engine on YouTube] 
to
O3DE also has an ever-growing YouTube channel that’s loaded with additional tutorial videos and presentations. Subscribe and enable notifications so you always know when new videos are released. [Open 3D Engine on YouTube])
or remove the bullet points by either descriptions or links so the different references are easily distinguishable from each other.

**Comment by micronAMZN** [comment]
This page has been completely re-organized and is now a table.
