### ISSUE TITLE
[Formatting]: Setup: Page is missing links listed in the navigation menu on the left

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#89]
Link: https://o3deorg.netlify.app/docs/welcome-guide/setup/

The Topics section on the Setting up Open 3D Engine page lists only four out of seven pages listed in the menu on the left. 
(Listed in the topics section:
System requirements
Upgrading O3DE
Enabling a Firewall
Using the Perforce Plugin with O3DE

Listed on the navigation menu on the left:
Open 3D Engine system requirements (System requirements redirects here)
Setup using O3DE installer
Setup O3DE from source
Troubleshooting O3DE setup
Upgrading O3DE
Enabling a Firewall
Using the Perforce Plugin with O3DE)

**Comment by micronAMZN** [comment]
These are all fixed.
