### ISSUE TITLE
[BROKEN LINK] in "Adding and Removing Gems in a Project"

### ISSUE THREAD

**Issue by allisaurus** [o3de/o3de.org#894]
## Which page has the broken link?

https://o3de.org/docs/user-guide/project-config/add-remove-gems/#using-the-command-line-interface-cli

## Which link was broken?

The one for "CLI Reference" (See pic):

![image](https://user-images.githubusercontent.com/34254888/133120685-821c7ca1-a43f-4f6a-93d3-055967a7b558.png)

## Know where it should go?

I think here? https://o3de.org/docs/user-guide/project-config/cli-reference/

**Comment by FiniteStateGit** [comment]
Link correctly points to https://o3de.org/docs/user-guide/project-config/cli-reference/.  This can be closed.
