### ISSUE TITLE
[Obsolete Information]: Create with Open 3D Engine: Text mentions the Project Configurator tool which is missing from the current build

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#92]
Link: https://o3deorg.netlify.app/docs/welcome-guide/get-started/workflows/create-intro/

Text under the section "Starting the Journey" mentions the Project Configurator tool which is not included in the current build: main-spectra-windows-all-11

Text excerpt:
You’ll use the **Project Configurator** tool to set the project that you’re working on. You can use one of the projects that ship with O3DE, such as the Samples Project, if you want to learn or play around with something premade. Or, if you want to start something new, this is also where you create a brand new project, based on the template of your choice.

**Comment by chanmosq** [comment]
The text was replaced with "Project Manager" and has been updated with current information. Also, the link to that page has been updated to this: https://o3de.org/docs/welcome-guide/get-started/create-intro/
This was resolved during initial website development.
