### ISSUE TITLE
[ISSUE][DOCS] Remove or update stale page

### ISSUE THREAD

**Issue by chanmosq** [o3de/o3de.org#934]
## Describe the issue briefly

There is no up-to-date information on animated textures in O3DE. The closest piece of information is this page: [Multiple UV sets for meshes and actors](https://o3de.org/docs/user-guide/assets/fbx-settings/multiple-uv-sets/); however, it references the old Material Editor in Lumberyard. 

Output: Update this page with current information and samples. 

## Which page(s) / section(s) are affected?

https://o3de.org/docs/user-guide/assets/fbx-settings/multiple-uv-sets/

## Does this work have an engineering dependency? What is it?

Yes. It depends on developers for animated textures, which may be owned by sig-graphics-audio.

**Comment by micronAMZN** [comment]
This page has been removed. O3DE supports 2 UV sets by default, which is covered in the new 3D Scene Format Support topic. The new base materials do not have animated oscillator and rotator properties, though, so much of the material here no longer applies.
