### ISSUE TITLE
[Obsolete links]: Create with Open 3D Engine: Multiple links are pointing to Lumberyard materials

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#94]
Link: https://o3deorg.netlify.app/docs/welcome-guide/get-started/workflows/create-intro/

The following links on the page lead to the Lumberyard material:
(Starting the Journey section):
Learn O3DE in 20 Minutes
(https://www.youtube.com/watch?v=E1NgI8urJ7o)
Set Up Open 3D Engine
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-setting-up.html)
Creating a Controllable Entity
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-written-basics-of-motion-overview.html)
Basics of Motion
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-game-engine-101.html)

(Work as an artist section):
Import Assets into O3DE 
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-importing-assets.html)
Animation System and Emotion FX
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-animation-intro.html)
Lighting
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-lighting.html)

(Work as a designer section):
Creating a Controllable Entity
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-written-basics-of-motion-overview.html)
Script Canvas
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-script-canvas-intro.html)
Basics of Motion
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-game-engine-101.html)
Working with Slices
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-slices.html)
Simulate Physics
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-physics.html)
Modify Terrain
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-terrain.html)
Import Assets into O3DE
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-importing-assets.html)
Animation System and Emotion FX
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-animation-intro.html)

(Work as a game engineer section):
Creating a Controllable Entity
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-written-basics-of-motion-overview.html)
Import Assets into O3DE 
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-importing-assets.html)
Script Canvas
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-script-canvas-intro.html)
Working with Slices
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-slices.html)
Working with Gems
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-gems.html)
Simulate Physics
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-physics.html)
Animation System and Emotion FX 
(https://docs.aws.amazon.com/lumberyard/latest/tutorials/tutorials-animation-intro.html)

**Comment by micronAMZN** [comment]
Links have been corrected.
