### ISSUE TITLE
[Formatting]: O3DE Welcome guide: Multiple pages layouts are breaking on resizing their width

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#95]
Links: 
https://o3deorg.netlify.app/docs/
https://o3deorg.netlify.app/docs/welcome-guide/
https://o3deorg.netlify.app/docs/welcome-guide/setup/
https://o3deorg.netlify.app/docs/welcome-guide/get-started/
https://o3deorg.netlify.app/docs/welcome-guide/get-started/project-config/
https://o3deorg.netlify.app/docs/welcome-guide/get-started/project-config/creating-projects-manually/
https://o3deorg.netlify.app/docs/welcome-guide/get-started/workflows/
https://o3deorg.netlify.app/docs/welcome-guide/get-started/intro-game/

Listed pages break the left menu's layout when their window is resized below around 60% of their original width on 1920x1080 resolution and completely vanish when their window is resized below around 30% of its original width on 1920x1080 resolution. This may be a substantial issue on mobile devices such as tablets or phones.

**Comment by FiniteStateGit** [comment]
Table of contents navigation collapses and moves to the hamburger menu on resize.  Tested mobile with same results.  @LB-RobertBaczkowski Could this be closed?

**Comment by LB-RobertBaczkowski** [comment]
Closing the issue as described. Some of the pages are no longer available, which is not a part of the issue.
