### ISSUE TITLE
[Dead links]: Editor tour: Video link leads to an unavailable YouTube video

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#96]
Link: https://o3deorg.netlify.app/docs/welcome-guide/get-started/workflows/editor-tour/

Video linked on the page redirects to an unavailable video (https://www.youtube.com/watch?v=https%3A%2F%2Fwww).

Please refer to the attached image:

![DeadVideoLink](https://user-images.githubusercontent.com/80751316/111468701-27bae980-8726-11eb-9286-b4947cc99a42.PNG)

**Comment by micronAMZN** [comment]
FIxed.
