### ISSUE TITLE
Lack of documentation about Engine as SDK and external projects.

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de.org#960]
### Problem description

While setting up the new project using the engine as SDK the team was wondering where the engine binaries would reside. Since we were setting an external project it was assumed that all the engine binaries would live in the engine and the external project would only need to build the project binaries. It seemed like the external project had to generate all the binaries, even when setup as external project. There was no documentation to find answers to this.

Reported by @moraaar through LY Game Jam

**Comment by willihay** [comment]
Additional information about engine and project binaries has been added to the website. For engine SDK builds:

Under [Build the engine](https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-windows/#build-the-engine):
"when the build is complete, you can find the engine tools and other binaries in C:\o3de-install\bin\Windows\profile\Default."

Under [Build the O3DE project](https://www.o3de.org/docs/welcome-guide/create/creating-projects-using-project-manager/#build-the-o3de-project):
"When the build completes, you can find the project binaries in your project directory under build/<platform>/bin/profile."

Similar information can be found in the User Guide:
https://www.o3de.org/docs/user-guide/build/configure-and-build
