### ISSUE TITLE
Lack of documentation about prefabs and how to spawn/destroy them dynamically

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de.org#962]
### Problem description

There is no documentation about prefabs to explain how to use them. A particular feature that any game needs is the ability to dynamically spawn and destroy prefabs, either by C++, Script Canvas or Lua. In our game case we were generating the world procedurally, so spawning/destroying the world as blocks (prefabs) was a requirement, documentation on how to spawn/destroy prefabs would have helped a lot.

Workaround was to search the code, specially unit tests, for examples of how to spawn/destroy entities.

Reported by @moraaar through LY Game Jam

**Comment by AMZN-stankowi** [comment]
@micronAMZN this issue is marked as completed, but the Prefab documentation page https://www.o3de.org/docs/user-guide/interactivity/prefabs/ is still empty and links to this.

I'd also like to see information on default procedural prefabs as part of the documentation.

**Comment by micronAMZN** [comment]
@AMZN-stankowi The documentation for this issue exists in the tutorials guide https://www.o3de.org/docs/learning-guide/tutorials/entities-and-prefabs/, and has been been recently updated in development for new changes including prefab overrides https://development--o3deorg.netlify.app/docs/learning-guide/tutorials/entities-and-prefabs/. I think the feature documentation page you've linked is included in a list of stub pages that need to be updated. There is an active PR for procedural prefab documentation, it should be merged this week. The prefabs user-guide topic you've linked as well as updates to the assets section (Scene Settings) for procedural prefabs are all very high priority in the coming weeks.
