### ISSUE TITLE
Feature Request: Document the SC framework

### ISSUE THREAD

**Issue by svitlani** [o3de/o3de.org#965]
**Describe the solution you'd like**

As a user, I'd like to leverage the SC framework to help me implement my SC nodes to be consistent with the rest of the notes.

**Comment by FiniteStateGit** [comment]
@willihay @sptramer Could this be closed, as #1182 was merged?

**Comment by willihay** [comment]
@FiniteStateGit There's more documentation work to do to complete the coverage of Script Canvas node implementation. For example, I'm working on updating the docs on creating custom nodes, and I've talked to some UI/UX experts on creating a UX style guide for SC nodes. I think both are important pieces of the "SC framework" umbrella of docs.

I think we could close this issue in favor of these two new issues that are more specific and actionable:
https://github.com/o3de/o3de.org/issues/1226
https://github.com/o3de/o3de.org/issues/1227

@svitlani , what do you think?
