### ISSUE TITLE
Documentation to instruct user how to extend the editor with their tools or workflows

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de.org#966]
### Problem description

As a user, I would like to know how to extend the editor with my own tool or workflow effectively.

**Comment by sptramer** [comment]
https://www.o3de.org/docs/learning-guide/tutorials/extend-the-editor/shape-example-cpp/
https://www.o3de.org/docs/learning-guide/tutorials/extend-the-editor/shape-example-py/
