### ISSUE TITLE
[Obsolete Information]: Editor tour: Multiple issues with included images

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#98]
Link: https://o3deorg.netlify.app/docs/welcome-guide/get-started/workflows/editor-tour/

**_Issue#1_**
**Provided screenshot shows Lumberyard Editor window and the references marked on it do not match the description**
The screenshot provided in "The O3DE Editor default layout" section shows the interface of the Lumberyard Editor Beta and the references on it are marked "A, B, C, D, E, F, G" instead of 
"1. Perspective (corresponds to A on the screenshot)
1. Entity Outliner (corresponds to B on the screenshot)
1. Entity Inspector (corresponds to C on the screenshot)
2. Asset Browser (corresponds to D on the screenshot)
1. Editor Console (corresponds to E on the screenshot)
2. Toolbar (corresponds to F on the screenshot)
3. Perspective Toolbar (corresponds to G on the screenshot)"

Note: The description should be reworked regardless of the change of the provided screenshot. A, B, C, D, E, F, G markings are clear but they should be referenced by these symbols in the description to make it more easily readable.

![LumberyardEditorWindow](https://user-images.githubusercontent.com/80751316/111469678-4372bf80-8727-11eb-93d5-d507c55e4a6c.PNG)

**_Issue#2_**
**The image displaying mouse and WASD keys is missing other listed keys/actions**
On the image under the "Navigating the O3DE Perspective viewport" there are W, A, S, D keys, and mouse shown. Beneath the image there is a list of controls in the Editor:
W - Move forward.
S - Move backward.
A - Move left.
D - Move right.
Q - Move down.
E - Move up.
Z - Focus on selected.
Right mouse + drag - Rotate view, known as mouselook in most games.
Mouse wheel scroll - Zoom view.
Middle mouse + drag - Pan view.
Left mouse - Select entity.
Left mouse + drag - Area select entities.
It feels intuitive to include all keys and actions present (actions could be represented by arrows drawn on the mouse image and e.g. filling a button with color to represent holding it) in the controls
on the image itself.

![MouseKeyboardImage](https://user-images.githubusercontent.com/80751316/111469662-3d7cde80-8727-11eb-95aa-ad460a48de42.PNG)

**_Issue#3_**
**Movement preferences screenshot displays deprecated Global Preferences window**
The first screenshot listed under the "Movement preferences" section shows an old Global Preferences window and options listed within it are different from the current ones as of build: main-spectra-windows-all-11

![MovementPreferences](https://user-images.githubusercontent.com/80751316/111469646-3950c100-8727-11eb-8c8d-55fba468bc7a.PNG)

**Comment by micronAMZN** [comment]
These issues have been fixed.
