### ISSUE TITLE
[ISSUE][DOCS] Broken link to Multiplayer Gem documentation

### ISSUE THREAD

**Issue by Aoredon** [o3de/o3de.org#982]
## Describe the issue

The page does not exist for the Multiplayer Gem documentation

## Impacted page(s)

Multiplayer Gem - https://o3de.org/docs/user-guide/gems/reference/multiplayer/multiplayer

## Expected experience

Documentation should be accessible

**Comment by lmbr-pip** [comment]
Fix for this here: https://github.com/o3de/o3de.org/pull/986

**Comment by sptramer** [comment]
I noticed there are actually a lot of Gem directories missing `_index.md` files - could possibly be taken care of as part of this ticket?

**Comment by FiniteStateGit** [comment]
@sptramer Fixed with #986, Multiplayer gem docs found at: https://o3de.org/docs/user-guide/gems/reference/multiplayer/.  Closing this issue.
