### ISSUE TITLE
[DOCS] Script Canvas Behavior Context content is outdated

### ISSUE THREAD

**Issue by willihay** [o3de/o3de.org#992]
## Describe the issue briefly

Documentation on Script Canvas and the Behavior Context is outdated. The examples refer to legacy (Lumberyard) components that no longer exist, and the knowledge is out of date. Need an update to this important topic!

## Which page(s) / section(s) are affected?

https://o3de.org/docs/user-guide/scripting/script-canvas/programmer-guide/behavior-context/

**Comment by FiniteStateGit** [comment]
@willihay @sptramer Closing this as #1182 was merged.
